import { expect, test } from "./fixtures.ts";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

test("server-path archive actions preserve backups, reject collisions and restore a deleted character", async ({ page }) => {
  const root = await mkdtemp(join(tmpdir(), "shore-browser-server-archives-"));
  const output = join(root, "nova.tar.gz");
  const backup = join(root, "before-delete.tar.gz");
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  try {
    await page.goto("/");
    await page.getByLabel("Daemon token").fill("browser-test-token");
    await page.getByRole("button", { name: "Open workspace" }).click();
    const dialog = page.getByRole("dialog");
    const action = async (label: string) => {
      await page.getByRole("button", { name: "All actions" }).click();
      await page.getByLabel("Find an action").fill(label);
      await dialog.getByRole("button", { name: `${label} Characters`, exact: true }).click();
    };
    const completed = async () => {
      await expect(dialog.getByRole("heading", { name: "Action completed", exact: true })).toBeVisible();
      await dialog.getByText("Complete action result", { exact: true }).click();
    };
    await action("Import character");
    await expect(dialog.getByLabel("Archive on daemon host", { exact: true })).toBeVisible();
    await dialog.getByLabel("Archive on daemon host", { exact: true }).fill(join(root, "missing.tar.gz"));
    await dialog.getByRole("button", { name: "Run action" }).click();
    await expect(dialog.getByRole("alert")).toContainText("Archive not found");
    await dialog.getByRole("button", { name: "Close dialog" }).click();
    await page.getByRole("button", { name: "Create character", exact: true }).click();
    await dialog.getByLabel("Character name", { exact: true }).fill("nova");
    await dialog.getByRole("button", { name: "Run action" }).click();
    await completed();
    await dialog.getByRole("button", { name: "Close dialog" }).click();
    await action("Export character");
    await dialog.getByLabel("Character", { exact: true }).fill("nova");
    await dialog.getByLabel("Archive output on daemon host", { exact: true }).fill("browser-local-name.tar.gz");
    await dialog.getByRole("button", { name: "Run action" }).click();
    await expect(dialog.getByRole("alert")).toContainText("output must be an absolute path");
    await dialog.getByLabel("Archive output on daemon host", { exact: true }).fill(output);
    await dialog.getByRole("button", { name: "Run action" }).click();
    await completed();
    await expect(dialog).toContainText('"call_diagnostics": "included"');
    await expect(dialog).toContainText("rebuild_from_archived_segments");
    const exported = await readFile(output);
    expect(exported.byteLength).toBeGreaterThan(0);
    await dialog.getByRole("button", { name: "Run action" }).click();
    await expect(dialog.getByRole("alert")).toContainText("Refusing to overwrite existing archive");
    expect(await readFile(output)).toEqual(exported);
    await dialog.getByRole("button", { name: "Close dialog" }).click();
    await action("Import character");
    await dialog.getByLabel("Archive on daemon host", { exact: true }).fill(output);
    await dialog.getByRole("button", { name: "Run action" }).click();
    await expect(dialog.getByRole("alert")).toContainText("Refusing to overwrite existing character");
    await dialog.getByRole("button", { name: "Close dialog" }).click();
    await action("Delete character");
    await dialog.getByLabel("Character", { exact: true }).fill("nova");
    await dialog.getByLabel("Repeat character name", { exact: true }).fill("wrong");
    await dialog.getByLabel("Set backup archive on daemon host", { exact: true }).check();
    await dialog.getByLabel("Backup archive on daemon host", { exact: true }).fill(backup);
    await dialog.getByRole("button", { name: "Run action" }).click();
    await dialog.getByRole("button", { name: "Go back" }).click();
    await expect(page.getByRole("navigation", { name: "Characters" })).toContainText("nova");
    await dialog.getByRole("button", { name: "Run action" }).click();
    await dialog.getByRole("button", { name: "Confirm delete", exact: true }).click();
    await expect(dialog.getByRole("alert")).toContainText("repeat the name as confirm");
    await dialog.getByLabel("Repeat character name", { exact: true }).fill("nova");
    await dialog.getByRole("button", { name: "Run action" }).click();
    await dialog.getByRole("button", { name: "Confirm delete", exact: true }).click();
    await completed();
    await expect(dialog).toContainText(backup);
    await expect(dialog).toContainText('"removed"');
    await expect(page.getByRole("navigation", { name: "Characters" })).not.toContainText("nova");
    expect((await readFile(backup)).byteLength).toBeGreaterThan(0);
    await dialog.getByRole("button", { name: "Close dialog" }).click();
    await action("Import character");
    await dialog.getByLabel("Archive on daemon host", { exact: true }).fill(backup);
    await dialog.getByRole("button", { name: "Run action" }).click();
    await completed();
    await expect(dialog).toContainText("queued_for_rebuild_when_retain_is_enabled");
    await dialog.getByRole("button", { name: "Close dialog" }).click();
    await page.getByRole("navigation", { name: "Characters" }).getByRole("button", { name: "N nova" }).click();
    await expect(page.getByRole("heading", { name: "nova / main" })).toBeVisible();
    await page.getByLabel("Message", { exact: true }).fill("Restored character can chat");
    await page.getByRole("button", { name: "Send", exact: true }).click();
    await expect(page.getByRole("article", { name: "assistant message" })).toContainText("Restored character can chat");
    expect(errors).toEqual([]);
  } finally { await rm(root, { recursive: true, force: true }); }
});
