import { draftAction } from "./navigation.ts";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { expect, test } from "./fixtures.ts";

test("conversation requests expose their complete options through the actual browser", async ({ page }, info) => {
  const sent: Record<string, unknown>[] = [];
  const received: Record<string, unknown>[] = [];
  page.on("websocket", (socket) => {
    socket.on("framesent", (event) => { sent.push(JSON.parse(String(event.payload)) as Record<string, unknown>); });
    socket.on("framereceived", (event) => { received.push(JSON.parse(String(event.payload)) as Record<string, unknown>); });
  });
  const pixel = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jp1sAAAAASUVORK5CYII=", "base64");
  const hostPath = info.outputPath("host-image.png");
  await mkdir(dirname(hostPath), { recursive: true });
  await writeFile(hostPath, pixel);
  await page.goto("/workspace");
  await page.getByLabel("Daemon token").fill("browser-test-token");
  await page.getByRole("button", { name: "Open workspace" }).click();
  await page.getByRole("button", { name: "Create character", exact: true }).click();
  const create = page.getByRole("dialog", { name: "Create character", exact: true });
  await create.getByLabel("Character name", { exact: true }).fill("core");
  await create.getByRole("button", { name: "Run action", exact: true }).click();
  await expect(create.getByRole("heading", { name: "Action completed" })).toBeVisible();
  await create.getByRole("button", { name: "Close dialog", exact: true }).click();
  await page.getByRole("navigation", { name: "Characters" }).getByRole("button", { name: "C core", exact: true }).click();
  await draftAction(page, "Message options");
  const options = page.getByRole("dialog", { name: "Message options", exact: true });
  await expect(options.getByLabel("Stream response", { exact: true })).toBeChecked();
  await expect(options.getByText("Original image paths", { exact: true })).toBeVisible();
  await options.getByLabel("Stream response", { exact: true }).uncheck();
  await options.getByRole("button", { name: "Add original image paths", exact: true }).click();
  await options.getByLabel("Original image paths 1", { exact: true }).fill(hostPath);
  await options.getByLabel("Set Time away in seconds", { exact: true }).check();
  await options.getByLabel("Time away in seconds", { exact: true }).fill("120");
  await options.getByRole("button", { name: "Close dialog", exact: true }).click();
  await page.getByLabel("Attach images", { exact: true }).setInputFiles({ name: "upload.png", mimeType: "image/png", buffer: pixel });
  await page.getByLabel("Message", { exact: true }).fill("A request with complete options");
  await expect(page.getByText("Draft saved on this device", { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByLabel("Message", { exact: true })).toHaveValue("A request with complete options");
  await draftAction(page, "Message options");
  await expect(options.getByLabel("Stream response", { exact: true })).not.toBeChecked();
  await expect(options.getByLabel("Original image paths 1", { exact: true })).toHaveValue(hostPath);
  await expect(options.getByLabel("Time away in seconds", { exact: true })).toHaveValue("120");
  await options.getByRole("button", { name: "Close dialog", exact: true }).click();
  await expect(page.getByRole("button", { name: "Remove upload.png", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Send", exact: true }).click();
  await expect(page.getByRole("article", { name: "assistant message" })).toContainText("Answer 1:");
  expect(sent).toContainEqual(expect.objectContaining({ type: "message", stream: false, text: "A request with complete options", images: [hostPath], image_data: [{ filename: "upload.png", mime_type: "image/png", data: pixel.toString("base64") }], absence_seconds: 120 }));
  const messageRid = sent.find((frame) => frame["type"] === "message")?.["rid"];
  expect(received.filter((frame) => frame["rid"] === messageRid && ["stream_start", "stream_chunk"].includes(String(frame["type"])))).toEqual([]);
  await expect(page.getByRole("article", { name: "user message" }).locator("img")).toHaveCount(1);
  await expect(page.getByRole("article", { name: "user message" })).toContainText("[image omitted: host-image.png — the client could not upload it]");
  await expect(page.getByLabel("Message", { exact: true })).toHaveValue("");
  await page.getByRole("button", { name: /All actions/ }).click();
  const palette = page.getByRole("dialog", { name: "All actions", exact: true });
  await palette.getByRole("button", { name: "Regenerate response Conversation", exact: true }).click();
  const regen = page.getByRole("dialog", { name: "Regenerate response", exact: true });
  await regen.getByLabel("Stream response", { exact: true }).uncheck();
  await regen.getByLabel("Guidance", { exact: true }).fill("Use a different example");
  await regen.getByRole("button", { name: "Regenerate", exact: true }).click();
  await expect(page.getByRole("article", { name: "assistant message" })).toContainText("Answer 2:");
  expect(sent).toContainEqual(expect.objectContaining({ type: "regen", stream: false, guidance: "Use a different example" }));
  const regenRid = sent.find((frame) => frame["type"] === "regen")?.["rid"];
  expect(received.filter((frame) => frame["rid"] === regenRid && ["stream_start", "stream_chunk"].includes(String(frame["type"])))).toEqual([]);
  await page.getByRole("button", { name: /All actions/ }).click();
  await palette.getByRole("button", { name: "Send message Conversation", exact: true }).click();
  await expect(page.getByLabel("Message", { exact: true })).toBeFocused();
  await page.getByLabel("Message", { exact: true }).fill("hold this request");
  await page.getByRole("button", { name: "Send", exact: true }).click();
  await expect(page.getByRole("article", { name: "user message" }).last()).toContainText("hold this request");
  await page.getByRole("button", { name: /All actions/ }).click();
  await palette.getByRole("button", { name: "Stop work Conversation", exact: true }).click();
  await expect(page.getByText("Previous send needs review", { exact: true })).toBeVisible();
  expect(sent).toContainEqual({ type: "cancel" });
  await expect(page.getByRole("button", { name: "Sending…", exact: true })).toHaveCount(0);
});

test("the picker rejects oversized and excess images without changing the retained draft", async ({ page }) => {
  await page.goto("/workspace");
  await page.getByLabel("Daemon token").fill("browser-test-token");
  await page.getByRole("button", { name: "Open workspace" }).click();
  await page.getByLabel("Message", { exact: true }).fill("Keep this draft");
  const picker = page.getByLabel("Attach images", { exact: true });
  await picker.setInputFiles({ name: "large.png", mimeType: "image/png", buffer: Buffer.alloc(5 * 1024 * 1024 + 1) });
  await expect(page.getByRole("alert").filter({ hasText: "Choose images no larger than 5 MiB" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Remove large.png", exact: true })).toHaveCount(0);
  const files = Array.from({ length: 17 }, (_, index) => ({ name: `image-${String(index)}.png`, mimeType: "image/png", buffer: Buffer.from("tiny fixture") }));
  await picker.setInputFiles(files);
  await expect(page.getByRole("alert").filter({ hasText: "Attach at most 16 images" })).toBeVisible();
  await expect(page.getByRole("button", { name: /^Remove image-/ })).toHaveCount(0);
  await picker.setInputFiles(files.slice(0, 16));
  await expect(page.getByRole("button", { name: /^Remove image-/ })).toHaveCount(16);
  await picker.setInputFiles({ name: "one-more.png", mimeType: "image/png", buffer: Buffer.from("tiny fixture") });
  await expect(page.getByRole("alert").filter({ hasText: "Attach at most 16 images" })).toBeVisible();
  await expect(page.getByRole("button", { name: /^Remove image-/ })).toHaveCount(16);
  await expect(page.getByLabel("Message", { exact: true })).toHaveValue("Keep this draft");
});
