import { readFile } from "node:fs/promises";
import { expect, test } from "./fixtures.ts";

test("diagnostic journeys inspect full captures, diffs, transcripts and stored messages, download data and operate runtime controls", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  page.on("dialog", (dialog) => { errors.push(`Unexpected script dialog: ${dialog.message()}`); void dialog.dismiss(); });
  await page.goto("/");
  await page.getByLabel("Daemon token").fill("browser-test-token");
  await page.getByRole("button", { name: "Open workspace" }).click();
  await expect(page.getByRole("button", { name: "Diagnostics", exact: true })).toBeDisabled();
  await page.getByRole("button", { name: "Create character", exact: true }).click();
  const create = page.getByRole("dialog", { name: "Create character", exact: true });
  await create.getByLabel("Character name", { exact: true }).fill("nova");
  await create.getByRole("button", { name: "Run action" }).click();
  await expect(create.getByRole("heading", { name: "Action completed" })).toBeVisible();
  await create.getByRole("button", { name: "Close dialog" }).click();
  await page.getByRole("navigation", { name: "Characters" }).getByRole("button", { name: "N nova" }).click();
  await expect(page.getByRole("heading", { name: "nova / main" })).toBeVisible();
  await page.getByRole("button", { name: "Diagnostics", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Diagnostics", exact: true });
  const view = dialog.getByRole("combobox", { name: "Diagnostic view", exact: true });
  await expect(dialog.getByRole("region", { name: "Runtime status" })).toContainText("anthropic:claude-opus-4-8");
  await dialog.getByRole("combobox", { name: "Status section", exact: true }).selectOption("tokens");
  await expect(dialog.locator(".diagnostic-data").first()).toContainText("cache read");
  await view.selectOption("calls");
  await dialog.getByLabel("Recent entries", { exact: true }).fill("0");
  await dialog.getByRole("button", { name: "Refresh diagnostics" }).click();
  await expect(dialog.getByRole("button", { name: /^Inspect call / })).toHaveCount(2);
  await dialog.getByLabel("Call type", { exact: true }).fill("missing-type");
  await dialog.getByRole("button", { name: "Refresh diagnostics" }).click();
  await expect(dialog.getByText("No calls match these filters.")).toBeVisible();
  await dialog.getByLabel("Recent entries", { exact: true }).fill("20");
  await dialog.getByLabel("Call type", { exact: true }).fill("diagnostic_fixture");
  await dialog.getByRole("button", { name: "Refresh diagnostics" }).click();
  await dialog.getByRole("button", { name: "Inspect call 2", exact: true }).click();
  const call = dialog.getByRole("article", { name: "Call 2 details", exact: true });
  await expect(call).toContainText("<img src=x onerror=alert('unsafe')>");
  await expect(call.locator("img")).toHaveCount(0);
  await dialog.getByLabel("Full wire headers and bodies", { exact: true }).check();
  await dialog.getByLabel("Compare requests", { exact: true }).check();
  await dialog.getByRole("button", { name: "Load call details" }).click();
  await expect(dialog.getByRole("region", { name: "Request differences" })).toContainText("1 → 2");
  await call.getByText("Complete call details", { exact: true }).click();
  const downloadReady = page.waitForEvent("download");
  await call.getByRole("button", { name: "Download JSON", exact: true }).click();
  const download = await downloadReady;
  const path = await download.path();
  if (path === null) throw new Error("Missing diagnostic download");
  const text = await readFile(path, "utf8");
  expect(JSON.parse(text)).toMatchObject({ call: { id: 2, request: { future_field: { inspectable: true } } }, wire: [{ request_headers: [["Authorization", "[redacted]"], ["x-request-id", "diagnostic-call-1"]], response_body: { text: "Wire response" } }], diff: { from_call: 1, to_call: 2 } });
  expect(text).not.toContain("private-fixture-key");
  expect(text).not.toContain("private-session-cookie");
  await dialog.getByLabel("Compare against call ID", { exact: true }).fill("9999");
  await dialog.getByRole("button", { name: "Load call details" }).click();
  await expect(dialog.getByRole("alert")).toContainText("cannot be compared");
  await expect(call).toBeVisible();
  await dialog.getByLabel("Compare against call ID", { exact: true }).fill("1");
  await dialog.getByRole("button", { name: "Load call details" }).click();
  await expect(dialog.getByRole("alert")).toHaveCount(0);
  await view.selectOption("heartbeat");
  await expect(dialog.getByRole("region", { name: "Stored transcript" })).toContainText("Heartbeat fixture transcript");
  await view.selectOption("subagents");
  await expect(dialog.getByRole("region", { name: "Stored subagent traces" })).toContainText("Stored messages have expired");
  await dialog.getByRole("button", { name: "Add parent tool ids", exact: true }).click();
  await dialog.getByLabel("Parent tool IDs 1", { exact: true }).fill("parent-fixture");
  await dialog.getByRole("button", { name: "Refresh diagnostics" }).click();
  await expect(dialog.getByRole("region", { name: "Stored subagent traces" })).not.toContainText("expired-worker");
  await dialog.getByText("Messages (1)", { exact: true }).click();
  await expect(dialog.getByText("Stored worker message", { exact: true })).toBeVisible();
  await view.selectOption("errors");
  await expect(dialog.getByRole("region", { name: "Diagnostic errors" })).toContainText("key fallbacks");
  await view.selectOption("controls");
  const controls = dialog.getByRole("region", { name: "Runtime controls", exact: true });
  await controls.getByRole("button", { name: /Activate session and cache/ }).click();
  await expect(controls.getByRole("status")).toContainText("Runtime action completed");
  await controls.getByRole("button", { name: /Make heartbeat dormant/ }).click();
  await expect(controls).toContainText("Heartbeat: Dormant");
  await controls.getByRole("button", { name: /Activate heartbeat/ }).click();
  await expect(controls).toContainText("Heartbeat: Active");
  await controls.getByRole("button", { name: /Send cache keepalive ping/ }).click();
  await expect(controls.getByRole("status")).toContainText('"status": "warm"');
  await controls.getByRole("button", { name: /Schedule heartbeat/ }).click();
  await expect(controls.getByRole("status")).toContainText("scheduled");
  await view.selectOption("events");
  await expect(dialog.getByRole("region", { name: "Heartbeat events" })).toContainText("Fixture heartbeat wake");
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: "../out/issue-214/diagnostics-mobile.png", fullPage: true });
  expect(await page.evaluate<boolean>("document.documentElement.scrollWidth <= innerWidth")).toBe(true);
  expect(errors).toEqual([]);
});
