import { expect, test } from "./fixtures.ts";
import { readFile } from "node:fs/promises";
test.use({ galleryMedia: true });

const bytes = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAIAAAD91JpzAAAAFklEQVR4nGMUqdjCwMDAxMDAwMDAAAAOigFED/mW/QAAAABJRU5ErkJggg==", "base64");

test("conversation images have captions, keyboard navigation, downloads and reload recovery", async ({ page }) => {
  await page.goto("/workspace");
  await page.getByLabel("Daemon token").fill("browser-test-token");
  await page.getByRole("button", { name: "Open workspace" }).click();
  await page.getByRole("button", { name: "Create character", exact: true }).click();
  const create = page.getByRole("dialog", { name: "Create character", exact: true });
  await create.getByLabel("Character name", { exact: true }).fill("nova");
  await create.getByRole("button", { name: "Run action" }).click();
  await expect(create.getByRole("heading", { name: "Action completed" })).toBeVisible();
  await create.getByRole("button", { name: "Close dialog" }).click();
  await page.getByRole("navigation", { name: "Characters" }).getByRole("button", { name: "N nova" }).click();
  await expect(page.getByRole("heading", { name: "nova / main" })).toBeVisible();
  await page.getByLabel("Attach images", { exact: true }).setInputFiles([
    { name: "alpha.png", mimeType: "image/png", buffer: bytes },
    { name: "beta.png", mimeType: "image/png", buffer: bytes },
  ]);
  await expect(page.getByRole("button", { name: "Remove beta.png", exact: true })).toBeVisible();
  await page.getByLabel("Message", { exact: true }).fill("Compare these pictures");
  await page.getByRole("button", { name: "Send", exact: true }).click();
  await expect(page.getByRole("article", { name: "assistant message" })).toContainText("Compare these pictures");
  const user = page.getByRole("article", { name: "user message" });
  await user.getByRole("button", { name: /View image:.*alpha.png/ }).click();
  const gallery = page.getByRole("dialog", { name: "Image", exact: true });
  await expect(gallery.getByRole("button", { name: "Next image", exact: true })).toBeVisible();
  await expect(gallery.getByLabel("Image caption", { exact: true })).toContainText("alpha.png");
  await expect(gallery.getByRole("status")).toContainText("1 of 2");
  await page.keyboard.press("ArrowRight");
  await expect(gallery.getByLabel("Image caption", { exact: true })).toContainText("beta.png");
  await expect(gallery.getByRole("status")).toContainText("2 of 2");
  await expect(gallery.getByRole("button", { name: "Next image", exact: true })).toBeDisabled();
  const downloadReady = page.waitForEvent("download");
  await gallery.getByRole("link", { name: "Download image", exact: true }).click();
  const download = await downloadReady;
  expect(download.suggestedFilename()).toContain("beta.png");
  const downloaded = await download.path();
  expect(downloaded).not.toBeNull();
  expect(await readFile(downloaded ?? "")).toEqual(bytes);
  await page.keyboard.press("Home");
  await expect(gallery.getByLabel("Image caption", { exact: true })).toContainText("alpha.png");
  await gallery.getByRole("button", { name: "Next image", exact: true }).click();
  await page.keyboard.press("ArrowLeft");
  await expect(gallery.getByLabel("Image caption", { exact: true })).toContainText("alpha.png");
  await page.keyboard.press("Escape");
  await page.reload();
  await expect(user.getByRole("button", { name: /View image:.*beta.png/ })).toBeVisible();
  await page.getByRole("button", { name: "Images", exact: true }).click();
  await expect(gallery.getByRole("status")).toContainText("1 of 2");
  await page.keyboard.press("End");
  await expect(gallery.getByLabel("Image caption", { exact: true })).toContainText("beta.png");
  await gallery.getByRole("button", { name: "Load earlier history", exact: true }).click();
  await expect(gallery.getByRole("button", { name: "Load earlier history", exact: true })).toHaveCount(0);
  await expect(gallery.getByLabel("Image caption", { exact: true })).toContainText("beta.png");
  await page.setViewportSize({ width: 390, height: 844 });
  await gallery.screenshot({ path: "../out/issue-214/gallery-mobile.png" });
  await expect.poll(() => page.evaluate<boolean>("document.documentElement.scrollWidth <= innerWidth")).toBe(true);
});

test("real tool image events appear once in the gallery and stay in their conversation", async ({ page }) => {
  const mediaEvents: unknown[] = [];
  page.on("websocket", (socket) => socket.on("framereceived", (event) => {
    const frame: unknown = JSON.parse(event.payload.toString());
    if (typeof frame === "object" && frame !== null && "type" in frame && frame.type === "send_image") mediaEvents.push(frame);
  }));
  await page.goto("/workspace");
  await page.getByLabel("Daemon token").fill("browser-test-token");
  await page.getByRole("button", { name: "Open workspace" }).click();
  await page.getByRole("button", { name: "Create character", exact: true }).click();
  const create = page.getByRole("dialog", { name: "Create character", exact: true });
  await create.getByLabel("Character name", { exact: true }).fill("nova");
  await create.getByRole("button", { name: "Run action" }).click();
  await expect(create.getByRole("heading", { name: "Action completed" })).toBeVisible();
  await create.getByRole("button", { name: "Close dialog" }).click();
  await page.getByRole("navigation", { name: "Characters" }).getByRole("button", { name: "N nova" }).click();
  await expect(page.getByRole("heading", { name: "nova / main" })).toBeVisible();
  await page.getByRole("button", { name: "Tool workbench", exact: true }).click();
  const workbench = page.getByRole("dialog", { name: "Tool workbench", exact: true });
  const selected = workbench.getByRole("region", { name: "Selected tool" });
  const run = async () => {
    await selected.getByRole("button", { name: "Review tool run", exact: true }).click();
    await workbench.getByRole("region", { name: "Review tool run" }).getByRole("button", { name: "Run tool now", exact: true }).click();
    await expect(workbench.getByRole("region", { name: "Tool result" })).toContainText("Tool completed");
    await expect(workbench.getByRole("region", { name: "Review tool run" })).toHaveCount(0);
  };
  await workbench.getByRole("navigation", { name: "Available tools" }).getByRole("button", { name: "bash", exact: true }).click();
  await selected.getByLabel("command", { exact: true }).fill(`printf %s '${bytes.toString("base64")}' | base64 -d > tool-image.png`);
  await run();
  await workbench.getByRole("button", { name: "Close dialog" }).click();
  await page.getByLabel("Message", { exact: true }).fill("show gallery image fixture");
  await page.getByRole("button", { name: "Send", exact: true }).click();
  await expect(page.getByRole("article", { name: "Streaming response", exact: true })).toContainText("Tool image ready");
  expect(mediaEvents).toHaveLength(1);
  await page.getByRole("button", { name: "Images", exact: true }).click();
  const gallery = page.getByRole("dialog", { name: "Image", exact: true });
  await expect(gallery.getByRole("status")).toContainText("1 of 1");
  await expect(gallery.getByLabel("Image caption", { exact: true })).toContainText("tool-image.png");
  await gallery.getByRole("button", { name: "Close dialog" }).click();
  const readResult = page.getByRole("article", { name: "assistant message", exact: true }).filter({ hasText: "Tool · read" });
  await readResult.getByText("Tool result", { exact: true }).click();
  await readResult.getByRole("button", { name: "View image: Inline image", exact: true }).click();
  await expect(gallery.getByLabel("Image caption", { exact: true })).toContainText("tool-image.png");
  await gallery.getByRole("button", { name: "Close dialog" }).click();
  await page.getByRole("button", { name: "Stop", exact: true }).click();
  await page.getByRole("button", { name: "I checked the conversation", exact: true }).click();
  const toolMessage = page.getByRole("article", { name: "assistant message", exact: true }).filter({ hasText: "Tool · read" });
  await toolMessage.getByRole("button", { name: "Delete", exact: true }).click();
  const deletion = page.getByRole("dialog");
  await deletion.getByRole("button", { name: "Run action", exact: true }).click();
  await deletion.getByRole("button", { name: "Confirm delete", exact: true }).click();
  await expect(deletion.getByRole("heading", { name: "Action completed" })).toBeVisible();
  await deletion.getByRole("button", { name: "Close dialog" }).click();
  await expect(toolMessage).toHaveCount(0);
  await page.getByRole("button", { name: "Images", exact: true }).click();
  await expect(gallery.getByRole("status")).toContainText("No images loaded");
  await gallery.getByRole("button", { name: "Close dialog" }).click();
  await page.getByLabel("Message", { exact: true }).fill("show gallery image fixture");
  await page.getByRole("button", { name: "Send", exact: true }).click();
  await expect(page.getByRole("article", { name: "Streaming response", exact: true })).toContainText("Tool image ready");
  expect(mediaEvents).toHaveLength(2);
  await page.getByRole("button", { name: "Stop", exact: true }).click();
  await page.getByRole("button", { name: "I checked the conversation", exact: true }).click();
  await page.locator(".sidebar").getByRole("button", { name: "New", exact: true }).first().click();
  await create.getByLabel("Character name", { exact: true }).fill("other");
  await create.getByRole("button", { name: "Run action" }).click();
  await expect(create.getByRole("heading", { name: "Action completed" })).toBeVisible();
  await create.getByRole("button", { name: "Close dialog" }).click();
  await page.getByRole("navigation", { name: "Characters" }).getByRole("button", { name: "O other" }).click();
  await expect(page.getByRole("heading", { name: "other / main" })).toBeVisible();
  await page.getByRole("button", { name: "Images", exact: true }).click();
  await expect(gallery.getByRole("status")).toContainText("No images loaded");
  await gallery.getByRole("button", { name: "Close dialog" }).click();
  await page.getByRole("button", { name: "Sign out", exact: true }).click();
  await page.getByLabel("Daemon token").fill("browser-test-token");
  await page.getByRole("button", { name: "Open workspace" }).click();
  await expect(page.getByRole("navigation", { name: "Characters" }).getByRole("button", { name: "O other" })).toBeVisible();
  await page.getByRole("button", { name: "Images", exact: true }).click();
  await expect(gallery.getByRole("status")).toContainText("No images loaded");
});
