import { openWorkspacePanel } from "./navigation.ts";
import type { Page } from "@playwright/test";
import { expect, test } from "./fixtures.ts";

async function openCharacter(page: Page): Promise<void> {
  await page.goto("/workspace");
  await page.getByLabel("Daemon token").fill("browser-test-token");
  await page.getByRole("button", { name: "Open workspace" }).click();
  await page.getByRole("button", { name: "Create character", exact: true }).click();
  const dialog = page.getByRole("dialog");
  await dialog.getByLabel("Character name", { exact: true }).fill("nova");
  await dialog.getByRole("button", { name: "Run action" }).click();
  await expect(dialog.getByRole("heading", { name: "Action completed" })).toBeVisible();
  await dialog.getByRole("button", { name: "Close dialog" }).click();
  await page.getByRole("navigation", { name: "Characters" }).getByRole("button", { name: "N nova" }).click();
  await expect(page.getByRole("heading", { name: "nova / main" })).toBeVisible();
}

test("last action output can be reopened after its form closes and clears on sign-out", async ({ page }) => {
  await openCharacter(page);
  await page.getByRole("button", { name: "All actions", exact: true }).click();
  const palette = page.getByRole("dialog", { name: "All actions", exact: true });
  await palette.getByLabel("Find an action", { exact: true }).fill("character_info");
  await palette.getByRole("button", { name: "Inspect character Characters", exact: true }).click();
  const action = page.getByRole("dialog");
  await action.getByRole("button", { name: "Run action", exact: true }).click();
  await expect(action.getByRole("heading", { name: "Action completed", exact: true })).toBeVisible();
  await action.getByRole("button", { name: "Close dialog", exact: true }).click();
  await openWorkspacePanel(page, "Last action output");
  const output = page.getByRole("dialog", { name: "Last action output", exact: true });
  await expect(output).toContainText("character_info");
  await expect(output.getByRole("region", { name: "Complete action result", exact: true })).toContainText("nova");
  await output.getByRole("button", { name: "Close dialog", exact: true }).click();
  await openWorkspacePanel(page, "Tool workbench");
  const tools = page.getByRole("dialog", { name: "Tool workbench", exact: true });
  await expect(tools.getByRole("navigation", { name: "Available tools" }).getByRole("button", { name: "bash", exact: true })).toBeVisible();
  await tools.getByRole("button", { name: "Close dialog", exact: true }).click();
  await openWorkspacePanel(page, "Last action output");
  await expect(output.getByRole("heading", { level: 3 })).toHaveText("character_info");
  await output.getByRole("button", { name: "Close dialog", exact: true }).click();
  await openWorkspacePanel(page, "Disconnect");
  await page.getByLabel("Daemon token").fill("browser-test-token");
  await page.getByRole("button", { name: "Open workspace", exact: true }).click();
  await openWorkspacePanel(page, "Last action output");
  await expect(output).toContainText("No completed action yet");
});

test("workspace help exposes input-line focus, transcript focus and configurable line scrolling", async ({ page }) => {
  await openCharacter(page);
  const input = page.getByLabel("Message", { exact: true });
  await input.fill("first\nsecond line\nlast");
  await input.press("Home");
  await input.press("ArrowUp");
  await input.press("ArrowRight");
  await expect(page.getByRole("button", { name: "Workspace settings", exact: true })).toBeVisible();
  await openWorkspacePanel(page, "Workspace help");
  const help = page.getByRole("dialog", { name: "Workspace help", exact: true });
  await help.getByRole("button", { name: "Start of input line", exact: true }).click();
  await expect(input).toBeFocused();
  await expect.poll(() => page.evaluate<number>('document.getElementById("message-composer").selectionStart')).toBe(6);
  await openWorkspacePanel(page, "Workspace help");
  await help.getByRole("button", { name: "End of input line", exact: true }).click();
  await expect.poll(() => page.evaluate<number>('document.getElementById("message-composer").selectionStart')).toBe(17);
  await expect(input).toHaveValue("first\nsecond line\nlast");
  await input.fill("Long transcript\n".repeat(60));
  await page.getByRole("button", { name: "Send", exact: true }).click();
  await expect(input).toHaveValue("");
  await openWorkspacePanel(page, "Workspace help");
  await help.getByRole("button", { name: "Focus transcript", exact: true }).click();
  const transcript = page.getByRole("region", { name: "Conversation transcript", exact: true });
  await expect(transcript).toBeFocused();
  await page.keyboard.press("Home");
  await expect.poll(() => page.evaluate<number>('document.querySelector(".messages").scrollTop')).toBe(0);
  await openWorkspacePanel(page, "Workspace help");
  await help.getByLabel("Lines per scroll", { exact: true }).fill("3");
  await help.getByRole("button", { name: "Scroll down", exact: true }).click();
  const expected = await page.evaluate<number>('3 * (parseFloat(getComputedStyle(document.querySelector(".messages")).lineHeight) || 24)');
  await expect.poll(() => page.evaluate<number>('document.querySelector(".messages").scrollTop')).toBeCloseTo(expected, -1);
  await expect(page.getByRole("checkbox", { name: "Follow", exact: true, includeHidden: true })).not.toBeChecked();
  await openWorkspacePanel(page, "Keyboard shortcuts");
  const keyboard = page.getByRole("dialog", { name: "Keyboard shortcuts", exact: true });
  await keyboard.getByLabel("Shortcut key", { exact: true }).fill("alt+j");
  await keyboard.getByLabel("Shortcut scope", { exact: true }).selectOption("global");
  await keyboard.getByLabel("Shortcut action", { exact: true }).selectOption("local:down");
  await keyboard.getByLabel("Lines per scroll", { exact: true }).fill("2");
  await keyboard.getByRole("button", { name: "Save shortcut", exact: true }).click();
  await expect(keyboard.getByRole("status")).toHaveText("Shortcut applied");
  await keyboard.getByRole("button", { name: "Close dialog", exact: true }).click();
  await page.keyboard.press("Alt+j");
  await expect.poll(() => page.evaluate<number>('document.querySelector(".messages").scrollTop')).toBeCloseTo(expected * 5 / 3, -1);
  await page.reload();
  await openWorkspacePanel(page, "Keyboard shortcuts");
  await keyboard.getByRole("button", { name: "Edit global:alt+j", exact: true }).click();
  await expect(keyboard.getByLabel("Lines per scroll", { exact: true })).toHaveValue("2");
  await keyboard.getByRole("button", { name: "Close dialog", exact: true }).click();
  await openWorkspacePanel(page, "Workspace help");
  await page.setViewportSize({ width: 390, height: 844 });
  await help.screenshot({ path: "../out/issue-214/help-mobile.png" });
  expect(await page.evaluate<boolean>("document.documentElement.scrollWidth <= innerWidth")).toBe(true);
});


test("conversation shortcuts, edit cancellation and attachment clearing use the current workspace", async ({ page }) => {
  await openCharacter(page);
  await openWorkspacePanel(page, "Keyboard shortcuts");
  const keyboard = page.getByRole("dialog", { name: "Keyboard shortcuts", exact: true });
  for (const [key, target] of [["alt+x", "local:edit_cancel"], ["alt+i", "local:clear_images"]]) {
    await keyboard.getByLabel("Shortcut key", { exact: true }).fill(key ?? "");
    await keyboard.getByLabel("Shortcut scope", { exact: true }).selectOption("global");
    await keyboard.getByLabel("Shortcut action", { exact: true }).selectOption(target ?? "");
    await keyboard.getByRole("button", { name: "Save shortcut", exact: true }).click();
    await expect(keyboard.getByRole("status")).toHaveText("Shortcut applied");
  }
  await keyboard.getByRole("button", { name: "Close dialog", exact: true }).click();
  const input = page.getByLabel("Message", { exact: true });
  await input.fill("Keep the saved message");
  await page.getByRole("button", { name: "Send", exact: true }).click();
  await expect(input).toHaveValue("");
  await input.fill("Keep the unsent draft");
  await openWorkspacePanel(page, "Workspace help");
  await page.getByRole("dialog", { name: "Workspace help", exact: true }).getByRole("button", { name: "Conversation shortcuts", exact: true }).click();
  const quick = page.getByRole("dialog", { name: "Conversation shortcuts", exact: true });
  await expect(quick.locator(".action-list > button")).toHaveCount(8);
  await expect(quick.getByRole("button", { name: "Create character Characters", exact: true })).toHaveCount(0);
  await quick.getByRole("button", { name: "Close dialog", exact: true }).click();
  await page.getByRole("article", { name: "user message", exact: true }).getByRole("button", { name: "Edit", exact: true }).click();
  const edit = page.getByRole("dialog", { name: "Edit message", exact: true });
  await edit.getByLabel("Message text", { exact: true }).fill("Discard this edit");
  await page.keyboard.press("Alt+x");
  await expect(edit).toHaveCount(0);
  await expect(input).toHaveValue("Keep the unsent draft");
  await expect(page.getByRole("article", { name: "user message", exact: true })).toContainText("Keep the saved message");
  await page.getByLabel("Attach images", { exact: true }).setInputFiles({ name: "clear.png", mimeType: "image/png", buffer: Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a8GQAAAAASUVORK5CYII=", "base64") });
  await expect(page.getByRole("button", { name: "Remove clear.png", exact: true })).toBeVisible();
  await page.keyboard.press("Alt+i");
  await expect(page.getByRole("button", { name: "Remove clear.png", exact: true })).toHaveCount(0);
  await expect(input).toHaveValue("Keep the unsent draft");
});
