import { expect, test } from "./fixtures.ts";
import { readFile } from "node:fs/promises";

test("memory workflows preview and archive context, preserve segment metadata and recover failed work", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/");
  await page.getByLabel("Daemon token").fill("browser-test-token");
  await page.getByRole("button", { name: "Open workspace" }).click();
  await expect(page.getByRole("button", { name: "Memory & segments", exact: true })).toBeDisabled();
  await page.getByRole("button", { name: "Create character", exact: true }).click();
  const create = page.getByRole("dialog", { name: "Create character", exact: true });
  await create.getByLabel("Character name", { exact: true }).fill("nova");
  await create.getByRole("button", { name: "Run action" }).click();
  await expect(create.getByRole("heading", { name: "Action completed" })).toBeVisible();
  await create.getByRole("button", { name: "Close dialog" }).click();
  await page.getByRole("navigation", { name: "Characters" }).getByRole("button", { name: "N nova" }).click();
  await expect(page.getByRole("heading", { name: "nova / main" })).toBeVisible();
  await page.getByRole("button", { name: "Memory & segments", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Memory & segments", exact: true });
  await expect(dialog.getByText("No archived segments yet.")).toBeVisible();
  await dialog.getByRole("button", { name: "Close dialog" }).click();
  for (const text of ["Remember a durable fixture fact", "Keep this recent conversation"]) {
    await page.getByLabel("Message", { exact: true }).fill(text);
    await page.getByRole("button", { name: "Send", exact: true }).click();
    await expect(page.getByRole("article", { name: "assistant message" }).last()).toContainText(text);
  }
  await page.getByRole("button", { name: "Memory & segments", exact: true }).click();
  await dialog.getByLabel("Retain recent turns", { exact: true }).fill("1");
  await dialog.getByRole("button", { name: "Preview compaction", exact: true }).click();
  await expect(dialog.getByRole("region", { name: "Compaction result" })).toContainText("Memory write preview");
  await expect(dialog.getByRole("region", { name: "Review context archive" })).toHaveCount(0);
  await expect(dialog.getByText("No archived segments yet.")).toBeVisible();
  await dialog.getByRole("button", { name: "Compact context", exact: true }).click();
  const review = dialog.getByRole("region", { name: "Review context archive" });
  await expect(review).toContainText('"keep_turns": 1');
  await review.getByRole("button", { name: "Go back" }).click();
  await expect(dialog.getByText("No archived segments yet.")).toBeVisible();
  await dialog.getByRole("button", { name: "Compact context", exact: true }).click();
  await review.getByRole("button", { name: "Confirm archive" }).click();
  const report = dialog.getByRole("region", { name: "Compaction result" });
  await expect(report).toContainText("Context compacted");
  await expect(report).toContainText("1 recent turns retained (2 messages)");
  await expect(report).toContainText("fixture.md");
  await dialog.getByRole("button", { name: "Inspect segment 0", exact: true }).click();
  const selected = dialog.getByRole("region", { name: "Selected segment" });
  await selected.getByText("Archived messages (2)", { exact: true }).click();
  await expect(selected).toContainText("Remember a durable fixture fact");
  await selected.getByLabel("Segment label", { exact: true }).fill("Durable fact");
  await selected.getByRole("button", { name: "Save label", exact: true }).click();
  await expect(dialog.getByRole("region", { name: "Archived segments" })).toContainText("Durable fact");
  await selected.getByRole("textbox", { name: "Segment note", exact: true }).fill("A note to keep");
  await selected.getByRole("button", { name: "Save note", exact: true }).click();
  await selected.getByRole("button", { name: "Exclude from history search", exact: true }).click();
  await expect(selected).toContainText("Excluded from history search");
  await selected.getByRole("button", { name: "Include in history search", exact: true }).click();
  await selected.getByRole("button", { name: "Clear label", exact: true }).click();
  await expect(selected.getByLabel("Segment label", { exact: true })).toHaveValue("");
  await selected.getByRole("button", { name: "Clear note", exact: true }).click();
  await expect(selected.getByRole("textbox", { name: "Segment note", exact: true })).toHaveValue("");
  await selected.getByRole("textbox", { name: "Segment note", exact: true }).fill("Unsaved note survives lookup errors");
  await dialog.getByLabel("Segment index", { exact: true }).fill("9999");
  await dialog.getByRole("button", { name: "Inspect segment", exact: true }).click();
  await expect(dialog.getByRole("alert")).toContainText("9999");
  await expect(selected.getByRole("textbox", { name: "Segment note", exact: true })).toHaveValue("Unsaved note survives lookup errors");
  await selected.getByRole("button", { name: "Save note", exact: true }).click();
  await selected.getByText("Complete segment and messages", { exact: true }).click();
  const downloaded = page.waitForEvent("download");
  await selected.getByRole("button", { name: "Download JSON", exact: true }).click();
  const download = await downloaded;
  const downloadedPath = await download.path();
  if (downloadedPath === null) throw new Error("Missing downloaded segment");
  expect(JSON.parse(await readFile(downloadedPath, "utf8"))).toMatchObject({ segment: { note: "Unsaved note survives lookup errors", label: null, excluded: false }, messages: [{ content: "Remember a durable fixture fact" }, {}] });
  for (const [text, outcome] of [["pause memory once", "Compaction paused"], ["truncate memory once", "Compaction reached the token limit"]] as const) {
    await dialog.getByRole("button", { name: "Close dialog" }).click();
    await page.getByLabel("Message", { exact: true }).fill(text);
    await page.getByRole("button", { name: "Send", exact: true }).click();
    await expect(page.getByRole("article", { name: "assistant message" }).last()).toContainText(text);
    await page.getByRole("button", { name: "Memory & segments", exact: true }).click();
    await dialog.getByLabel("Retain recent turns", { exact: true }).fill("0");
    await dialog.getByRole("button", { name: "Compact context", exact: true }).click();
    await review.getByRole("button", { name: "Confirm archive" }).click();
    await expect(report).toContainText(outcome);
    await expect(page.getByRole("article", { name: "user message" }).last()).toContainText(text);
    if (text === "truncate memory once") await dialog.getByLabel("Restart paused work").check();
    await dialog.getByRole("button", { name: text === "pause memory once" ? "Resume compaction" : "Compact context", exact: true }).click();
    await review.getByRole("button", { name: "Confirm archive" }).click();
    await expect(report).toContainText("Context compacted");
  }
  await dialog.getByRole("button", { name: "Close dialog" }).click();
  await page.getByLabel("Message", { exact: true }).fill("Archive this conversation without summarizing");
  await page.getByRole("button", { name: "Send", exact: true }).click();
  await expect(page.getByRole("article", { name: "assistant message" }).last()).toContainText("Archive this conversation without summarizing");
  await page.getByRole("button", { name: "Memory & segments", exact: true }).click();
  await dialog.getByLabel("Archive note", { exact: true }).fill("Manual archive");
  await dialog.getByLabel("Exclude new segment from history search").check();
  await dialog.getByRole("button", { name: "Clear active context", exact: true }).click();
  await review.getByRole("button", { name: "Go back" }).click();
  await expect(page.getByRole("article", { name: "user message" })).toHaveCount(1);
  await dialog.getByRole("button", { name: "Clear active context", exact: true }).click();
  await review.getByRole("button", { name: "Confirm archive" }).click();
  await expect(dialog.getByRole("heading", { name: "Memory action completed" })).toBeVisible();
  await expect(page.getByRole("article", { name: "user message" })).toHaveCount(0);
  await dialog.getByRole("button", { name: "Inspect segment 3", exact: true }).click();
  await expect(selected.getByRole("textbox", { name: "Segment note", exact: true })).toHaveValue("Manual archive");
  await expect(selected).toContainText("Excluded from history search");
  await dialog.getByRole("button", { name: "Close dialog" }).click();
  await page.reload();
  await page.getByRole("button", { name: "Memory & segments", exact: true }).click();
  await dialog.getByRole("button", { name: "Inspect segment 0", exact: true }).click();
  await expect(selected.getByRole("textbox", { name: "Segment note", exact: true })).toHaveValue("Unsaved note survives lookup errors");
  await page.setViewportSize({ width: 390, height: 844 });
  await dialog.screenshot({ path: "../out/issue-214/memory-mobile.png" });
  await expect.poll(() => page.evaluate<boolean>("document.documentElement.scrollWidth <= innerWidth")).toBe(true);
  expect(errors).toEqual([]);
});

test("archive-only previews obey shared confirmation rules", async ({ page }) => {
  await page.goto("/");
  await page.getByLabel("Daemon token").fill("browser-test-token");
  await page.getByRole("button", { name: "Open workspace" }).click();
  await page.getByRole("button", { name: "Create character", exact: true }).click();
  const create = page.getByRole("dialog", { name: "Create character", exact: true });
  await create.getByLabel("Character name", { exact: true }).fill("recovery");
  await create.getByRole("button", { name: "Run action" }).click();
  await expect(create.getByRole("heading", { name: "Action completed" })).toBeVisible();
  await create.getByRole("button", { name: "Close dialog" }).click();
  await page.getByRole("navigation", { name: "Characters" }).getByRole("button", { name: "R recovery" }).click();
  await page.getByRole("button", { name: "Memory & segments", exact: true }).click();
  const memory = page.getByRole("dialog", { name: "Memory & segments", exact: true });
  await memory.getByRole("button", { name: "Inspect segment 0", exact: true }).click();
  const selected = memory.getByRole("region", { name: "Selected segment" });
  await selected.getByText("Archived messages (1)", { exact: true }).click();
  await expect(selected).toContainText("Archived message from an earlier session");
  await memory.getByRole("button", { name: "Close dialog" }).click();
  await page.getByRole("button", { name: "Settings", exact: true }).click();
  const settings = page.getByRole("dialog", { name: "Settings", exact: true });
  await settings.getByLabel("Find a setting").fill("compaction.write_memory");
  await settings.getByRole("button").filter({ has: page.locator("span", { hasText: /^compaction\.write_memory$/ }) }).click();
  const setting = settings.getByRole("region", { name: "Setting compaction.write_memory", exact: true });
  await setting.getByLabel("Value", { exact: true }).uncheck();
  await setting.getByRole("button", { name: "Save setting" }).click();
  await expect(setting.getByRole("status")).toContainText("Setting saved");
  await settings.getByRole("button", { name: "Close dialog" }).click();
  await page.getByLabel("Message", { exact: true }).fill("Keep this in the archive");
  await page.getByRole("button", { name: "Send", exact: true }).click();
  await expect(page.getByRole("article", { name: "assistant message" }).last()).toContainText("Keep this in the archive");
  await page.getByRole("button", { name: "All actions" }).click();
  await page.getByLabel("Find an action").fill("Compact active context");
  await page.getByRole("button", { name: "Compact active context Memory" }).click();
  const action = page.getByRole("dialog", { name: "Compact active context", exact: true });
  await action.getByLabel("Set preview only").check();
  await action.getByLabel("Preview only", { exact: true }).check();
  await action.getByLabel("Set retain recent turns").check();
  await action.getByLabel("Retain recent turns", { exact: true }).fill("0");
  await action.getByRole("button", { name: "Run action" }).click();
  await expect(action.getByRole("heading", { name: "Action completed" })).toBeVisible();
  await expect(action).toContainText('"dry_run": true');
  await expect(action.getByRole("button", { name: "Confirm archive" })).toHaveCount(0);
  await action.getByRole("button", { name: "Close dialog" }).click();
  await page.getByRole("button", { name: "Memory & segments", exact: true }).click();
  await memory.getByLabel("Retain recent turns", { exact: true }).fill("0");
  await memory.getByRole("button", { name: "Preview compaction", exact: true }).click();
  await expect(memory.getByRole("region", { name: "Compaction result" })).toContainText("Archive preview");
  await expect(memory.getByRole("button", { name: "Inspect segment 1", exact: true })).toHaveCount(0);
  await memory.getByRole("button", { name: "Compact context", exact: true }).click();
  await memory.getByRole("region", { name: "Review context archive" }).getByRole("button", { name: "Confirm archive" }).click();
  await expect(memory.getByRole("region", { name: "Compaction result" })).toContainText("Context archived");
  await memory.getByRole("button", { name: "Inspect segment 1", exact: true }).click();
  await selected.getByText("Archived messages (2)", { exact: true }).click();
  await expect(selected).toContainText("Keep this in the archive");
});
