import { openWorkspacePanel } from "./navigation.ts";
import { expect, test } from "./fixtures.ts";

test("model workflows preserve global settings before onboarding and expose role selection and structured vendor settings", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/");
  await page.getByLabel("Daemon token").fill("browser-test-token");
  await page.getByRole("button", { name: "Open workspace" }).click();
  await openWorkspacePanel(page, "Providers");
  const providers = page.getByRole("dialog", { name: "Providers", exact: true });
  await providers.getByRole("article", { name: "fixture provider", exact: true }).getByRole("button", { name: "Refresh models", exact: true }).click();
  await expect(providers.getByRole("region", { name: "Refresh results" })).toContainText("fixture: 2 models refreshed");
  await providers.getByRole("button", { name: "Close dialog" }).click();
  await openWorkspacePanel(page, "Models & roles");
  const dialog = page.getByRole("dialog", { name: "Models & roles", exact: true });
  await dialog.getByLabel("Find a model", { exact: true }).fill("vendor/hidden");
  await expect(dialog.locator(".model-cards article")).toHaveCount(0);
  await dialog.getByLabel("Include hidden models", { exact: true }).check();
  const hidden = dialog.getByRole("article", { name: "fixture:vendor/hidden model", exact: true });
  await expect(hidden).toBeVisible();
  await hidden.getByRole("button", { name: "Inspect model", exact: true }).click();
  await expect(dialog.getByRole("region", { name: "Target model settings", exact: true })).toContainText("fixture:vendor/hidden");
  await dialog.getByLabel("Include hidden models", { exact: true }).uncheck();
  await expect(hidden).toHaveCount(0);
  await dialog.getByLabel("Find a model", { exact: true }).fill("fast-fixture");
  const fast = dialog.getByRole("article", { name: "anthropic:fast-fixture model", exact: true });
  await fast.getByRole("button", { name: "Inspect model", exact: true }).click();
  await dialog.getByRole("combobox", { name: "Model setting", exact: true }).selectOption("temperature");
  const setting = dialog.getByRole("region", { name: "Model setting temperature", exact: true });
  await expect(dialog.getByRole("combobox", { name: "Preference scope", exact: true })).toHaveValue("global");
  await setting.getByLabel("Value", { exact: true }).fill("0.4");
  await setting.getByRole("button", { name: "Save model setting", exact: true }).click();
  await expect(setting.getByRole("status")).toContainText("Model setting saved");
  await expect(setting.locator(".setting-values")).toContainText("0.4");
  await fast.getByRole("button", { name: "Favorite", exact: true }).click();
  await expect(fast.getByRole("button", { name: "Remove favorite" })).toHaveAttribute("aria-pressed", "true");
  await dialog.getByLabel("Favorites only", { exact: true }).check();
  await expect(dialog.locator(".model-cards article")).toHaveCount(1);
  await dialog.getByRole("button", { name: "Close dialog" }).click();
  await page.reload();
  await openWorkspacePanel(page, "Models & roles");
  await dialog.getByLabel("Find a model", { exact: true }).fill("fast-fixture");
  await fast.getByRole("button", { name: "Inspect model", exact: true }).click();
  await dialog.getByRole("combobox", { name: "Model setting", exact: true }).selectOption("temperature");
  await expect(setting.locator(".setting-values")).toContainText("0.4");
  await expect(fast.getByRole("button", { name: "Remove favorite" })).toBeVisible();
  await dialog.getByRole("button", { name: "Close dialog" }).click();
  await page.getByRole("button", { name: "Create character", exact: true }).click();
  const create = page.getByRole("dialog", { name: "Create character", exact: true });
  await create.getByLabel("Character name", { exact: true }).fill("nova");
  await create.getByRole("button", { name: "Run action" }).click();
  await expect(create.getByRole("heading", { name: "Action completed" })).toBeVisible();
  await create.getByRole("button", { name: "Close dialog" }).click();
  await page.getByRole("navigation", { name: "Characters" }).getByRole("button", { name: "N nova" }).click();
  await expect(page.getByRole("heading", { name: "nova / main" })).toBeVisible();
  await openWorkspacePanel(page, "Models & roles");
  await dialog.getByLabel("Find a model", { exact: true }).fill("fast-fixture");
  await fast.getByRole("button", { name: "Use for chat", exact: true }).click();
  const roles = dialog.getByRole("region", { name: "Model roles", exact: true });
  const role = (name: string) => roles.getByRole("row").filter({ has: page.getByRole("cell", { name, exact: true }) });
  await expect(role("chat")).toContainText("anthropic:fast-fixture");
  await expect(role("compaction")).toContainText("anthropic:fast-fixture");
  await expect(role("heartbeat")).toContainText("anthropic:claude-opus-4-8");
  await expect(role("sub-agents")).toContainText("anthropic:claude-opus-4-8");
  await dialog.getByRole("button", { name: "Inspect target settings" }).click();
  await dialog.getByRole("combobox", { name: "Model setting", exact: true }).selectOption("temperature");
  await expect(dialog.getByRole("combobox", { name: "Preference scope", exact: true })).toHaveValue("character");
  await setting.getByLabel("Value", { exact: true }).fill("0.2");
  await setting.getByRole("button", { name: "Save model setting", exact: true }).click();
  await expect(setting.locator(".setting-values")).toContainText("0.2");
  await setting.getByRole("button", { name: "Clear saved setting" }).click();
  await expect(setting.getByRole("status")).toContainText("Saved setting cleared");
  await expect(setting.locator(".setting-values")).not.toContainText("0.2");
  await dialog.getByRole("combobox", { name: "Target role", exact: true }).selectOption("background:heartbeat");
  await fast.getByRole("button", { name: "Use for background heartbeat", exact: true }).click();
  await expect(role("heartbeat")).toContainText("heartbeat.model");
  await dialog.getByLabel("Find a model", { exact: true }).fill("vendor-fixture");
  const vendor = dialog.getByRole("article", { name: "openrouter:vendor-fixture model", exact: true });
  await dialog.getByRole("combobox", { name: "Target role", exact: true }).selectOption("background:compaction");
  await vendor.getByRole("button", { name: "Use for background compaction", exact: true }).click();
  await expect(role("compaction")).toContainText("openrouter:vendor-fixture");
  await dialog.getByRole("button", { name: "Reset model selection", exact: true }).click();
  await expect(role("compaction")).toContainText("anthropic:fast-fixture");
  await expect(dialog.getByRole("region", { name: "Target model settings", exact: true })).toContainText("anthropic:fast-fixture");
  await dialog.getByRole("status").filter({ hasText: "Model change completed" }).getByText("Model change details", { exact: true }).click();
  await expect(dialog.getByRole("status").filter({ hasText: "Model change completed" })).toContainText('"active": "anthropic:fast-fixture"');
  await vendor.getByRole("button", { name: "Use for background compaction", exact: true }).click();
  await dialog.getByRole("combobox", { name: "Target role", exact: true }).selectOption("background:all");
  await expect(dialog.getByRole("alert")).toContainText("background tasks use different models");
  await dialog.getByRole("button", { name: "Reset model selection", exact: true }).click();
  await expect(role("heartbeat")).toContainText("anthropic:claude-opus-4-8");
  await vendor.getByRole("button", { name: "Inspect model", exact: true }).click();
  await dialog.getByRole("combobox", { name: "Preference scope", exact: true }).selectOption("global");
  await dialog.getByRole("combobox", { name: "Model setting", exact: true }).selectOption("openrouter_routing");
  const structured = dialog.getByRole("region", { name: "Model setting openrouter_routing", exact: true });
  await structured.getByRole("button", { name: "Add field to value", exact: true }).click();
  await structured.getByLabel("Value field 1", { exact: true }).fill("order");
  await structured.getByRole("combobox", { name: "Value.order type", exact: true }).selectOption("array");
  await structured.getByRole("button", { name: "Add value.order", exact: true }).click();
  await structured.getByLabel("Value.order 1", { exact: true }).fill("provider-a");
  await structured.getByRole("button", { name: "Add field to value", exact: true }).click();
  await structured.getByLabel("Value field 2", { exact: true }).fill("allow_fallbacks");
  await structured.getByRole("combobox", { name: "Value.allow_fallbacks type", exact: true }).selectOption("boolean");
  await structured.getByRole("button", { name: "Save model setting", exact: true }).click();
  await expect(structured.getByRole("status")).toContainText("Model setting saved");
  await expect(structured.locator(".setting-values")).toContainText("provider-a");
  await expect(structured.locator(".setting-values")).toContainText('"allow_fallbacks": false');
  await dialog.getByRole("combobox", { name: "Target role", exact: true }).selectOption("subagent:worker");
  await vendor.getByRole("button", { name: "Use for subagent worker", exact: true }).click();
  await expect(dialog.getByRole("region", { name: "Target model settings", exact: true })).toContainText("openrouter:vendor-fixture");
  await dialog.getByRole("combobox", { name: "Model setting", exact: true }).selectOption("temperature");
  await setting.getByLabel("Value", { exact: true }).fill("0.8");
  await setting.getByRole("button", { name: "Save model setting", exact: true }).click();
  await expect(setting.locator(".setting-values")).toContainText("0.8");
  await page.setViewportSize({ width: 390, height: 844 });
  await setting.scrollIntoViewIfNeeded();
  await page.screenshot({ path: "../out/issue-214/models-mobile.png", fullPage: true });
  expect(await page.evaluate<boolean>("document.documentElement.scrollWidth <= innerWidth")).toBe(true);
  await dialog.getByRole("button", { name: "Reset model selection", exact: true }).click();
  await expect(dialog.getByRole("region", { name: "Target model settings", exact: true })).toContainText("anthropic:claude-opus-4-8");
  expect(errors).toEqual([]);
});
