import { expect, test } from "@playwright/test";

test("provider discovery is usable before character selection and preserves hidden models and partial failures", async ({ page }) => {
  const errors: string[] = [];
  const requests: string[] = [];
  page.on("pageerror", (error) => { errors.push(error.message); });
  page.on("request", (request) => { requests.push(request.url()); });
  await page.goto("/");
  await page.getByLabel("Daemon token").fill("browser-test-token");
  await page.getByRole("button", { name: "Open workspace" }).click();
  await expect(page.getByRole("heading", { name: "Welcome to Shore" })).toBeVisible();
  await page.getByRole("button", { name: "Providers", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Providers", exact: true });
  const fixture = dialog.getByRole("article", { name: "fixture provider", exact: true });
  await expect(fixture).toContainText("key available");
  await expect(fixture).toContainText("No cached models");
  await fixture.getByRole("button", { name: "Refresh models", exact: true }).click();
  await expect(dialog.getByRole("region", { name: "Refresh results" })).toContainText("fixture: 2 models refreshed");
  await expect(fixture).toContainText("1 visible · 1 hidden models");
  await fixture.getByRole("button", { name: "Browse models" }).click();
  const catalogue = dialog.getByRole("region", { name: "fixture models" });
  await expect(catalogue.getByRole("heading", { name: "Visible test model" })).toBeVisible();
  await expect(catalogue.getByRole("article", { name: "vendor/visible" })).toContainText("64,000 context tokens");
  await expect(catalogue.getByRole("heading", { name: "Hidden test model" })).toHaveCount(0);
  await catalogue.getByLabel("Include hidden models").check();
  await expect(catalogue.getByRole("heading", { name: "Hidden test model" })).toBeVisible();
  await catalogue.getByLabel("Find a model").fill("hidden");
  await expect(catalogue.getByRole("heading", { name: "Visible test model" })).toHaveCount(0);
  await expect(catalogue.getByRole("heading", { name: "Hidden test model" })).toBeVisible();
  await dialog.getByRole("button", { name: "Refresh all providers", exact: true }).click();
  const results = dialog.getByRole("region", { name: "Refresh results" });
  await expect(results).toContainText("fixture: 2 models refreshed");
  await expect(results).toContainText("broken: failed");
  await expect(results).toContainText("off: skipped — disabled");
  await expect(results).toContainText("anthropic: skipped — discovery disabled");
  await expect(dialog.getByRole("article", { name: "off provider", exact: true }).getByRole("button", { name: "Refresh models" })).toBeDisabled();
  await expect(dialog).not.toContainText("private-discovery-fixture-key");
  await page.setViewportSize({ width: 390, height: 844 });
  await dialog.screenshot({ path: "../out/issue-214/providers-mobile.png" });
  await expect.poll(() => page.evaluate<boolean>("document.documentElement.scrollWidth <= innerWidth")).toBe(true);
  await dialog.getByRole("button", { name: "Close dialog" }).click();
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole("button", { name: "All actions" }).click();
  await page.getByLabel("Find an action").fill("Browse provider models");
  await page.getByRole("button", { name: "Browse provider models Providers" }).click();
  const action = page.getByRole("dialog", { name: "Browse provider models" });
  await expect(action.locator("datalist option[value=fixture]")).toHaveCount(1);
  await action.getByLabel("Provider", { exact: true }).fill("fixture");
  await action.getByLabel("Set include hidden models").check();
  await action.getByLabel("Include hidden models format").selectOption({ label: "Explicitly unset" });
  await action.getByRole("button", { name: "Run action" }).click();
  await expect(action.getByRole("heading", { name: "Action completed" })).toBeVisible();
  await expect(action).toContainText('"include_hidden": false');
  expect(errors).toEqual([]);
  expect(requests.every((url) => new URL(url).origin === new URL(page.url()).origin)).toBe(true);
});
