import { mkdtemp, readFile, rm } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { expect, test } from "./fixtures.ts";

test("reload and a second tab recover and review an interrupted tool request without repeating its effect", async ({ page, context }) => {
  const root = await mkdtemp(join(tmpdir(), "shore-browser-request-recovery-"));
  const marker = join(root, "effect");
  try {
    await page.goto("/workspace");
    await page.getByLabel("Daemon token").fill("browser-test-token");
    await page.getByRole("button", { name: "Open workspace" }).click();
    await page.getByRole("button", { name: "Create character", exact: true }).click();
    const create = page.getByRole("dialog", { name: "Create character", exact: true });
    await create.getByLabel("Character name", { exact: true }).fill("nova");
    await create.getByRole("button", { name: "Run action", exact: true }).click();
    await expect(create.getByRole("heading", { name: "Action completed" })).toBeVisible();
    await create.getByRole("button", { name: "Close dialog", exact: true }).click();
    await page.getByRole("navigation", { name: "Characters" }).getByRole("button", { name: "N nova" }).click();
    await page.getByRole("button", { name: "Tool workbench", exact: true }).click();
    const dialog = page.getByRole("dialog", { name: "Tool workbench", exact: true });
    await dialog.getByRole("navigation", { name: "Available tools" }).getByRole("button", { name: "bash", exact: true }).click();
    const selected = dialog.getByRole("region", { name: "Selected tool" });
    await selected.getByLabel("command", { exact: true }).fill(`printf 'applied\\n' >> '${marker}'; sleep 60`);
    await selected.getByRole("button", { name: "Review tool run", exact: true }).click();
    await dialog.getByRole("button", { name: "Run tool now", exact: true }).click();
    await expect.poll(async () => readFile(marker, "utf8").catch(() => "")).toBe("applied\n");
    await page.reload();
    await expect(page.getByText("Request outcome uncertain", { exact: true })).toBeVisible();
    expect(await readFile(marker, "utf8")).toBe("applied\n");
    await page.reload();
    await expect(page.getByText("Request outcome uncertain", { exact: true })).toBeVisible();
    expect(await readFile(marker, "utf8")).toBe("applied\n");
    const second = await context.newPage();
    await second.goto(page.url());
    await expect(second.getByText("Request outcome uncertain", { exact: true })).toBeVisible();
    await second.getByRole("button", { name: "Review request", exact: true }).click();
    const history = second.getByRole("dialog", { name: "Request history", exact: true });
    const tool = history.getByRole("article", { name: "Run tool request", exact: true });
    await expect(tool).toContainText("nova / main");
    await history.screenshot({ path: "../out/issue-214/resume-2026-09-23/requests-review-desktop.png" });
    await tool.getByRole("button", { name: "I checked the outcome", exact: true }).click();
    await expect(tool).toHaveCount(0);
    await expect(page.getByText("Request outcome uncertain", { exact: true })).toHaveCount(0);
    await page.reload();
    await expect(page.getByRole("button", { name: "Request history", exact: true })).toBeVisible();
    await expect(page.getByText("Request outcome uncertain", { exact: true })).toHaveCount(0);
    expect(await readFile(marker, "utf8")).toBe("applied\n");
    await second.close();
  } finally { await rm(root, { recursive: true, force: true }); }
});
