import { expect, test } from "./fixtures.ts";

test("settings use live types, preserve collections and secrets, validate writes and reload without a character", async ({ page }) => {
  const errors: string[] = [];
  const responses: string[] = [];
  page.on("pageerror", (error) => { errors.push(error.message); });
  page.on("websocket", (socket) => socket.on("framereceived", ({ payload }) => { responses.push(String(payload)); }));
  await page.goto("/");
  await page.getByLabel("Daemon token").fill("browser-test-token");
  await page.getByRole("button", { name: "Open workspace" }).click();
  await page.getByRole("button", { name: "Settings", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Settings", exact: true });
  await expect(dialog).toContainText("Global configuration");
  const choose = async (key: string) => {
    await dialog.getByLabel("Find a setting").fill(key);
    await dialog.getByRole("button").filter({ has: page.locator("span", { hasText: new RegExp(`^${key.replaceAll(".", "\\.")}$`) }) }).click();
    return dialog.getByRole("region", { name: `Setting ${key}`, exact: true });
  };
  let setting = await choose("defaults.stream");
  await expect(setting.getByRole("heading", { name: "Default", exact: true })).toBeVisible();
  await setting.getByLabel("Value", { exact: true }).uncheck();
  await setting.getByRole("button", { name: "Save setting" }).click();
  await expect(setting.getByRole("status")).toContainText("Setting saved");
  await expect(setting.getByLabel("Value", { exact: true })).not.toBeChecked();
  setting = await choose("cache.keepalive_max");
  await setting.getByLabel("Value", { exact: true }).fill("90m");
  await setting.getByRole("button", { name: "Save setting" }).click();
  await expect(setting.getByRole("status")).toContainText("Setting saved");
  await setting.getByLabel("Value", { exact: true }).fill("yesterday");
  await setting.getByRole("button", { name: "Save setting" }).click();
  await expect(setting.getByRole("alert")).toContainText("durations look like");
  await expect(setting.getByLabel("Value", { exact: true })).toHaveValue("yesterday");
  setting = await choose("behavior.user_message_timestamps");
  await setting.getByLabel("Value", { exact: true }).selectOption("always");
  await setting.getByRole("button", { name: "Save setting" }).click();
  await expect(setting.getByRole("status")).toContainText("Setting saved");
  setting = await choose("memory.compaction.min_turns");
  await setting.getByLabel("Value", { exact: true }).fill("4");
  await setting.getByRole("button", { name: "Save setting" }).click();
  await expect(setting.getByRole("status")).toContainText("Setting saved");
  setting = await choose("notifications.command");
  await setting.getByRole("button", { name: "Add value", exact: true }).click();
  await setting.getByLabel("Value 1", { exact: true }).fill("notify-send");
  await setting.getByRole("button", { name: "Add value", exact: true }).click();
  await setting.getByLabel("Value 2", { exact: true }).fill("a,b");
  await setting.getByRole("button", { name: "Save setting" }).click();
  await expect(setting.getByRole("status")).toContainText("Restart required: [notifications]");
  await expect(setting.getByLabel("Value 2", { exact: true })).toHaveValue("a,b");
  setting = await choose("notifications.ntfy.token");
  await expect(setting.getByLabel("Value", { exact: true })).toHaveAttribute("type", "password");
  await setting.getByLabel("Value", { exact: true }).fill("settings-fixture-secret");
  await setting.getByRole("button", { name: "Save setting" }).click();
  await expect(setting.getByRole("status")).toContainText("Setting saved");
  await expect(setting.getByLabel("Value", { exact: true })).toHaveValue("");
  await expect(setting).toContainText("<redacted>");
  await page.setViewportSize({ width: 390, height: 844 });
  await dialog.screenshot({ path: "../out/issue-214/settings-mobile.png" });
  await expect.poll(() => page.evaluate<boolean>("document.documentElement.scrollWidth <= innerWidth")).toBe(true);
  await dialog.getByRole("button", { name: "Preview reload" }).click();
  const reload = dialog.getByRole("region", { name: "Configuration reload", exact: true });
  await expect(reload).toContainText("Reload preview");
  await expect(reload.getByLabel("Refresh prompt snapshot")).toBeDisabled();
  await reload.getByRole("button", { name: "Apply reload" }).click();
  await expect(reload).toContainText("Configuration reloaded");
  await dialog.getByRole("button", { name: "Check configuration" }).click();
  await expect(dialog.getByRole("region", { name: "Configuration check" })).toBeVisible();
  await dialog.getByRole("button", { name: "Tool access", exact: true }).click();
  await expect(dialog.getByRole("region", { name: "Tool access", exact: true }).getByRole("table")).toBeVisible();
  await dialog.getByRole("button", { name: "Close dialog" }).click();
  await page.reload();
  await page.getByRole("button", { name: "Navigation", exact: true }).click();
  await page.getByRole("button", { name: "Settings", exact: true }).click();
  setting = await choose("notifications.command");
  await expect(setting.getByLabel("Value 2", { exact: true })).toHaveValue("a,b");
  setting = await choose("cache.keepalive_max");
  await expect(setting.getByLabel("Value", { exact: true })).toHaveValue("90m");
  expect(responses.join("\n")).not.toContain("settings-fixture-secret");
  expect(errors).toEqual([]);
});
