import { expect, test } from "./fixtures.ts";
import { readFile } from "node:fs/promises";

test("the tool workbench discovers schemas and runs tools through the shared daemon", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/");
  await page.getByLabel("Daemon token").fill("browser-test-token");
  await page.getByRole("button", { name: "Open workspace" }).click();
  await expect(page.getByRole("button", { name: "Tool workbench", exact: true })).toBeDisabled();
  await page.getByRole("button", { name: "Create character", exact: true }).click();
  const create = page.getByRole("dialog", { name: "Create character", exact: true });
  await create.getByLabel("Character name", { exact: true }).fill("nova");
  await create.getByRole("button", { name: "Run action" }).click();
  await expect(create.getByRole("heading", { name: "Action completed" })).toBeVisible();
  await create.getByRole("button", { name: "Close dialog" }).click();
  await page.getByRole("navigation", { name: "Characters" }).getByRole("button", { name: "N nova" }).click();
  await page.getByRole("button", { name: "Tool workbench", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Tool workbench", exact: true });
  const tools = dialog.getByRole("navigation", { name: "Available tools" });
  const selected = dialog.getByRole("region", { name: "Selected tool" });
  const report = dialog.getByRole("region", { name: "Tool result" });
  const review = dialog.getByRole("region", { name: "Review tool run" });
  const execute = async () => {
    await selected.getByRole("button", { name: "Review tool run", exact: true }).click();
    await review.getByRole("button", { name: "Run tool now", exact: true }).click();
    await expect(report.getByRole("heading", { level: 3 })).toBeVisible();
    await expect(review).toHaveCount(0);
  };
  await dialog.getByLabel("Find a tool").fill("edit");
  await expect(tools.getByRole("button", { name: "read", exact: true })).toHaveCount(0);
  await tools.getByRole("button", { name: "edit", exact: true }).click();
  await selected.getByLabel("path", { exact: true }).fill("tool-fixture.txt");
  await selected.getByLabel("Set content", { exact: true }).check();
  await selected.getByLabel("content", { exact: true }).fill("first line\nreplace me twice; replace me twice\nlast line");
  await selected.getByRole("button", { name: "Review tool run", exact: true }).click();
  await expect(review).toContainText("tool-fixture.txt");
  await review.getByRole("button", { name: "Go back" }).click();
  await expect(report).toHaveCount(0);
  await execute();
  await expect(report).toContainText("Tool completed");
  await selected.getByLabel("Set content", { exact: true }).uncheck();
  await selected.getByLabel("Set edits", { exact: true }).check();
  await selected.getByRole("button", { name: "Add edits", exact: true }).click();
  await selected.getByLabel("old_string", { exact: true }).fill("replace me twice");
  await selected.getByLabel("new_string", { exact: true }).fill("replaced");
  await selected.getByLabel("Set replace_all", { exact: true }).check();
  await selected.getByLabel("replace_all", { exact: true }).check();
  await execute();
  await expect(report).toContainText("Tool completed");
  await dialog.getByLabel("Find a tool").fill("");
  await tools.getByRole("button", { name: "read", exact: true }).click();
  await selected.getByLabel("Set path", { exact: true }).check();
  await selected.getByLabel("path", { exact: true }).fill("tool-fixture.txt");
  await execute();
  await expect(report).toContainText("replaced; replaced");
  await expect(report).toContainText("first line");
  await selected.getByText("Argument overrides", { exact: true }).click();
  await selected.getByRole("button", { name: "Add field to overrides", exact: true }).click();
  await selected.getByLabel("Overrides field 1", { exact: true }).fill("depth");
  await selected.getByLabel("Overrides.depth", { exact: true }).fill("0");
  await execute();
  await expect(report).toContainText("Tool input rejected");
  await expect(selected.getByLabel("path", { exact: true })).toHaveValue("tool-fixture.txt");
  await selected.getByLabel("Overrides.depth", { exact: true }).fill("1");
  await execute();
  await expect(report).toContainText("Tool completed");
  await selected.getByRole("button", { name: "Remove Overrides.depth", exact: true }).click();
  await dialog.getByLabel("Tool name", { exact: true }).fill("missing_tool");
  await dialog.getByRole("button", { name: "Inspect tool", exact: true }).click();
  await expect(dialog.getByRole("alert")).toContainText("missing_tool");
  await expect(selected.getByLabel("path", { exact: true })).toHaveValue("tool-fixture.txt");
  await tools.getByRole("button", { name: "edit", exact: true }).click();
  await selected.getByLabel("path", { exact: true }).fill("tool-long.txt");
  await selected.getByLabel("Set content", { exact: true }).check();
  const complete = `long-output-start\n${"x".repeat(30000)}\nlong-output-end`;
  await selected.getByLabel("content", { exact: true }).fill(complete);
  await execute();
  await expect(report).toContainText("Tool completed");
  await tools.getByRole("button", { name: "read", exact: true }).click();
  await selected.getByLabel("Set path", { exact: true }).check();
  await selected.getByLabel("path", { exact: true }).fill("tool-long.txt");
  await selected.getByLabel("Include full output").check();
  await execute();
  await expect(report).toContainText("The normal output window is truncated.");
  await report.getByText("Complete tool result", { exact: true }).click();
  const downloaded = page.waitForEvent("download");
  await report.getByRole("button", { name: "Download JSON", exact: true }).click();
  const downloadedPath = await (await downloaded).path();
  if (downloadedPath === null) throw new Error("Missing tool result download");
  const saved = JSON.parse(await readFile(downloadedPath, "utf8")) as { raw: string; input: unknown };
  expect(saved.raw).toContain("long-output-end");
  expect(saved.raw.length).toBeGreaterThan(30000);
  expect(saved.input).toEqual({ path: "tool-long.txt" });
  await tools.getByRole("button", { name: "ask_worker", exact: true }).click();
  await selected.getByLabel("query", { exact: true }).fill("Inspect the tool fixture");
  await execute();
  await expect(report).toContainText("Tool completed");
  await expect(report).toContainText("Inspected the fixture workspace");
  await expect(report.getByRole("region", { name: "Nested tool calls" })).toContainText("read · worker · completed");
  await report.getByText("read · worker · completed", { exact: true }).click();
  await expect(report).toContainText("SOUL.md");
  await tools.getByRole("button", { name: "mcp__tool_fixture__nested", exact: true }).click();
  await selected.getByRole("button", { name: "Add entries", exact: true }).click();
  await selected.getByLabel("text", { exact: true }).fill("Nested MCP text\nsecond line");
  await selected.getByRole("combobox", { name: "enabled format", exact: true }).selectOption({ label: "Explicitly unset" });
  await selected.getByLabel("mode", { exact: true }).selectOption("all");
  await selected.getByLabel("Set metadata", { exact: true }).check();
  await selected.getByRole("button", { name: "Add field to metadata", exact: true }).click();
  await selected.getByLabel("metadata field 1", { exact: true }).fill("source");
  await selected.getByLabel("metadata.source", { exact: true }).fill("browser");
  await execute();
  await expect(report).toContainText("Tool completed");
  await expect(report).toContainText('"enabled":null');
  await expect(report).toContainText('"source":"browser"');
  await page.setViewportSize({ width: 390, height: 844 });
  await dialog.screenshot({ path: "../out/issue-214/tools-mobile.png" });
  await expect.poll(() => page.evaluate<boolean>("document.documentElement.scrollWidth <= innerWidth")).toBe(true);
  await selected.getByRole("button", { name: "All tool options", exact: true }).click();
  const advanced = page.getByRole("dialog", { name: "Run tool", exact: true });
  await expect(advanced.getByLabel("Tool", { exact: true })).toHaveValue("mcp__tool_fixture__nested");
  await advanced.getByRole("button", { name: "Run action", exact: true }).click();
  await expect(advanced.getByRole("button", { name: "Confirm execute", exact: true })).toBeVisible();
  await expect(advanced.locator(".confirmation")).toContainText('"enabled": null');
  await advanced.getByRole("button", { name: "Confirm execute", exact: true }).click();
  await expect(advanced.getByRole("heading", { name: "Action completed" })).toBeVisible();
  await advanced.getByLabel("Set describe only", { exact: true }).check();
  await advanced.getByLabel("Describe only", { exact: true }).check();
  await advanced.getByRole("button", { name: "Run action", exact: true }).click();
  await expect(advanced.locator(".confirmation")).toHaveCount(0);
  await expect(advanced).toContainText('"mode": "tool_definition"');
  expect(errors).toEqual([]);
});
