import { expect, test } from "./fixtures.ts";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

test("browser archive transfers are available before character selection", async ({ page }) => {
  await page.goto("/");
  await page.getByLabel("Daemon token").fill("browser-test-token");
  await page.getByRole("button", { name: "Open workspace" }).click();
  await page.getByRole("button", { name: "Character archives", exact: true }).click();
  await expect(page.getByLabel("Archive file", { exact: true })).toBeVisible();
});

test("browser-picked archives preserve history and media across download, collision refusal, deletion and restoration", async ({ page }) => {
  const root = await mkdtemp(join(tmpdir(), "shore-browser-picked-archives-"));
  const picked = join(root, "downloaded-on-this-computer.tar.gz");
  const errors: string[] = []; const imports: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  page.on("request", (request) => { if (/\/api\/archives\/[^/]+\/import$/.test(request.url())) imports.push(request.url()); });
  try {
    await page.goto("/");
    await page.getByLabel("Daemon token").fill("browser-test-token");
    await page.getByRole("button", { name: "Open workspace" }).click();
    const dialog = page.getByRole("dialog");
    const openArchives = async () => {
      await page.getByRole("button", { name: "Character archives", exact: true }).click();
      await expect(dialog.getByLabel("Archive file", { exact: true })).toBeEnabled();
    };
    const close = () => dialog.getByRole("button", { name: "Close dialog" }).click();
    await page.getByRole("button", { name: "Create character", exact: true }).click();
    await dialog.getByLabel("Character name", { exact: true }).fill("nova");
    await dialog.getByRole("button", { name: "Run action" }).click();
    await expect(dialog.getByRole("heading", { name: "Action completed", exact: true })).toBeVisible(); await close();
    await page.getByRole("navigation", { name: "Characters" }).getByRole("button", { name: "N nova" }).click();
    await expect(page.getByRole("heading", { name: "nova / main" })).toBeVisible();
    await page.getByLabel("Message", { exact: true }).fill("Remember this archived picture");
    await page.getByLabel("Attach images", { exact: true }).setInputFiles({ name: "archived.png", mimeType: "image/png", buffer: Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAIAAAD91JpzAAAAFklEQVR4nGMUqdjCwMDAxMDAwMDAAAAOigFED/mW/QAAAABJRU5ErkJggg==", "base64") });
    await expect(page.getByRole("button", { name: "Remove archived.png", exact: true })).toBeVisible();
    await page.getByRole("button", { name: "Send", exact: true }).click();
    await expect(page.getByRole("article", { name: "assistant message" })).toContainText("Remember this archived picture");
    await openArchives();
    await expect(dialog.getByLabel("Character to export", { exact: true })).toHaveValue("nova");
    await dialog.getByRole("button", { name: "Prepare archive", exact: true }).click();
    await expect(dialog.getByText("Export ready to download.", { exact: true })).toBeVisible();
    await page.reload(); await openArchives();
    await expect(dialog.getByText("Export ready to download.", { exact: true })).toBeVisible();
    const saved = page.waitForEvent("download");
    await dialog.getByRole("button", { name: "Download archive", exact: true }).click();
    const download = await saved;
    expect(download.suggestedFilename()).toBe("nova.shore.tar.gz");
    await download.saveAs(picked);
    const bytes = await readFile(picked); expect([...bytes.subarray(0, 2)]).toEqual([31, 139]);
    await expect(dialog.getByText("No archive transfers.", { exact: true })).toBeVisible();
    await dialog.getByLabel("Archive file", { exact: true }).setInputFiles(picked);
    await expect(dialog.getByText("Uploaded and ready to import.", { exact: true })).toBeVisible();
    await dialog.getByRole("button", { name: "Import archive", exact: true }).click();
    await dialog.getByRole("button", { name: "Go back", exact: true }).click();
    expect(imports).toHaveLength(0);
    await dialog.getByRole("button", { name: "Import archive", exact: true }).click();
    await dialog.getByRole("button", { name: "Confirm import", exact: true }).click();
    await expect(dialog.getByRole("alert")).toContainText("Refusing to overwrite existing character");
    await dialog.getByRole("button", { name: "Refresh transfers", exact: true }).click();
    await expect(dialog.getByRole("alert")).toContainText("Refusing to overwrite existing character");
    expect(imports).toHaveLength(1);
    await dialog.getByRole("button", { name: "Remove transfer", exact: true }).click();
    await dialog.getByRole("button", { name: "Delete character…", exact: true }).click();
    await dialog.getByLabel("Repeat character name", { exact: true }).fill("nova");
    await dialog.getByRole("button", { name: "Run action" }).click();
    await dialog.getByRole("button", { name: "Confirm delete", exact: true }).click();
    await expect(dialog.getByRole("heading", { name: "Action completed", exact: true })).toBeVisible();
    await expect(page.getByRole("navigation", { name: "Characters" })).not.toContainText("nova"); await close();
    await openArchives();
    await dialog.getByLabel("Archive file", { exact: true }).setInputFiles({ name: "<img onerror=alert(1)>.tar.gz", mimeType: "application/gzip", buffer: bytes });
    await expect(dialog.getByRole("article", { name: "<img onerror=alert(1)>.tar.gz", exact: true })).toBeVisible();
    await expect(dialog.locator("img")).toHaveCount(0);
    await page.reload(); await openArchives();
    await dialog.getByRole("button", { name: "Import archive", exact: true }).click();
    await dialog.getByRole("button", { name: "Confirm import", exact: true }).click();
    await expect(dialog.getByText("Import completed for nova. Temporary upload removed.", { exact: true })).toBeVisible();
    await dialog.getByRole("button", { name: "Refresh characters", exact: true }).click();
    await expect(page.getByRole("navigation", { name: "Characters" })).toContainText("nova");
    await page.reload(); await openArchives();
    await expect(dialog.getByText("Import completed for nova. Temporary upload removed.", { exact: true })).toBeVisible();
    expect(imports).toHaveLength(2);
    await dialog.getByText("Complete archive transfer", { exact: true }).click();
    await expect(dialog).toContainText("queued_for_rebuild_when_retain_is_enabled");
    await close();
    await page.getByRole("navigation", { name: "Characters" }).getByRole("button", { name: "N nova" }).click();
    await expect(page.getByRole("article", { name: "assistant message" })).toContainText("Remember this archived picture");
    const picture = page.getByRole("article", { name: "user message" }).getByRole("img");
    await expect(picture).toBeVisible(); await picture.click();
    await expect(dialog.getByRole("img", { name: "Full-size conversation image" })).toBeVisible(); await close();
    await page.getByLabel("Message", { exact: true }).fill("Continue after browser restore");
    await page.getByRole("button", { name: "Send", exact: true }).click();
    await expect(page.getByRole("article", { name: "assistant message" }).filter({ hasText: "Continue after browser restore" })).toBeVisible();
    await openArchives();
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: "../out/issue-214/browser-archives-mobile.png", fullPage: true });
    expect(await page.evaluate<boolean>("document.documentElement.scrollWidth <= window.innerWidth")).toBe(true);
    expect(errors).toEqual([]);
  } finally { await rm(root, { recursive: true, force: true }); }
});
