import { expect, test } from "./fixtures.ts";

test("a real browser creates, chats, edits, forks, confirms deletion and recovers its draft", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => { errors.push(error.message); });
  await page.addInitScript("window.shorePolicyViolations = []; document.addEventListener('securitypolicyviolation', event => window.shorePolicyViolations.push(event.violatedDirective));");
  await page.goto("/workspace");
  await page.getByLabel("Daemon token").fill("browser-test-token");
  await page.getByRole("button", { name: "Open workspace" }).click();
  await page.getByRole("button", { name: "Create character", exact: true }).click();
  const dialog = page.getByRole("dialog");
  await dialog.getByLabel("Character name", { exact: true }).fill("nova");
  await dialog.getByRole("button", { name: "Run action" }).click();
  await expect(dialog.getByRole("heading", { name: "Action completed" })).toBeVisible();
  await dialog.getByRole("button", { name: "Close dialog" }).click();
  await page.getByRole("navigation", { name: "Characters" }).getByRole("button", { name: "N nova" }).click();
  await expect(page.getByRole("heading", { name: "nova / main" })).toBeVisible();
  await page.getByLabel("Message", { exact: true }).fill("A thoughtful first question");
  await page.getByRole("button", { name: "Send", exact: true }).click();
  const assistant = page.getByRole("article", { name: "assistant message" });
  await expect(assistant).toContainText("Answer 1: A thoughtful first question");
  await expect(page.getByLabel("Message", { exact: true })).toHaveValue("");
  const user = page.getByRole("article", { name: "user message" });
  await user.getByRole("button", { name: "Edit", exact: true }).click();
  await dialog.getByLabel("Message text", { exact: true }).fill("Edited <img src=x onerror=alert(1)> question");
  await dialog.getByRole("button", { name: "Run action" }).click();
  await expect(dialog.getByRole("heading", { name: "Action completed" })).toBeVisible();
  await dialog.getByRole("button", { name: "Close dialog" }).click();
  await expect(user).toContainText("Edited <img src=x onerror=alert(1)> question");
  await expect(user.locator("img")).toHaveCount(0);
  await page.getByRole("button", { name: "Regenerate", exact: true }).click();
  await dialog.getByLabel("Guidance", { exact: true }).fill("Answer again with more detail");
  await dialog.getByRole("button", { name: "Regenerate", exact: true }).click();
  await expect(assistant).toContainText("Answer 2:");
  await assistant.getByRole("button", { name: "Choose response" }).click();
  await dialog.getByLabel("Set one-based position").check();
  await dialog.getByLabel("One-based position", { exact: true }).fill("1");
  await dialog.getByRole("button", { name: "Run action" }).click();
  await expect(dialog.getByRole("heading", { name: "Action completed" })).toBeVisible();
  await dialog.getByRole("button", { name: "Close dialog" }).click();
  await expect(assistant).toContainText("Answer 1:");
  await page.getByLabel("Message", { exact: true }).fill("Fork only this recent turn");
  await page.getByRole("button", { name: "Send", exact: true }).click();
  await expect(assistant.filter({ hasText: "Answer 3: Fork only this recent turn" })).toBeVisible();
  await page.getByRole("button", { name: "Fork", exact: true }).click();
  await dialog.getByLabel("New thread ID", { exact: true }).fill("branch");
  await dialog.getByLabel("Set recent turns").check();
  await dialog.getByLabel("Recent turns", { exact: true }).fill("1");
  await dialog.getByRole("button", { name: "Run action" }).click();
  await expect(dialog.getByRole("heading", { name: "Action completed" })).toBeVisible();
  await dialog.getByRole("button", { name: "Close dialog" }).click();
  await page.getByRole("navigation", { name: "Threads" }).getByRole("button", { name: /branch/ }).click();
  await expect(page.getByRole("heading", { name: "nova / branch" })).toBeVisible();
  await expect(user).toHaveCount(1);
  await expect(user).toContainText("Fork only this recent turn");
  await page.getByLabel("Message", { exact: true }).fill("Unsent branch draft");
  await page.reload();
  await expect(page.getByRole("heading", { name: "nova / branch" })).toBeVisible();
  await expect(page.getByLabel("Message", { exact: true })).toHaveValue("Unsent branch draft");
  await user.getByRole("button", { name: "Delete", exact: true }).click();
  await dialog.getByRole("button", { name: "Run action" }).click();
  await expect(dialog.getByRole("button", { name: "Confirm delete" })).toBeVisible();
  await dialog.getByRole("button", { name: "Go back" }).click();
  await dialog.getByRole("button", { name: "Close dialog" }).click();
  await expect(user).toHaveCount(1);
  await user.getByRole("button", { name: "Delete", exact: true }).click();
  await dialog.getByRole("button", { name: "Run action" }).click();
  await dialog.getByRole("button", { name: "Confirm delete" }).click();
  await expect(dialog.getByRole("heading", { name: "Action completed" })).toBeVisible();
  await dialog.getByRole("button", { name: "Close dialog" }).click();
  await expect(user).toHaveCount(0);
  await page.getByRole("navigation", { name: "Threads" }).getByRole("button", { name: /main/ }).click();
  await expect(user).toHaveCount(2);
  await expect(page.getByLabel("Message", { exact: true })).toHaveValue("");
  await page.getByLabel("Message", { exact: true }).fill("hold this request");
  await page.getByRole("button", { name: "Send", exact: true }).click();
  await expect(page.getByRole("article", { name: "Streaming response" })).toBeVisible();
  await page.getByRole("button", { name: "Stop", exact: true }).click();
  await page.getByRole("button", { name: "I checked the conversation", exact: true }).click();
  await expect(page.getByRole("button", { name: "Send", exact: true })).toBeEnabled();
  await page.getByLabel("Message", { exact: true }).fill("Picture question");
  await page.getByLabel("Attach images", { exact: true }).setInputFiles({ name: "example.png", mimeType: "image/png", buffer: Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAIAAAD91JpzAAAAFklEQVR4nGMUqdjCwMDAxMDAwMDAAAAOigFED/mW/QAAAABJRU5ErkJggg==", "base64") });
  await expect(page.getByRole("button", { name: "Remove example.png" })).toBeVisible();
  await page.getByRole("button", { name: "Send", exact: true }).click();
  const picture = page.getByRole("article", { name: "user message" }).filter({ hasText: "Picture question" }).getByRole("img");
  await expect(picture).toBeVisible();
  await picture.click();
  await expect(dialog.getByRole("img", { name: "Full-size conversation image" })).toBeVisible();
  await dialog.getByRole("button", { name: "Close dialog" }).click();
  await page.getByRole("button", { name: "Dismiss error" }).click();
  await page.screenshot({ path: "../out/issue-214/workspace-desktop.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole("button", { name: "Navigation", exact: true }).click();
  await page.getByRole("navigation", { name: "Threads" }).getByRole("button", { name: /branch/ }).click();
  await expect(page.getByLabel("Message", { exact: true })).toHaveValue("Unsent branch draft");
  await page.screenshot({ path: "../out/issue-214/workspace-mobile.png", fullPage: true });
  expect(await page.evaluate<boolean>("document.documentElement.scrollWidth <= window.innerWidth")).toBe(true);
  expect(errors).toEqual([]);
  expect(await page.evaluate<unknown[]>("window.shorePolicyViolations")).toEqual([]);
});
