// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityHourClass } from "./ActivityHourClass";

export type ActivityStatusReport = { hour_histogram: Array<number>, hour_classifications: Array<ActivityHourClass>, has_sufficient_heatmap: boolean, engagement_score: number, sessions_per_day: number, message_count: number, turn_count: number, };
