// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutonomyHeartbeatState } from "./AutonomyHeartbeatState";

export type ActivatedHeartbeat = { state: AutonomyHeartbeatState, next_wake_at?: string, seconds_until_wake?: number, };
