// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageRef } from "./ImageRef";

export type AlternativeView = { index: number, position: number, active: boolean, content: string, images: Array<ImageRef>, timestamp: string, };
