// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlternativeView } from "./AlternativeView";

export type AlternativeListing = { ref: string, alt_index: number | null, position: number | null, alt_count: number, alternatives: Array<AlternativeView>, };
