// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceRewind } from "./WorkspaceRewind";

export type AlternativeSelected = { ref: string, alt_index: number, position: number, alt_count: number, content: string, workspace?: WorkspaceRewind, };
