// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutonomyHeartbeatState } from "./AutonomyHeartbeatState";
import type { HeartbeatEvent } from "./HeartbeatEvent";

export type AutonomyStatusReport = { heartbeat_state: AutonomyHeartbeatState, ticks_without_user: number, dormant_after_heartbeat_turns: number, default_interval_secs: number, next_wake_at?: string, seconds_until_wake?: number, last_user_at?: string, seconds_since_user?: number, min_interval_secs: number, max_interval_secs: number, dormant_after_idle_time_secs: number, recent_events: Array<HeartbeatEvent>, };
