// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallSummary } from "./CallSummary";

export type CallListing = { enabled: boolean, entries: Array<CallSummary>, };
