// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallInspection } from "./CallInspection";
import type { CallListing } from "./CallListing";

export type CallLogResult = CallListing | CallInspection;
