// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticUsage } from "./DiagnosticUsage";

export type CallSummary = { id: number, call_id: string, ts: string, call_type: string | null, character: string | null, model: string | null, provider: string | null, finish_reason: string | null, usage: DiagnosticUsage, duration_ms: number | null, error: string | null, request_bytes: number, response_bytes: number, };
