// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallDiffSource } from "./CallDiffSource";
import type { PayloadDiffCounts } from "./PayloadDiffCounts";
import type { PayloadDiffEntry } from "./PayloadDiffEntry";

export type CallDiff = { from_payload: number, to_payload: number, from_call: number, to_call: number, source: CallDiffSource, chunks: PayloadDiffCounts, bytes: PayloadDiffCounts, entries: Array<PayloadDiffEntry>, };
