// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallDetail } from "./CallDetail";
import type { CallDiff } from "./CallDiff";
import type { HttpExchange } from "./HttpExchange";

export type CallInspection = { enabled: boolean, call: CallDetail, wire: Array<HttpExchange>, diff?: CallDiff, };
