// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CallLogArgs = { id?: number | null, count?: number | null, call_type?: string | null, character?: string | null, diff?: boolean | null, against?: number | null, wire?: boolean | null, };
