// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharacterInfo } from "./CharacterInfo";

export type CharacterListing = { characters: Array<CharacterInfo>, };
