// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelInvalidated } from "./ModelInvalidated";

export type CharacterModelReset = { active: string | null, previous_provider: string | null, previous_model_id: string | null, reset_to: string, invalidated?: ModelInvalidated, };
