// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CharacterCreated = { character: string, workspace_dir: string, config_dir: string, created_files: Array<string>, };
