// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharacterAvatar } from "./CharacterAvatar";

/**
 * Information about a character.
 */
export type CharacterInfo = { name: string, avatar?: CharacterAvatar | null, };
