// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CharacterDetails = { name: string, active: boolean, config_dir: string, workspace_dir: string, has_definition: boolean, definition_preview: string | null, bootstrap_files: Array<string>, has_config_override: boolean, pending_deferred_edits: Array<string>, data_dir: string, has_data: boolean, };
