// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaudePlanWindow } from "./ClaudePlanWindow";
import type { UsageBudgetAction } from "./UsageBudgetAction";
import type { UsageBudgetLevel } from "./UsageBudgetLevel";

export type ClaudePlanLimit = { window: ClaudePlanWindow, percent_used: number, resets_at: string | null, status: UsageBudgetLevel, warning_thresholds: Array<number>, crossed_warn_at: Array<number>, limit_at: number, action: UsageBudgetAction, over_limit: boolean, };
