// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaudePlanLimit } from "./ClaudePlanLimit";

export type ClaudePlanLimitsReport = { updated_at: string, subscription_type: string | null, windows: Array<ClaudePlanLimit>, };
