// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Client hello — sent once after connect.
 */
export type ClientHello = { client_type: string, client_name: string, capabilities: Array<string>, 
/**
 * Which character this client wants to talk to.
 */
character?: string | null, 
/**
 * The shared secret, from `SHORE_TOKEN` or `<config_dir>/token`.
 *
 * `Option` on the wire and required in practice: the daemon rejects a
 * hello without one. It is optional here so that a client too old to send
 * it is refused by the *authentication* check with a message saying so,
 * rather than by the deserializer with a parse error that explains
 * nothing.
 */
token?: string | null, };
