// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Client hello — sent once after connect.
 */
export type ClientHello = { client_type: string, client_name: string, capabilities: Array<string>, 
/**
 * Which character this client wants to talk to.
 */
character?: string | null, };
