// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClientHello = { client_type: string, client_name: string, capabilities: Array<string>, character?: string | null, token?: string | null, };
