// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageUpload } from "./ImageUpload";
import type { MessageOverrides } from "./MessageOverrides";

/**
 * Send a user message.
 */
export type ClientMessageBody = { rid?: string | null, text: string, stream: boolean, 
/**
 * Legacy: file paths (only works when client and server share a filesystem).
 */
images: Array<string>, 
/**
 * Preferred: base64-encoded image data (works across machines).
 */
image_data?: Array<ImageUpload>, absence_seconds?: number, overrides?: MessageOverrides | null, };
