// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageUpload } from "./ImageUpload";

export type ClientMessageBody = { rid?: string | null, text: string, stream: boolean, images: Array<string>, image_data?: Array<ImageUpload>, absence_seconds?: number, };
