// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Execute a server command.
 */
export type Command = { rid?: string | null, name: string, args: unknown, };
