// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompactionTrigger } from "./CompactionTrigger";

export type CompactionPassProgress = { thread: string, trigger: CompactionTrigger, started_at: string, phase: string | null, last_tool: string | null, };
