// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompactionReport } from "./CompactionReport";
import type { CompactionTrigger } from "./CompactionTrigger";

export type CompactionPassEnd = { thread: string, trigger: CompactionTrigger, started_at: string, ended_at: string, report: CompactionReport | null, error: string | null, };
