// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompactionCheckpointStatus } from "./CompactionCheckpointStatus";
import type { CompactionPassEnd } from "./CompactionPassEnd";
import type { CompactionPassProgress } from "./CompactionPassProgress";

export type CompactionStatusReport = { running: CompactionPassProgress | null, paused: CompactionCheckpointStatus | null, last: CompactionPassEnd | null, };
