// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CompactionCheckpointStatus = { thread: string, checkpoint_id: string, reason: string, detail: string | null, resume_at: string | null, tool_rounds: number, compacted_turns: number, updated_at: string, };
