// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompactionPassEnd } from "./CompactionPassEnd";
import type { CompactionWatchState } from "./CompactionWatchState";

export type CompactionWatchResult = { character: string, state: CompactionWatchState, pass: CompactionPassEnd | null, };
