// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConfigSource = "chat_models" | "embedding_models" | "image_models" | "tools" | "subagents" | "characters" | "providers";
