// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConfigInvalidated = { merged_character_configs?: boolean, character_discovery?: boolean, removed_character_engines?: number, };
