// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A config file on disk was saved in a state the daemon could not adopt.
 *
 * The daemon keeps running on the last config that loaded, so this is a
 * warning and not an [`Error`]: nothing failed for the client, but what it is
 * looking at on disk is not what the daemon is using. Without it the only
 * record is a daemon log line, and a user who saved a broken character
 * override goes on getting the old behaviour with no idea why.
 */
export type ConfigWarning = { rid?: string | null, 
/**
 * The file the daemon was reading when it gave up.
 */
path: string, 
/**
 * The character whose overlay failed, when the failure was in one.
 */
character?: string | null, 
/**
 * What went wrong, as the daemon would have logged it.
 */
message: string, };
