// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConfigReloadArgs = { apply?: boolean | null, refresh_prompts?: boolean | null, };
