// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConfigCheckResult = { valid: boolean, warnings: Array<string>, info: Array<string>, config_dir: string, data_dir: string, cache_dir: string, chat_models: number, providers: number, };
