// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigInvalidated } from "./ConfigInvalidated";

export type ConfigSetResult = { set: string, value: unknown, previous: unknown, file: string, action: string, restart_required: Array<string>, masked_by_preference: string | null, invalidated?: ConfigInvalidated, };
