// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigSetResult } from "./ConfigSetResult";
import type { ConfigView } from "./ConfigView";

export type ConfigResult = ConfigSetResult | ConfigView;
