// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigSchemaEntry } from "./ConfigSchemaEntry";
import type { ConfigSources } from "./ConfigSources";

export type ConfigSchemaResult = { schema: Array<ConfigSchemaEntry>, sources: ConfigSources, };
