// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigKind } from "./ConfigKind";
import type { ConfigSource } from "./ConfigSource";
import type { ConfigWidth } from "./ConfigWidth";

export type ConfigSchemaEntry = { key: string, kind: ConfigKind, item_kind?: ConfigKind, width?: ConfigWidth, type: string, settable: boolean, optional: boolean, restart_required: boolean, secret: boolean, values: Array<string>, source?: ConfigSource, key_source?: ConfigSource, };
