// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConfigWarning = { rid?: string | null, path: string, character?: string | null, message: string, };
