// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConfigSources = { chat_models: Array<string>, embedding_models: Array<string>, image_models: Array<string>, tools: Array<string>, subagents: Array<string>, characters: Array<string>, providers: Array<string>, };
