// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A structured content block within a message.
 *
 * Messages can contain a sequence of content blocks representing text,
 * thinking/reasoning, tool invocations, and tool results. This preserves
 * the full fidelity of what happened during generation.
 */
export type ContentBlock = { "type": "text", text: string, } | { "type": "thinking", thinking: string, signature?: string | null, } | { "type": "tool_use", id: string, name: string, input: unknown, } | { "type": "redacted_thinking", data: string, } | { "type": "tool_result", tool_use_id: string, content: string, is_error: boolean, };
