// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Message } from "./Message";

export type ConversationPage = { messages: Array<Message>, active_start: number, cursor: number, next_before: number, has_more_before: boolean, global_active_start: number, total_messages: number, total_turns: number, };
