// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

export type ConversationLogArgs = { turns?: number | null, count?: number | null, role?: Role, segment?: number | null, };
