// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateThreadArgs = { name: string, label?: string | null, model?: string | null, compaction?: boolean | null, };
