// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageReferences } from "./MessageReferences";

export type DeleteMessagesArgs = { refs: MessageReferences, };
