// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiagnosticKeyFallbackEntry = { timestamp: string, rid?: string, provider: string, model: string, character: string, from_key: string, to_key?: string, kind: string, status?: number, reason: string, };
