// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiagnosticErrorEntry = { timestamp: string, error_type: string, message: string, context: string, };
