// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticErrorEntry } from "./DiagnosticErrorEntry";

export type DiagnosticErrorRing = { count: number, recent: Array<DiagnosticErrorEntry>, };
