// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCode } from "./ErrorCode";

/**
 * Error response.
 */
export type Error = { rid?: string | null, code: ErrorCode, message: string, };
