// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * SWP error codes per §3.6.
 */
export type ErrorCode = "protocol_error" | "invalid_request" | "not_found" | "busy" | "provider_error" | "timeout" | "internal_error";
