// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticErrorRing } from "./DiagnosticErrorRing";
import type { DiagnosticKeyFallbackRing } from "./DiagnosticKeyFallbackRing";

export type ErrorLogResult = { errors: DiagnosticErrorRing, key_fallbacks: DiagnosticKeyFallbackRing, };
