// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExportCharacterResult = { character: string, archive: string, bytes: number, live: boolean, call_diagnostics: string, external_memory: string, };
