// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GroupedUsageRow = { group: string, call_count: number, total_input: number, total_output: number, total_cache_read: number, total_cache_write: number, total_cost: number, };
