// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TranscriptToolCall } from "./TranscriptToolCall";

export type HeartbeatTranscriptEntry = { reasoning: Array<string>, text: string, tool_calls: Array<TranscriptToolCall>, };
