// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HeartbeatEventKind } from "./HeartbeatEventKind";

export type HeartbeatEvent = { timestamp: string, kind: HeartbeatEventKind, detail: string, };
