// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HeartbeatEventKind = "tick_fired" | "call_failed" | "message_sent" | "message_skipped" | "tool_use" | "dormant" | "wake" | "timeout" | "dormant_ping" | "budget_paused" | "recap_written" | "recap_missing";
