// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HeartbeatControlStatus } from "./HeartbeatControlStatus";

export type HeartbeatControlResult = { status: HeartbeatControlStatus, character: string, warning?: string, };
