// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Message } from "./Message";

export type History = { rid?: string | null, messages: Array<Message>, active_start?: number, config: unknown, selected_character?: string | null, revision: number, };
