// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexBackgroundStatus } from "./IndexBackgroundStatus";

export type HistoryIndexStatus = { path: string, messages: number, chunks: number, embedded: number, pending: number, model: string | null, background: IndexBackgroundStatus, };
