// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistoryDelta } from "./HistoryDelta";
import type { Message } from "./Message";
import type { SegmentSummary } from "./SegmentSummary";

export type History = { delta?: HistoryDelta | null, rid?: string | null, messages: Array<Message>, previous_segment?: SegmentSummary | null, config: unknown, selected_character?: string | null, selected_thread?: string | null, revision: number, };
