// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HttpExchange = { id: number, call_id: string, seq: number, ts: string, character: string | null, call_type: string | null, rid: string | null, method: string, url: string, status: number | null, status_text: string | null, duration_ms: number | null, error: string | null, request_bytes: number, response_bytes: number, request_headers?: Array<[string, string]>, response_headers?: Array<[string, string]>, request_body?: unknown, response_body?: unknown, };
