// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IndexBackgroundStatus = { failures: number, last_error?: string, retry_in_secs?: number, };
