// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InlineImageEncoding } from "./InlineImageEncoding";

export type InlineImageSource = { type: InlineImageEncoding, media_type: string, data: string, };
