// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeepaliveActivationDetail } from "./KeepaliveActivationDetail";
import type { PrimedKeepalivePing } from "./PrimedKeepalivePing";
import type { ScheduledKeepalivePing } from "./ScheduledKeepalivePing";

export type KeepaliveActivation = { "status": "unavailable" } & KeepaliveActivationDetail | { "status": "off" } | { "status": "resumed" } & ScheduledKeepalivePing | { "status": "primed" } & PrimedKeepalivePing | { "status": "skipped" } & KeepaliveActivationDetail | { "status": "failed" } & KeepaliveActivationDetail;
