// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeepalivePingDetail } from "./KeepalivePingDetail";
import type { KeepalivePingSkipped } from "./KeepalivePingSkipped";

export type KeepalivePingResult = { "status": "skipped" } & KeepalivePingSkipped | { "status": "warm" } & KeepalivePingDetail | { "status": "cold" } & KeepalivePingDetail;
