// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeepaliveRequestSource } from "./KeepaliveRequestSource";

export type KeepalivePingDetail = { character: string, source: KeepaliveRequestSource, input_tokens: number, cache_read_tokens: number, cache_creation_tokens: number, note: string, };
