// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ListModelsArgs = { include_hidden?: boolean | null, favorites_only?: boolean | null, };
