// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpConnectionState } from "./McpConnectionState";
import type { McpTransportKind } from "./McpTransportKind";

export type McpStatusEntry = { name: string, transport: McpTransportKind | null, state: McpConnectionState, connected_tools: number, last_error: string | null, next_retry_at: string | null, };
