// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One-shot parameter overrides for a single message.
 */
export type MessageOverrides = { temperature?: number | null, top_p?: number | null, 
/**
 * Enable extended thinking with the given budget (in tokens).
 * `Some(n)` enables thinking with budget `n`; omitted = use model default.
 */
thinking_budget?: number | null, };
