// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a message entered the conversation.
 *
 * Persisted on [`Message`] (and echoed on `NewMessage` pushes) so that
 * history consumers can distinguish autonomous (heartbeat-initiated)
 * assistant messages from replies. `None` on a stored message means the
 * origin was not recorded (messages persisted before origin tracking, or
 * ordinary user/assistant turns where the role already implies it).
 */
export type MessageOrigin = "user_input" | "assistant_reply" | "autonomous";
