// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MessageOverrides = { temperature?: number | null, top_p?: number | null, thinking_budget?: number | null, };
