// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelInvalidated } from "./ModelInvalidated";

export type ModelSelected = { active: string, qualified_name: string, provider: string, model_id: string, changed: boolean, invalidated?: ModelInvalidated, };
