// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelSettingApplicability } from "./ModelSettingApplicability";
import type { ModelSettingEditor } from "./ModelSettingEditor";
import type { ModelSettingKind } from "./ModelSettingKind";

export type ModelSettingSchemaEntry = { key: string, kind: ModelSettingKind, applicability: ModelSettingApplicability, suggestions: Array<string>, allow_custom: boolean, editor?: ModelSettingEditor, };
