// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelSource } from "./ModelSource";

export type ModelSummary = { name: string, qualified_name: string, sdk: string, model_id: string, source: ModelSource, hidden: boolean, favorite: boolean, subscription_included?: boolean, };
