// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelSettingSchemaEntry } from "./ModelSettingSchemaEntry";

export type ModelSettingsDetail = { model: string, provider: string, model_id: string, subagent?: string, applies_to?: string, key?: string, effective_sampler: Record<string, unknown>, saved_global: Record<string, unknown> | null, saved_character: Record<string, unknown> | null, setting_schema: Array<ModelSettingSchemaEntry>, scopes: { [key in string]: string | null }, };
