// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharacterModelReset } from "./CharacterModelReset";
import type { RoleModelReset } from "./RoleModelReset";
import type { ThreadModelReset } from "./ThreadModelReset";

export type ModelResetResult = { "target": "thread" } & ThreadModelReset | { "target": "character" } & CharacterModelReset | { "target": "role" } & RoleModelReset;
