// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelSettingKind = "number" | "u32" | "boolean" | "string" | "duration" | "duration_or_off" | "json_object";
