// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SavedModelSetting } from "./SavedModelSetting";

export type ModelOverviewRole = { role: string, flag: string, model: string | null, source: string | null, inherited: boolean, settings: Array<SavedModelSetting>, same_settings_as: string | null, error: string | null, };
