// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelFavorite = { qualified_name: string, provider: string, model_id: string, favorite: boolean, changed: boolean, favorites: Array<string>, };
