// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharacterModelSelected } from "./CharacterModelSelected";
import type { ModelActive } from "./ModelActive";
import type { ModelSelected } from "./ModelSelected";
import type { RoleModelSelected } from "./RoleModelSelected";

export type ModelSwitchResult = { "target": "current" } & ModelActive | { "target": "thread" } & ModelSelected | { "target": "character" } & CharacterModelSelected | { "target": "role" } & RoleModelSelected;
