// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelRole } from "./ModelRole";
import type { ModelSummary } from "./ModelSummary";

export type ModelListing = { models: { [key in string]: Array<ModelSummary> }, active: string | null, roles: Array<ModelRole>, include_hidden: boolean, favorites_only: boolean, favorite_count: number, hidden_count: number, };
