// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NanoGptWeeklyInputTokens = { used: number, remaining: number, limit: number, resetAt: string, };
