// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NanoGptAccountState } from "./NanoGptAccountState";
import type { NanoGptRouting } from "./NanoGptRouting";
import type { NanoGptWeeklyInputTokens } from "./NanoGptWeeklyInputTokens";

export type NanoGptSubscriptionState = { version: 1, fetched_at: string, active: boolean, state: NanoGptAccountState, weeklyInputTokens?: NanoGptWeeklyInputTokens, routing?: NanoGptRouting, };
