// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NestedToolCall = { tool: string, subagent: string | null, ok: boolean, input: string, output: string, };
