// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentBlock } from "./ContentBlock";
import type { ImageRef } from "./ImageRef";
import type { MessageAlternative } from "./MessageAlternative";
import type { MessageOrigin } from "./MessageOrigin";
import type { Role } from "./Role";

export type NewMessage = { revision: number, character?: string | null, thread?: string | null, rid?: string | null, msg_id: string, role: Role, content: string, images: Array<ImageRef>, content_blocks: Array<ContentBlock>, alt_index?: number | null, alt_count?: number | null, alternatives?: Array<MessageAlternative>, timestamp: string, provider_key?: string | null, model?: string | null, origin?: MessageOrigin | null, };
