// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationDescriptor } from "./OperationDescriptor";

export type OperationCatalogue = { operations: Array<OperationDescriptor>, };
