// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationCondition } from "./OperationCondition";
import type { OperationConfirmation } from "./OperationConfirmation";
import type { OperationEffect } from "./OperationEffect";

export type OperationPolicy = { condition: OperationCondition, effects: Array<OperationEffect>, confirmation: OperationConfirmation, };
