// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OperationEffect = "read" | "workspace_write" | "history_write" | "selection" | "model_selection" | "provider_discovery";
