// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationScalar } from "./OperationScalar";

export type OperationCondition = { "kind": "equals", field: string, value: OperationScalar, } | { "kind": "absent", field: string, };
