// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharacterInfoArgs } from "./CharacterInfoArgs";
import type { CreateThreadArgs } from "./CreateThreadArgs";
import type { EmptyOperationArgs } from "./EmptyOperationArgs";
import type { ForkThreadArgs } from "./ForkThreadArgs";
import type { NamedOperationArgs } from "./NamedOperationArgs";
import type { SwitchThreadArgs } from "./SwitchThreadArgs";
import type { ThreadLabelArgs } from "./ThreadLabelArgs";
import type { ThreadModelArgs } from "./ThreadModelArgs";

export type OperationRequest = { "name": "list_characters", "args": EmptyOperationArgs } | { "name": "create_character", "args": NamedOperationArgs } | { "name": "switch_character", "args": NamedOperationArgs } | { "name": "character_info", "args": CharacterInfoArgs } | { "name": "list_threads", "args": EmptyOperationArgs } | { "name": "switch_thread", "args": SwitchThreadArgs } | { "name": "create_thread", "args": CreateThreadArgs } | { "name": "archive_thread", "args": NamedOperationArgs } | { "name": "fork_thread", "args": ForkThreadArgs } | { "name": "thread_home", "args": NamedOperationArgs } | { "name": "thread_label", "args": ThreadLabelArgs } | { "name": "thread_model", "args": ThreadModelArgs };
