// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OperationPrerequisite = "threads" | "autonomy" | "keepalive" | "session_activation" | "compaction" | "tool_execution";
