// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlternativeListing } from "./AlternativeListing";
import type { AlternativeSelected } from "./AlternativeSelected";
import type { CharacterCreated } from "./CharacterCreated";
import type { CharacterDetails } from "./CharacterDetails";
import type { CharacterListing } from "./CharacterListing";
import type { CharacterSelection } from "./CharacterSelection";
import type { ConversationPage } from "./ConversationPage";
import type { Message } from "./Message";
import type { MessageEdited } from "./MessageEdited";
import type { MessagesDeleted } from "./MessagesDeleted";
import type { OperationCatalogue } from "./OperationCatalogue";
import type { SystemInjected } from "./SystemInjected";
import type { ThreadForkResult } from "./ThreadForkResult";
import type { ThreadListing } from "./ThreadListing";
import type { ThreadSelection } from "./ThreadSelection";

export type OperationResponse = { "name": "discover_operations", "data": OperationCatalogue } | { "name": "log", "data": ConversationPage } | { "name": "history_page", "data": ConversationPage } | { "name": "get", "data": Message } | { "name": "edit", "data": MessageEdited } | { "name": "delete", "data": MessagesDeleted } | { "name": "list_alternatives", "data": AlternativeListing } | { "name": "alt", "data": AlternativeSelected } | { "name": "inject_system", "data": SystemInjected } | { "name": "list_characters", "data": CharacterListing } | { "name": "create_character", "data": CharacterCreated } | { "name": "switch_character", "data": CharacterSelection } | { "name": "character_info", "data": CharacterDetails } | { "name": "list_threads", "data": ThreadListing } | { "name": "switch_thread", "data": ThreadSelection } | { "name": "create_thread", "data": ThreadListing } | { "name": "archive_thread", "data": ThreadListing } | { "name": "fork_thread", "data": ThreadForkResult } | { "name": "thread_home", "data": ThreadListing } | { "name": "thread_label", "data": ThreadListing } | { "name": "thread_model", "data": ThreadListing };
