// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PayloadDiffOperation } from "./PayloadDiffOperation";

export type PayloadDiffEntry = { op: PayloadDiffOperation, hash: string, bytes: number, text: string | null, };
