// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Generation phase change.
 */
export type Phase = { rid?: string | null, phase: string, model?: string | null, };
