// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaudePlanWindow } from "./ClaudePlanWindow";

export type PlanLimitWarning = { rid?: string | null, window: ClaudePlanWindow, limit: string, message: string, percent_used: number, crossed_warn_at: Array<number>, limit_at: number, over_limit: boolean, resets_at: string, resets_at_display: string, };
