// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PrimedKeepalivePing = { input_tokens: number, cache_read_tokens: number, cache_creation_tokens: number, wrote_cache: boolean, interval_secs: number, next_ping_at: string, seconds_until_ping: number, };
