// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderFallbackWarning = { rid?: string | null, provider: string, from_key: string, to_key: string, kind: string, status?: number | null, message: string, };
