// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderStatus } from "./ProviderStatus";

export type ProviderListing = { providers: Array<ProviderStatus>, };
