// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderRefreshResult = { ok: true, provider: string, model_count: number, fetched_at: string, cache_path: string, } | { provider: string, ok: false, error: string, };
