// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StaticModelSource } from "./StaticModelSource";

export type ProviderStaticModel = { source: StaticModelSource, name: string, qualified_name: string, model_id: string, sdk: string, max_output_tokens: number | null, };
