// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderCacheStatus = { present: boolean, models: number, visible: number, hidden: number, fetched_at: string | null, };
