// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The daemon rotated from one configured provider key to another mid-request
 * because the previous key reported a credential-scoped failure (missing,
 * invalid, exhausted quota or budget, account-scoped rate limit).
 *
 * Emitted only when the previous key had `warn_on_fallback = true`. The
 * payload intentionally never carries the env var value or the API key
 * itself — only the provider key, the friendly key names, the failure
 * classification, and a sanitized human-readable reason.
 */
export type ProviderFallbackWarning = { rid?: string | null, 
/**
 * Provider this fallback applies to (e.g. `"openrouter"`).
 */
provider: string, 
/**
 * Friendly name of the key being abandoned.
 */
from_key: string, 
/**
 * Friendly name of the key now in use.
 */
to_key: string, 
/**
 * Stable failure tag from `CredentialFailureKind::as_str()`. Stable
 * across releases so client-side rendering can branch on it.
 */
kind: string, 
/**
 * HTTP status when the failure was a status-shaped error; `None` for
 * missing-key / network / classified-by-body cases.
 */
status?: number | null, 
/**
 * Sanitized human-readable summary. Never contains secrets.
 */
message: string, };
