// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderRefreshResult } from "./ProviderRefreshResult";
import type { ProviderSkipped } from "./ProviderSkipped";

export type ProvidersRefreshed = { results: Array<ProviderRefreshResult>, skipped: Array<ProviderSkipped>, };
