// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscoveredModelSource } from "./DiscoveredModelSource";

export type ProviderDiscoveredModel = { source: DiscoveredModelSource, model_id: string, display_name: string | null, sdk: string, owned_by: string | null, context_length: number | null, max_output_tokens: number | null, supports_tools: boolean | null, supports_images: boolean | null, supports_reasoning: boolean | null, supports_prompt_cache: boolean | null, subscription_included?: boolean, subscription_input_multiplier?: number, discovered_at: string, };
