// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderDiscoveredModel } from "./ProviderDiscoveredModel";
import type { ProviderModelCache } from "./ProviderModelCache";
import type { ProviderStaticModel } from "./ProviderStaticModel";

export type ProviderModelListing = { provider: string, discovered: Array<ProviderDiscoveredModel>, hidden: Array<ProviderDiscoveredModel>, static: Array<ProviderStaticModel>, include_hidden: boolean, cache: ProviderModelCache, };
