// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderCacheStatus } from "./ProviderCacheStatus";
import type { ProviderKeyStatus } from "./ProviderKeyStatus";

export type ProviderStatus = { name: string, enabled: boolean, sdk: string, base_url: string | null, discovery_enabled: boolean, keys: Array<ProviderKeyStatus>, cache: ProviderCacheStatus, };
