// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RateLimitSnapshot = { requests_remaining?: number, requests_limit?: number, input_tokens_remaining?: number, input_tokens_limit?: number, output_tokens_remaining?: number, output_tokens_limit?: number, resets_at?: string, };
