// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Regenerate last response.
 */
export type Regen = { rid?: string | null, stream: boolean, };
