// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelRole } from "./ModelRole";

export type RoleModelReset = { active: string | null, role: string, cleared: Array<string>, source: string | null, file: string | null, reset_to: string, roles: Array<ModelRole>, };
