// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunningWorkKind } from "./RunningWorkKind";

export type RunningWork = { kind: RunningWorkKind, character: string, thread: string | null, started_at: string, running_secs: number, };
