// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolDescription } from "./ToolDescription";
import type { ToolRunReport } from "./ToolRunReport";

export type RunToolResult = ToolDescription | ToolRunReport;
