// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SegmentMutation } from "./SegmentMutation";
import type { SegmentSummary } from "./SegmentSummary";

export type SegmentChanged = { character: string, thread: string, action: SegmentMutation, segment: SegmentSummary, };
