// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SegmentChanged } from "./SegmentChanged";
import type { SegmentInspection } from "./SegmentInspection";
import type { SegmentsListing } from "./SegmentsListing";

export type SegmentsResult = SegmentsListing | SegmentInspection | SegmentChanged;
