// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SegmentAction } from "./SegmentAction";

export type SegmentsArgs = { action?: SegmentAction | null, index?: number | null, value?: string | null, };
