// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Message } from "./Message";
import type { SegmentSummary } from "./SegmentSummary";

export type SegmentInspection = { character: string, thread: string, segment: SegmentSummary, messages: Array<Message>, };
