// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SegmentSummary = { index: number, first_message_at: string | null, last_message_at: string | null, compacted_at: string, message_count: number, excluded: boolean, label: string | null, note: string | null, memory_before: string | null, memory_after: string | null, };
