// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SegmentSummary } from "./SegmentSummary";

export type SegmentsListing = { character: string, thread: string, segments: Array<SegmentSummary>, count: number, };
