// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlternativeDirection } from "./AlternativeDirection";

export type SelectAlternativeArgs = { ref?: string | null, index?: number | null, position?: number | null, direction?: AlternativeDirection | null, };
