// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SendImage = { rid?: string | null, path: string, caption?: string | null, data?: string | null, subagent?: string | null, };
