// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Server-generated image ready.
 */
export type SendImage = { rid?: string | null, path: string, caption?: string | null, 
/**
 * Base64-encoded image data for wire transfer.
 */
data?: string | null, 
/**
 * Sub-agent name when this image is from a nested `ask_<name>` loop; see
 * [`StreamStart::subagent`].
 */
subagent?: string | null, };
