// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CacheWarning } from "./CacheWarning";
import type { CommandOutput } from "./CommandOutput";
import type { ConfigWarning } from "./ConfigWarning";
import type { Error } from "./Error";
import type { History } from "./History";
import type { NewMessage } from "./NewMessage";
import type { Phase } from "./Phase";
import type { Ping } from "./Ping";
import type { ProviderFallbackWarning } from "./ProviderFallbackWarning";
import type { ProviderWarning } from "./ProviderWarning";
import type { RequestAccepted } from "./RequestAccepted";
import type { RequestFinished } from "./RequestFinished";
import type { SendImage } from "./SendImage";
import type { ServerHello } from "./ServerHello";
import type { Shutdown } from "./Shutdown";
import type { StreamChunk } from "./StreamChunk";
import type { StreamEnd } from "./StreamEnd";
import type { StreamStart } from "./StreamStart";
import type { ToolCall } from "./ToolCall";
import type { ToolResult } from "./ToolResult";
import type { UsageWarning } from "./UsageWarning";

export type ServerMessage = { "type": "hello" } & ServerHello | { "type": "history" } & History | { "type": "shutdown" } & Shutdown | { "type": "ping" } & Ping | { "type": "command_output" } & CommandOutput | { "type": "error" } & Error | { "type": "stream_start" } & StreamStart | { "type": "stream_chunk" } & StreamChunk | { "type": "stream_end" } & StreamEnd | { "type": "phase" } & Phase | { "type": "new_message" } & NewMessage | { "type": "tool_call" } & ToolCall | { "type": "tool_result" } & ToolResult | { "type": "send_image" } & SendImage | { "type": "cache_warning" } & CacheWarning | { "type": "provider_warning" } & ProviderWarning | { "type": "provider_fallback_warning" } & ProviderFallbackWarning | { "type": "usage_warning" } & UsageWarning | { "type": "config_warning" } & ConfigWarning | { "type": "request_accepted" } & RequestAccepted | { "type": "request_finished" } & RequestFinished;
