// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackgroundModelTarget } from "./BackgroundModelTarget";
import type { ModelPreferenceScope } from "./ModelPreferenceScope";

export type SetModelSettingArgs = { name?: string | null, background_task?: BackgroundModelTarget | null, subagent?: string | null, key: string, scope?: ModelPreferenceScope | null, value?: unknown, };
