// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Message } from "./Message";

export type StoredSubagentTrace = { ts: string, subagent: string, parent_tool_use_id: string, rid?: string, model: string, messages: Array<Message>, messages_expired?: boolean, result?: string, error?: string, };
