// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Begin streaming.
 */
export type StreamStart = { rid?: string | null, regen: boolean, 
/**
 * Set when this frame belongs to a sub-agent's nested tool loop (the
 * `[subagents.<name>]` name behind an `ask_<name>` call). Clients render
 * it as attributed/nested activity; `None` is the primary model.
 */
subagent?: string | null, };
