// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StreamChunk = { rid?: string | null, text: string, content_type: string, subagent?: string | null, task_id?: string | null, };
