// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StreamStart = { rid?: string | null, regen: boolean, replaces?: Array<string>, subagent?: string | null, task_id?: string | null, };
