// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Partial content chunk.
 */
export type StreamChunk = { rid?: string | null, text: string, content_type: string, 
/**
 * Sub-agent name when this chunk is from a nested `ask_<name>` loop; see
 * [`StreamStart::subagent`].
 */
subagent?: string | null, };
