// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimingInfo } from "./TimingInfo";
import type { TokenCounts } from "./TokenCounts";

export type StreamMetadata = { tokens: TokenCounts, timing: TimingInfo, model: string, };
