// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubagentAccess = { name: string, enabled: boolean, tools: Array<string>, model: string | null, };
