// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StoredSubagentTrace } from "./StoredSubagentTrace";

export type SubagentTraceResult = { character: string, requested_ids?: Array<string>, entries: Array<StoredSubagentTrace>, };
