// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubagentStatus = { task_id: string, character: string, name: string, query: string, status: string, detail?: string | null, };
