// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackgroundModelTarget } from "./BackgroundModelTarget";

export type SwitchModelArgs = { name?: string | null, background_task?: BackgroundModelTarget | null, subagent?: string | null, include_hidden?: boolean | null, };
