// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CacheInvalidation } from "./CacheInvalidation";
import type { ThreadForkDetails } from "./ThreadForkDetails";
import type { ThreadView } from "./ThreadView";

export type ThreadForkResult = { fork: ThreadForkDetails, character: string, threads: Array<ThreadView>, home: string, current: string, invalidated?: CacheInvalidation, };
