// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadForkOrigin = { fork_id: string, source: string, created_at: string, messages: number, turns: number, };
