// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadForkOrigin } from "./ThreadForkOrigin";

export type ThreadView = { id: string, label?: string, created_at: string, last_active?: string, chat_model?: string, compaction: boolean, home: boolean, current: boolean, turns?: number, warm?: boolean, forked_from?: ThreadForkOrigin, };
