// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForkScope } from "./ForkScope";

export type ThreadForkDetails = { fork_id: string, thread: string, source: string, created_at: string, messages: number, turns: number, scope: ForkScope, requested_turns?: number, };
