// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CacheInvalidation } from "./CacheInvalidation";

export type ThreadSelection = { character: string, thread: string, changed: boolean, selected_thread?: string, invalidated?: CacheInvalidation, };
