// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TokenCounts = { input: number, output: number, cache_read: number, cache_write: number, };
