// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToolResult = { rid?: string | null, tool_id: string, tool_name: string, output: string, is_error: boolean, subagent?: string | null, };
