// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageRef } from "./ImageRef";
import type { NestedToolCall } from "./NestedToolCall";
import type { ToolKind } from "./ToolKind";

export type ToolRunReport = { tool: string, character: string, kind: ToolKind, enabled: boolean, input: { [key: string]: unknown }, ok: boolean, rejected: boolean, duration_ms: number, output: string, truncated: boolean, result_chars: number, raw: string | null, calls: Array<NestedToolCall>, images?: Array<ImageRef>, };
