// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolDescriptionMode } from "./ToolDescriptionMode";
import type { ToolKind } from "./ToolKind";

export type ToolDescription = { mode: ToolDescriptionMode, tool: string, kind: ToolKind, enabled: boolean, description: string, input_schema: { [key: string]: unknown }, };
