// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubagentAccess } from "./SubagentAccess";
import type { ToolAccess } from "./ToolAccess";

export type ToolAccessResult = { tools: Array<ToolAccess>, subagents: Array<SubagentAccess>, mcp: Array<string>, warnings: Array<string>, };
