// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tool completed.
 */
export type ToolResult = { rid?: string | null, tool_id: string, tool_name: string, output: string, is_error: boolean, 
/**
 * Sub-agent name when this result is from a nested `ask_<name>` loop; see
 * [`StreamStart::subagent`].
 */
subagent?: string | null, };
