// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TranscriptSource } from "./TranscriptSource";

export type TranscriptArgs = { source?: TranscriptSource | null, count?: number | null, };
