// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TranscriptRow } from "./TranscriptRow";
import type { TranscriptSource } from "./TranscriptSource";

export type TranscriptResult = { enabled: boolean, source: TranscriptSource, character?: string, entries: Array<TranscriptRow>, };
