// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UsageCostSource = { cost_source: string, calls: number, unpriced_calls: number, total_cost: number, };
