// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UsageBudgetFilters = { character: string | null, provider: string | null, api_key: string | null, model: string | null, call_type: string | null, usage_kind: Array<string>, };
