// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NanoGptSubscriptionState } from "./NanoGptSubscriptionState";
import type { UsageAnomalyCount } from "./UsageAnomalyCount";
import type { UsageBudget } from "./UsageBudget";
import type { UsageCacheCoverage } from "./UsageCacheCoverage";
import type { UsageCacheHealth } from "./UsageCacheHealth";
import type { UsageCallAttempts } from "./UsageCallAttempts";
import type { UsageCostSource } from "./UsageCostSource";
import type { UsageRateLimitReading } from "./UsageRateLimitReading";
import type { UsageSummaryRow } from "./UsageSummaryRow";

export type UsageSummaryReport = { period: string, period_since?: string, timezone: string, summary: Array<UsageSummaryRow>, cache_health: Array<UsageCacheHealth>, anomaly_count_7d: number, anomaly_counts_7d: Array<UsageAnomalyCount>, cache_coverage: Array<UsageCacheCoverage>, cost_sources: Array<UsageCostSource>, rate_limits: Array<UsageRateLimitReading>, nanogpt_subscription: NanoGptSubscriptionState | null, call_attempts: UsageCallAttempts, budgets: Array<UsageBudget>, };
