// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UsageCacheCoverage = { state: string, reason: string | null, calls: number, cache_read_tokens: number, cache_write_tokens: number, };
