// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageBudgetAction } from "./UsageBudgetAction";
import type { UsageBudgetFilters } from "./UsageBudgetFilters";
import type { UsageBudgetLevel } from "./UsageBudgetLevel";
import type { UsageBudgetPeriod } from "./UsageBudgetPeriod";
import type { UsagePace } from "./UsagePace";

export type UsageBudget = { name: string, period: UsageBudgetPeriod, period_start: string, period_end: string, reset_at: string, timezone: string, current_cost: number, cost_limit: number, percent_used: number, status: UsageBudgetLevel, action: UsageBudgetAction, effective_action: UsageBudgetAction, warning_thresholds: Array<number>, crossed_warn_at: Array<number>, over_limit: boolean, compaction_allowed_over_budget: boolean, filters: UsageBudgetFilters, pace?: UsagePace, };
