// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageBudget } from "./UsageBudget";
import type { UsageCallAttempts } from "./UsageCallAttempts";

export type UsageBudgetReport = { timezone: string, allow_compaction_over_budget: boolean, budgets: Array<UsageBudget>, call_attempts: UsageCallAttempts, };
