// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageAnomaly } from "./UsageAnomaly";

export type UsageAnomaliesReport = { anomalies: Array<UsageAnomaly>, };
