export type UsageWarning = { rid?: string | null, 
budget: string, 
message: string, 
current_cost: number, 
cost_limit: number, 
percent_used: number, 
crossed_warn_at: Array<number>, 
period: string, 
period_start: string, 
reset_at: string, 
reset_at_display: string, 
scope?: string | null, };
