// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UsageAnomaly = { ts: string, character: string, model: string, call_type: string, anomaly: string | null, cache_read_tokens: number, cache_write_tokens: number, };
