// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UsageBudgetAction = "warn" | "block" | "pause_background" | "pause_heartbeat";
