// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UsageDimension = "model" | "provider" | "call_type" | "kind" | "api_key" | "cost_source";
