// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupedUsageRow } from "./GroupedUsageRow";
import type { UsageDimension } from "./UsageDimension";

export type UsageGroupedReport = { dimension: UsageDimension, period: string, period_since?: string, summary: Array<GroupedUsageRow>, };
