// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageBudgetAction } from "./UsageBudgetAction";
import type { UsageBudgetLevel } from "./UsageBudgetLevel";
import type { UsageBudgetPeriod } from "./UsageBudgetPeriod";

export type UsagePace = { period: UsageBudgetPeriod, window_start: string, window_end: string, allowance: number, base_allowance: number, rollover: number, debt_adjustment: number, current_cost: number, remaining: number, percent_used: number, periods_remaining: number, status: UsageBudgetLevel, action: UsageBudgetAction, effective_action: UsageBudgetAction, warning_thresholds: Array<number>, crossed_warn_at: Array<number>, over_limit: boolean, };
