// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageAnomaliesReport } from "./UsageAnomaliesReport";
import type { UsageBudgetReport } from "./UsageBudgetReport";
import type { UsageExportReport } from "./UsageExportReport";
import type { UsageGroupedReport } from "./UsageGroupedReport";
import type { UsageSummaryReport } from "./UsageSummaryReport";

export type UsageResult = { "mode": "summary" } & UsageSummaryReport | { "mode": "summary_by" } & UsageGroupedReport | { "mode": "budget" } & UsageBudgetReport | { "mode": "anomalies" } & UsageAnomaliesReport | { "mode": "csv" } & UsageExportReport | { "mode": "tsv" } & UsageExportReport;
