// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UsageAnomalyCount = { anomaly: string, calls: number, cache_write_tokens: number, };
