// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExportCharacterResult } from "./ExportCharacterResult";
import type { ImportCharacterResult } from "./ImportCharacterResult";

export type WebArchiveResult = { "name": "export_character", "data": ExportCharacterResult } | { "name": "import_character", "data": ImportCharacterResult };
