// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebArchiveInfo } from "./WebArchiveInfo";

export type WebArchiveList = { archives: Array<WebArchiveInfo>, max_upload_bytes: number, max_expanded_bytes: number, };
