// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebArchivePhase } from "./WebArchivePhase";
import type { WebArchiveResult } from "./WebArchiveResult";

export type WebArchiveInfo = { id: string, filename: string, bytes: number, expires_at: number, phase: WebArchivePhase, downloadable: boolean, result?: WebArchiveResult, error?: string, };
