// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WebProblemCode = "unauthorized" | "forbidden" | "invalid_request" | "too_many_requests" | "reload_required" | "unavailable" | "not_found";
