// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebProblemCode } from "./WebProblemCode";

export type WebProblem = { code: WebProblemCode, message: string, };
