// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebRequestInfo } from "./WebRequestInfo";

export type WebRequestList = { requests: Array<WebRequestInfo>, max_records: number, max_result_bytes: number, };
