// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WebSessionInfo = { contract: string, protocol: number, expires_at: number, max_message_bytes: number, max_pending_requests: number, };
