// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticIndexError } from "./DiagnosticIndexError";
import type { WorkspaceIndexStatus } from "./WorkspaceIndexStatus";

export type WorkspaceIndexResult = DiagnosticIndexError | WorkspaceIndexStatus;
