// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexBackgroundStatus } from "./IndexBackgroundStatus";

export type WorkspaceIndexStatus = { path: string, unusable?: string, files: number, embedded: number, pending: number, skipped: number, skip_reasons: { [key in string]: number }, vectors: number, models: Array<string>, bytes: number, last_indexed_at: string | null, background: IndexBackgroundStatus, };
