// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceKept } from "./WorkspaceKept";

export type WorkspaceRewind = { restored: Array<string>, skipped: Array<string>, kept?: WorkspaceKept, };
