// Generated by scripts/browser_validators.ts. Do not edit.
import type { OperationInput, OperationName, OperationResult } from "../operations/types.ts";
export declare function validOperationInput<N extends OperationName>(name: N, value: unknown): value is OperationInput<N>;
export declare function validOperationResult<N extends OperationName>(name: N, value: unknown): value is OperationResult<N>;
