// Generated by scripts/browser_validators.ts from the terminal capability inventory. Do not edit.
export const VIEW_PREFERENCES = {
  "timestamps": [
    "on",
    "off",
    "toggle"
  ],
  "thinking": [
    "on",
    "off",
    "toggle"
  ],
  "tools": [
    "on",
    "off",
    "toggle"
  ],
  "subagent": [
    "on",
    "off",
    "toggle"
  ],
  "compaction": [
    "on",
    "off",
    "toggle"
  ],
  "images": [
    "on",
    "off",
    "toggle"
  ],
  "metadata": [
    "on",
    "off",
    "toggle"
  ],
  "usage": [
    "off",
    "always",
    "warn",
    "toggle"
  ],
  "budget": [
    "auto",
    "cap",
    "pace",
    "toggle"
  ]
} as const;
export const TERMINAL_SHORTCUTS = [
  [
    "regen",
    "msg regen"
  ],
  [
    "edit",
    "msg edit"
  ],
  [
    "alt",
    "msg alt"
  ],
  [
    "delete",
    "msg delete"
  ],
  [
    "compact",
    "compact"
  ],
  [
    "usage",
    "usage"
  ],
  [
    "status",
    "status"
  ],
  [
    "clear",
    "clear"
  ]
] as const;
export const TERMINAL_LOCAL_COMMANDS = {
  "insert": {
    "home": [],
    "end": []
  },
  "normal": {},
  "scroll": {
    "direction": [
      "up",
      "down",
      "top",
      "bottom"
    ],
    "amount": []
  },
  "segment": {
    "target": []
  },
  "images": {},
  "subagents": {},
  "editor": {},
  "image": {
    "target": []
  },
  "cancel": {},
  "edit_cancel": {},
  "help": {},
  "palette": {
    "scope": [
      "full",
      "shortcuts",
      "config"
    ]
  },
  "output": {},
  "bind": {
    "key": [],
    "command": [],
    "global": []
  },
  "unbind": {
    "key": [],
    "global": []
  },
  "quit": {}
} as const;
