// Generated by scripts/browser_validators.ts from the terminal capability inventory. Do not edit.
export const VIEW_PREFERENCES = {
  "timestamps": [
    "on",
    "off",
    "toggle"
  ],
  "thinking": [
    "on",
    "off",
    "toggle"
  ],
  "tools": [
    "on",
    "off",
    "toggle"
  ],
  "subagent": [
    "on",
    "off",
    "toggle"
  ],
  "compaction": [
    "on",
    "off",
    "toggle"
  ],
  "images": [
    "on",
    "off",
    "toggle"
  ],
  "metadata": [
    "on",
    "off",
    "toggle"
  ],
  "usage": [
    "off",
    "always",
    "warn",
    "toggle"
  ],
  "budget": [
    "auto",
    "cap",
    "pace",
    "toggle"
  ]
} as const;
