import terminal from "../../docs/capabilities/terminal.generated.json" with { type: "json" };

export function browserPreferences(): Record<string, string> {
  return { "preferences.generated.ts": "// Generated by scripts/browser_validators.ts from the terminal capability inventory. Do not edit.\n" +
    `export const VIEW_PREFERENCES = ${JSON.stringify(Object.fromEntries(terminal.view_preferences.map((preference) => [preference.key, preference.values])), null, 2)} as const;\n` +
    `export const TERMINAL_SHORTCUTS = ${JSON.stringify(terminal.keymap.shortcuts, null, 2)} as const;\n` +
    `export const TERMINAL_LOCAL_COMMANDS = ${JSON.stringify(Object.fromEntries(terminal.commands.filter((command) => command.path.startsWith("shore ui ")).map((command) => [command.path.slice("shore ui ".length).replaceAll("-", "_"), Object.fromEntries(command.arguments.filter((argument) => argument.id !== "help").map((argument) => [argument.id, argument.choices]))])), null, 2)} as const;\n` };
}
