import { readFile, writeFile, mkdir } from "node:fs/promises";
import { resolve } from "node:path";
import { _ } from "ajv";
import standaloneCode from "ajv/dist/standalone/index.js";
import { contractValidator } from "../src/operations/validation.ts";
import wire from "../src/protocol/wire.generated.json" with { type: "json" };
import web from "../src/web/schemas.generated.json" with { type: "json" };
import operations from "../src/operations/schemas.generated.json" with { type: "json" };

export function browserValidators(): Record<string, string> {
  const validator = contractValidator({ source: true, esm: true, formats: _`require("../operations/number_formats.ts").numberFormats` });
  const contracts = {
    ServerMessage: wire.server,
    WebSessionInfo: web.session,
    WebProblem: web.problem,
  };
  const names: Record<string, string> = {};
  for (const [name, schema] of Object.entries(contracts)) {
    validator.addSchema(schema, name);
    names[`valid${name}`] = name;
  }
  const operationValidator = contractValidator({ source: true, esm: true, formats: _`require("../operations/number_formats.ts").numberFormats` });
  const operationNames: Record<string, string> = {};
  for (const operation of operations) {
    for (const kind of ["input", "output"] as const) {
      const name = `${kind}_${operation.name}`;
      operationValidator.addSchema(operation[kind], name);
      operationNames[name] = name;
    }
  }
  const lookup = (["input", "output"] as const).map((kind) =>
    `const ${kind}Validators = new Map([${operations.map((operation) => `[${JSON.stringify(operation.name)}, ${kind}_${operation.name}]`).join(",")}]);\n` +
    `export function validOperation${kind === "input" ? "Input" : "Result"}(name, value) { return ${kind}Validators.get(name)?.(value) === true; }\n`,
  ).join("");
  return {
    "operation_validators.generated.js": "// Generated by scripts/browser_validators.ts. Do not edit.\n" + standaloneCode(operationValidator, operationNames) + "\n" + lookup,
    "operation_validators.generated.d.ts": "// Generated by scripts/browser_validators.ts. Do not edit.\n" +
      'import type { OperationInput, OperationName, OperationResult } from "../operations/types.ts";\n' +
      'export declare function validOperationInput<N extends OperationName>(name: N, value: unknown): value is OperationInput<N>;\n' +
      'export declare function validOperationResult<N extends OperationName>(name: N, value: unknown): value is OperationResult<N>;\n',
    "validators.generated.js": "// Generated by scripts/browser_validators.ts. Do not edit.\n" + standaloneCode(validator, names) + "\n",
    "validators.generated.d.ts": "// Generated by scripts/browser_validators.ts. Do not edit.\n" + Object.keys(contracts).map((name) =>
      `import type { ${name} } from "../protocol/${name}.ts";\nexport declare function valid${name}(value: unknown): value is ${name};\n`,
    ).join(""),
  };
}

if (import.meta.main) {
  const root = resolve(import.meta.dir, "../src/browser");
  await mkdir(root, { recursive: true });
  for (const [name, source] of Object.entries(browserValidators())) {
    const path = resolve(root, name);
    if (process.argv.includes("--write")) await writeFile(path, source);
    else if (await readFile(path, "utf8") !== source) throw new Error(`Stale ${name}; run bun run browser:generate`);
  }
}
