import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { WEB_CONTRACT, WEB_PROTOCOL } from "../src/web/contract.ts";

export async function buildBrowserAssets(): Promise<string> {
  const result = await Bun.build({
    entrypoints: [new URL("../src/browser/app.tsx", import.meta.url).pathname], target: "browser", format: "esm", minify: true,
    define: { SHORE_WEB_CONTRACT: JSON.stringify(WEB_CONTRACT), SHORE_WEB_PROTOCOL: String(WEB_PROTOCOL), "process.env.NODE_ENV": '"production"' },
  });
  if (!result.success) throw new AggregateError(result.logs, "Browser build failed");
  const script = result.outputs.at(0);
  if (script === undefined || result.outputs.length !== 1) throw new Error("Expected one self-contained browser script");
  const javascript = await script.text();
  const css = await readFile(new URL("../src/browser/app.css", import.meta.url), "utf8");
  const name = (content: string, extension: string) => `/assets/app-${createHash("sha256").update(content).digest("hex").slice(0, 16)}.${extension}`;
  const jsPath = name(javascript, "js");
  const cssPath = name(css, "css");
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><title>Shore workspace</title><link rel="stylesheet" href="${cssPath}"><script type="module" src="${jsPath}"></script></head><body><div id="root"></div><noscript>Enable JavaScript to use the Shore workspace.</noscript></body></html>`;
  return "// Generated by scripts/build_browser.ts. Do not edit.\nexport const browserAssets: Readonly<Record<string, { type: string; body: string }>> = " + JSON.stringify({
    "/": { type: "text/html; charset=utf-8", body: html },
    [jsPath]: { type: "text/javascript; charset=utf-8", body: javascript },
    [cssPath]: { type: "text/css; charset=utf-8", body: css },
  }) + ";\n";
}

if (import.meta.main) {
  const source = await buildBrowserAssets();
  const destination = new URL("../src/web/assets.generated.ts", import.meta.url);
  if (process.argv.includes("--check")) {
    if (await readFile(destination, "utf8") !== source) throw new Error("Stale browser assets; run bun run browser:build");
  } else await writeFile(destination, source);
}
