import { createHash } from "node:crypto";
import { readdir, readFile, writeFile } from "node:fs/promises";
import { WEB_CONTRACT, WEB_PROTOCOL } from "../src/web/contract.ts";

const BROWSER = new URL("../src/browser/", import.meta.url);

export async function browserStyles(): Promise<string> {
  const styles = new URL("styles/", BROWSER);
  const group = async (folder: string) => (await readdir(new URL(folder, styles)).catch(() => [])).filter((file) => file.endsWith(".css")).sort().map((file) => `${folder}${file}`);
  const files = ["tokens.css", "base.css", ...await group("components/"), ...await group("themes/")];
  return (await Promise.all(files.map(async (file) => `/* ${file} */\n${await readFile(new URL(file, styles), "utf8")}`))).join("\n");
}

const LATIN = "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD";
const LATIN_EXT = "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF";
export const FONT_FACES = ["latin", "latin-ext"].flatMap((subset) => [
    { family: "Geist", file: `geist-${subset}-wght-normal.woff2`, style: "normal", weight: "100 900", range: subset === "latin" ? LATIN : LATIN_EXT },
    { family: "Geist Mono", file: `geist-mono-${subset}-wght-normal.woff2`, style: "normal", weight: "100 900", range: subset === "latin" ? LATIN : LATIN_EXT },
    ...["normal", "italic"].map((style) => ({ family: "Newsreader", file: `newsreader-${subset}-wght-${style}.woff2`, style, weight: "200 800", range: subset === "latin" ? LATIN : LATIN_EXT })),
]);

type Asset = { type: string; body: string; encoding?: "base64" };

async function buildBrowserAssets(): Promise<string> {
  const result = await Bun.build({
    entrypoints: ["main.tsx", "theme_boot.ts"].map((file) => new URL(file, BROWSER).pathname), target: "browser", format: "esm", minify: true, naming: "[name].[ext]",
    define: { SHORE_WEB_CONTRACT: JSON.stringify(WEB_CONTRACT), SHORE_WEB_PROTOCOL: String(WEB_PROTOCOL), "process.env.NODE_ENV": '"production"' },
  });
  if (!result.success) throw new AggregateError(result.logs, "Browser build failed");
  const output = async (name: string) => {
    const file = result.outputs.find((item) => item.path.endsWith(`${name}.js`));
    if (file === undefined) throw new Error(`Missing browser bundle: ${name}`);
    return await file.text();
  };
  if (result.outputs.length !== 2) throw new Error("Expected two self-contained browser scripts");
  const javascript = await output("main");
  const boot = await output("theme_boot");
  const name = (content: string | Uint8Array, prefix: string, extension: string) => `/assets/${prefix}-${createHash("sha256").update(content).digest("hex").slice(0, 16)}.${extension}`;
  const fonts: Record<string, Asset> = {};
  const faces: string[] = [];
  for (const face of FONT_FACES) {
    const bytes = new Uint8Array(await readFile(new URL(`fonts/${face.file}`, BROWSER)));
    const path = name(bytes, face.file.replace(/\.woff2$/, ""), "woff2");
    fonts[path] = { type: "font/woff2", body: Buffer.from(bytes).toString("base64"), encoding: "base64" };
    faces.push(`@font-face{font-family:"${face.family}";font-style:${face.style};font-weight:${face.weight};font-display:swap;src:url(${path}) format("woff2");unicode-range:${face.range}}`);
  }
  const css = `${faces.join("\n")}\n${await browserStyles()}`;
  const jsPath = name(javascript, "app", "js");
  const bootPath = name(boot, "theme", "js");
  const cssPath = name(css, "app", "css");
  const html = `<!doctype html><html lang="en" data-theme="default"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="color-scheme" content="dark"><title>Shore</title><script src="${bootPath}"></script><link rel="stylesheet" href="${cssPath}"><script type="module" src="${jsPath}"></script></head><body><div id="root"></div><noscript>Enable JavaScript to use Shore.</noscript></body></html>`;
  const assets: Record<string, Asset> = {
    "/": { type: "text/html; charset=utf-8", body: html },
    [jsPath]: { type: "text/javascript; charset=utf-8", body: javascript },
    [bootPath]: { type: "text/javascript; charset=utf-8", body: boot },
    [cssPath]: { type: "text/css; charset=utf-8", body: css },
    ...fonts,
  };
  return "// Generated by scripts/build_browser.ts. Do not edit.\nexport const browserAssets: Readonly<Record<string, { type: string; body: string; encoding?: \"base64\" }>> = " + JSON.stringify(assets) + ";\n";
}

if (import.meta.main) {
  const source = await buildBrowserAssets();
  const destination = new URL("../src/web/assets.generated.ts", import.meta.url);
  if (process.argv.includes("--check")) {
    if (await readFile(destination, "utf8") !== source) throw new Error("Stale browser assets; run bun run browser:build");
  } else await writeFile(destination, source);
}
