import { createHash } from "node:crypto";
import { readdir, readFile, writeFile } from "node:fs/promises";
import { WEB_CONTRACT, WEB_PROTOCOL } from "../src/web/contract.ts";

const BROWSER = new URL("../src/browser/", import.meta.url);

export async function browserStyles(): Promise<string> {
  const styles = new URL("styles/", BROWSER);
  const group = async (folder: string) => (await readdir(new URL(folder, styles)).catch(() => [])).filter((file) => file.endsWith(".css")).sort().map((file) => `${folder}${file}`);
  const files = ["tokens.css", "base.css", ...await group("components/"), ...await group("themes/")];
  return (await Promise.all(files.map(async (file) => `/* ${file} */\n${await readFile(new URL(file, styles), "utf8")}`))).join("\n");
}

export async function buildBrowserAssets(): Promise<string> {
  const result = await Bun.build({
    entrypoints: ["main.tsx", "theme_boot.ts"].map((file) => new URL(file, BROWSER).pathname), target: "browser", format: "esm", minify: true, naming: "[name].[ext]",
    define: { SHORE_WEB_CONTRACT: JSON.stringify(WEB_CONTRACT), SHORE_WEB_PROTOCOL: String(WEB_PROTOCOL), "process.env.NODE_ENV": '"production"' },
  });
  if (!result.success) throw new AggregateError(result.logs, "Browser build failed");
  const output = async (name: string) => {
    const file = result.outputs.find((item) => item.path.endsWith(`${name}.js`));
    if (file === undefined) throw new Error(`Missing browser bundle: ${name}`);
    return await file.text();
  };
  if (result.outputs.length !== 2) throw new Error("Expected two self-contained browser scripts");
  const javascript = await output("main");
  const boot = await output("theme_boot");
  const css = await browserStyles();
  const name = (content: string, prefix: string, extension: string) => `/assets/${prefix}-${createHash("sha256").update(content).digest("hex").slice(0, 16)}.${extension}`;
  const jsPath = name(javascript, "app", "js");
  const bootPath = name(boot, "theme", "js");
  const cssPath = name(css, "app", "css");
  const html = `<!doctype html><html lang="en" data-theme="default"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="color-scheme" content="dark"><title>Shore</title><script src="${bootPath}"></script><link rel="stylesheet" href="${cssPath}"><script type="module" src="${jsPath}"></script></head><body><div id="root"></div><noscript>Enable JavaScript to use Shore.</noscript></body></html>`;
  return "// Generated by scripts/build_browser.ts. Do not edit.\nexport const browserAssets: Readonly<Record<string, { type: string; body: string }>> = " + JSON.stringify({
    "/": { type: "text/html; charset=utf-8", body: html },
    [jsPath]: { type: "text/javascript; charset=utf-8", body: javascript },
    [bootPath]: { type: "text/javascript; charset=utf-8", body: boot },
    [cssPath]: { type: "text/css; charset=utf-8", body: css },
  }) + ";\n";
}

if (import.meta.main) {
  const source = await buildBrowserAssets();
  const destination = new URL("../src/web/assets.generated.ts", import.meta.url);
  if (process.argv.includes("--check")) {
    if (await readFile(destination, "utf8") !== source) throw new Error("Stale browser assets; run bun run browser:build");
  } else await writeFile(destination, source);
}
