import ts from "typescript";
import { readFileSync } from "node:fs";
import { join, relative } from "node:path";
import { Glob } from "bun";

const ROOT = join(import.meta.dir, "..");
const ROOTS = [join(ROOT, "src"), join(ROOT, "tests"), join(ROOT, "scripts")];

const DIRECTIVE =
  /^(\/\/|\/\*)[\s*]*(@ts-|eslint|biome|prettier|deno-|c8 |v8 |istanbul|#__|@__|<reference|<amd)/;

const GENERATED = /^.{0,200}?\b(generated by|@generated|do not edit)\b/is;

function commentRanges(sf: ts.SourceFile, text: string): ts.CommentRange[] {
  const byPos = new Map<number, ts.CommentRange>();
  const add = (rs: ts.CommentRange[] | undefined) => {
    for (const r of rs ?? []) byPos.set(r.pos, r);
  };
  const walk = (node: ts.Node) => {
    const kids = node.getChildren(sf);
    if (kids.length === 0) {
      add(ts.getLeadingCommentRanges(text, node.getFullStart()));
      add(ts.getTrailingCommentRanges(text, node.getEnd()));
      return;
    }
    for (const k of kids) walk(k);
  };
  walk(sf);
  return [...byPos.values()].sort((a, b) => a.pos - b.pos);
}

const offenders: string[] = [];
let scanned = 0;
let generated = 0;

for (const root of ROOTS)
for (const rel of new Glob("**/*.ts").scanSync(root)) {
  const abs = join(root, rel);
  const text = readFileSync(abs, "utf8");
  if (GENERATED.test(text)) {
    generated++;
    continue;
  }
  scanned++;
  const sf = ts.createSourceFile(rel, text, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
  for (const r of commentRanges(sf, text)) {
    const body = text.slice(r.pos, r.end);
    if (r.pos === 0 && body.startsWith("#!")) continue;
    if (DIRECTIVE.test(body.trimStart())) continue;
    const line = sf.getLineAndCharacterOfPosition(r.pos).line + 1;
    const first = body.split("\n")[0].trim();
    offenders.push(`${relative(ROOT, abs)}:${line}  ${first.slice(0, 90)}`);
  }
}

if (offenders.length > 0) {
  console.error(`Comments are not allowed in daemon/. Found ${offenders.length}:\n`);
  for (const o of offenders) console.error(`  ${o}`);
  console.error(`\nSee CLAUDE.md. Rename something or write a test instead.`);
  console.error(`Directives (@ts-expect-error, eslint-*) and generated files are exempt.`);
  process.exit(1);
}

console.log(`no comments in ${scanned} files (${generated} generated files skipped)`);
