import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { _ } from "ajv";
import standaloneCode from "ajv/dist/standalone/index.js";
import { contractValidator } from "../src/operations/validation.ts";
import operations from "../src/operations/schemas.generated.json" with { type: "json" };
import web from "../src/web/schemas.generated.json" with { type: "json" };

const HEADER = "// Generated by scripts/contract_validators.ts. Do not edit.\n";

const WEB_CONTRACTS = {
  validWebLogin: ["login", "WebLogin"],
  validWebSession: ["session", "WebSessionInfo"],
  validWebProblem: ["problem", "WebProblem"],
  validWebArchiveExport: ["archive_export", "WebArchiveExport"],
  validWebArchiveInfo: ["archive_info", "WebArchiveInfo"],
  validWebArchiveList: ["archive_list", "WebArchiveList"],
  validWebRequestInfo: ["request_info", "WebRequestInfo"],
  validWebRequestList: ["request_list", "WebRequestList"],
} as const;

export function contractValidators(): Record<string, string> {
  const operationValidator = contractValidator({ source: true, esm: true, formats: _`require("./number_formats.ts").numberFormats` });
  const operationNames: Record<string, string> = {};
  for (const operation of operations) {
    for (const kind of ["input", "output"] as const) {
      const name = `${kind}_${operation.name}`;
      operationValidator.addSchema(operation[kind], name);
      operationNames[name] = name;
    }
  }
  const lookup = (["input", "output"] as const).map((kind) =>
    `const ${kind}Validators = new Map([${operations.map((operation) => `[${JSON.stringify(operation.name)}, ${kind}_${operation.name}]`).join(",")}]);\n` +
    `export function validOperation${kind === "input" ? "Input" : "Result"}(name, value) { return ${kind}Validators.get(name)?.(value) === true; }\n`,
  ).join("") +
    'export function isOperationName(name) { return inputValidators.has(name); }\n' +
    'export function operationValidator(kind, name) { return (kind === "input" ? inputValidators : outputValidators).get(name); }\n';

  const webValidator = contractValidator({ source: true, esm: true, formats: _`require("../operations/number_formats.ts").numberFormats` });
  const webNames: Record<string, string> = {};
  for (const [name, [key]] of Object.entries(WEB_CONTRACTS)) {
    webValidator.addSchema(web[key], key);
    webNames[name] = key;
  }

  return {
    "operations/validators.generated.js": HEADER + standaloneCode(operationValidator, operationNames) + "\n" + lookup,
    "operations/validators.generated.d.ts": HEADER +
      'import type { OperationInput, OperationName, OperationResult } from "./types.ts";\n' +
      "export interface ContractError { keyword: string; instancePath: string; params: Record<string, unknown>; message?: string }\n" +
      "export interface ContractValidator { (value: unknown): boolean; errors?: ContractError[] | null }\n" +
      'export declare function operationValidator(kind: "input" | "output", name: string): ContractValidator | undefined;\n' +
      "export declare function isOperationName(name: string): name is OperationName;\n" +
      "export declare function validOperationInput<N extends OperationName>(name: N, value: unknown): value is OperationInput<N>;\n" +
      "export declare function validOperationResult<N extends OperationName>(name: N, value: unknown): value is OperationResult<N>;\n",
    "web/validators.generated.js": HEADER + standaloneCode(webValidator, webNames) + "\n",
    "web/validators.generated.d.ts": HEADER + Object.entries(WEB_CONTRACTS).map(([name, [, type]]) =>
      `import type { ${type} } from "../protocol/${type}.ts";\nexport declare function ${name}(value: unknown): value is ${type};\n`,
    ).join(""),
  };
}

if (import.meta.main) {
  const root = resolve(import.meta.dir, "../src");
  for (const [name, source] of Object.entries(contractValidators())) {
    const path = resolve(root, name);
    if (process.argv.includes("--write")) await writeFile(path, source);
    else if (await readFile(path, "utf8").catch(() => undefined) !== source) throw new Error(`Stale ${name}; run bun run contracts:generate`);
  }
}
