#!/usr/bin/env python3
"""Exercise the chat transcript and its live updates, markdown safety and streaming, themes, shortcuts, settings wording and the parity ratchet."""
import sys
from mutation import run

T = "src/browser/chat/transcript.ts"
W = "src/browser/workspace.ts"
M = "src/browser/markdown.tsx"
R = "src/browser/chat/Message.tsx"
H = "src/browser/theme.ts"
Z = "src/browser/font_size.ts"
S = "src/browser/app/shortcuts.ts"
F = "src/browser/settings/format.ts"
P = "scripts/browser_parity.ts"
O = "src/browser/sidebar/order.ts"
MUTANTS = [
    ("a reply leaves its thread where it was in the sidebar", W, 'threads: touchThread(this.#state.threads, this.#state.character, message) });', '});'),
    ("a reply in another character's thread of the same name moves this one", W, 'if (message.character !== character || Number.isNaN(time)) return threads;', 'if (Number.isNaN(time)) return threads;'),
    ("a reply moves every thread", W, 'threads.map((item) => item.id === thread ?', 'threads.map((item) => true ?'),
    ("a reply's local offset is compared as written", W, 'last_active: new Date(time).toISOString() }', 'last_active: message.timestamp }'),
    ("threads ordered by creation alone", O, '(b.last_active ?? b.created_at).localeCompare(a.last_active ?? a.created_at)', 'b.created_at.localeCompare(a.created_at)'),
    ("home no longer listed first", O, 'Number(b.home) - Number(a.home) || ', ''),
    ("a labelled segment loses its number", T, ': `Segment ${String(segment.index)} · ${segment.label}`', ': segment.label'),
    ("one message is counted as messages", T, 'segment.message_count === 1 ? "message" : "messages"', '"messages"'),
    ("an excluded segment is not marked", T, '...(segment.excluded ? ["excluded from memory"] : [])', '...([] as string[])'),
    ("a one-day segment shows its day twice", T, 'const dates = first === last || last === "" ? first :', 'const dates = last === "" ? first :'),
    ("a segment with only an end date shows nothing", T, ': first === "" ? last : `${first} – ${last}`', ': `${first} – ${last}`'),
    ("a segment from another year hides its year", T, 'year: date.getFullYear() === now.getFullYear() ? undefined : "numeric" });\n}\n\nexport function segmentDetail', 'year: undefined });\n}\n\nexport function segmentDetail'),
    ("every assistant reply treated as last", T, 'last: index === lastAssistant', 'last: message.role === "assistant"'),
    ("day dividers repeat for every message", T, 'if (key !== previousDay) {', 'if (true) {'),
    ("tool results create duplicate chips", T, 'if (view === undefined) views.push', 'if (true) views.push'),
    ("tool errors reported as success", T, 'view.error = block.is_error === true;', 'view.error = false;'),
    ("blank text blocks rendered", T, 'if (block.text.trim() !== "") views.push', 'views.push'),
    ("swipe count off by one", T, 'Math.max(1, (message.alt_index ?? count - 1) + 1)', 'Math.max(1, message.alt_index ?? count - 1)'),
    ("previous swipe allowed on the first response", T, 'canPrevious: position > 1', 'canPrevious: position > 0'),
    ("finished streams from other requests reappear", T, 'stream.rid !== null && active.has(stream.rid)', 'true'),
    ("finished stream shown alongside its message", T, '!messages.some((message) => message.msg_id === stream.msgId) && stream.rid', 'stream.rid'),
    ("every step gets its own box", T, 'else if (last?.kind === "activity") last.steps.push(view);', 'else if (false) last.steps.push(view);'),
    ("a finished reply still says Thinking", T, 'if (live && latest?.kind === "thinking")', 'if (latest?.kind === "thinking")'),
    ("a finished reply names its last tool instead of summarising", T, 'if (live && latest?.kind === "tool" && latest.output === null)', 'if (latest?.kind === "tool" && latest.output === null)'),
    ("a running tool is summarised instead of named", T, 'if (live && latest?.kind === "tool" && latest.output === null)', 'if (false)'),
    ("the summary ignores reasoning", T, 'steps.some((step) => step.kind === "thinking") ? `Reasoned and used ${count}` : `Used ${count}`', '`Used ${count}`'),
    ("long tool lists are not shortened", T, 'names.length > 3 ?', 'false ?'),
    ("a reply's saved rounds are not recognised by their tool calls", T, 'const shared = toolUseIds(last.content_blocks).some((id) => stream.tools.includes(id));', 'const shared = false;'),
    ("a round saved before its tool calls arrive is not recognised", T, 'const awaitingTools = stream.tools.length === 0 && ', 'const awaitingTools = false && '),
    ("an earlier reply ending in a tool call is claimed", T, 'const awaitingTools = stream.tools.length === 0 && ', 'const awaitingTools = '),
    ("saved tool calls repeat in the live reply", T, '? !ids.includes(block.id) :', '? true :'),
    ("a live result replaces the saved one", T, 'block.type === "tool_result" && !answered.has(block.tool_use_id)', 'block.type === "tool_result"'),
    ("a round saved after its tool calls arrived shows twice", T, '(stream.round.tools.includes(latest) || !stream.tools.includes(latest))', '!stream.tools.includes(latest)'),
    ("a round saved before its tool calls arrived shows twice", T, '(stream.round.tools.includes(latest) || !stream.tools.includes(latest))', 'stream.round.tools.includes(latest)'),
    ("earlier rounds vanish before any are saved", T, 'const unsaved = saved === undefined ? stream :', 'const unsaved = saved === undefined ? stream.round :'),
    ("empty reasoning makes an empty reply look started", T, 'unsaved.reasoning === "" ? [] :', 'false ? [] :'),
    ("empty text makes an empty reply look started", T, 'unsaved.text === "" ? [] :', 'false ? [] :'),
    ("a superseded segment page still opens", W, 'if (epoch !== this.#segmentEpoch || page.segment === null) return;', 'if (page.segment === null) return;'),
    ("older from the current conversation does nothing", W, 'const previous = view === null ? this.#state.previousSegment : view.previous;', 'const previous = view?.previous ?? null;'),
    ("newer from the newest segment stays put", W, '    if (next === null) this.closeSegment();', '    if (next === null) return;'),
    ("closing a segment leaves its pending page able to land", W, '  closeSegment(): void {\n    this.#segmentEpoch += 1;\n', '  closeSegment(): void {\n'),
    ("an exhausted segment is asked for more", W, 'if (view === null || this.#loadingEarlier || !view.hasEarlier) return;', 'if (view === null || this.#loadingEarlier) return;'),
    ("earlier messages land after the later ones", W, 'messages: [...page.messages.filter((message) => !ids.has(message.msg_id)), ...current.messages]', 'messages: [...current.messages, ...page.messages.filter((message) => !ids.has(message.msg_id))]'),
    ("a conversation switch keeps the segment open", W, 'previousSegment, segmentView: changed ? null : this.#state.segmentView,', 'previousSegment, segmentView: this.#state.segmentView,'),
    ("a delta forgets the segment before the context", W, 'const previousSegment = full ? message.previous_segment ?? null : this.#state.previousSegment;', 'const previousSegment = message.previous_segment ?? null;'),
    ("a new segment leaves the open view's neighbours stale", W, '        if (!changed && moved) void this.#refreshSegmentNeighbours();\n', ''),
    ("a delta anchored at the top keeps the old messages", W, 'const index = history.delta.after === null ? -1 :', 'const index = history.delta.after === null ? previous.length - 1 :'),
    ("a new model call keeps the previous round's text", W, 'const round = next.round.tools.length > 0 ? { reasoning: "", text: "", tools: [] } : next.round;', 'const round = next.round;'),
    ("the current round drops its reasoning", W, '{ ...round, reasoning: round.reasoning + message.text }', '{ ...round }'),
    ("the current round drops its text", W, '{ ...round, text: round.text + message.text }', '{ ...round }'),
    ("tool calls are not remembered for the reply", W, 'next.tools = [...next.tools, message.tool_id];', ''),
    ("tool calls are not remembered for the current round", W, 'next.round = { ...next.round, tools: [...next.round.tools, message.tool_id] };', ''),
    ("streamed chunks render at once instead of once per frame", W, '}, message.type === "stream_chunk");', '}, false);'),
    ("every streamed chunk asks for a frame of its own", W, '    if (this.#framePending) return;\n', ''),
    ("a frame already covered by an immediate update renders again", W, 'this.#frame(() => { if (this.#framePending) this.#notify(); });', 'this.#frame(() => { this.#notify(); });'),
    ("an immediate update leaves its frame pending", W, '    this.#framePending = false;\n    for (const listener', '    for (const listener'),
    ("compaction notice survives its request", T, 'if (phase === null || phase.id < finished) return null;', 'if (phase === null) return null;'),
    ("tool summary shows raw objects", T, 'values.find((value): value is string => typeof value === "string" && value.trim() !== "")', 'values.find((value): value is string => value !== undefined)'),
    ("unsafe link schemes become clickable", M, 'const SAFE_LINK = /^(https?:|mailto:)/i;', 'const SAFE_LINK = /^/i;'),
    ("raw HTML rendered as markup", M, 'case "html": return node.value;', 'case "html": return <span key={key} dangerouslySetInnerHTML={{ __html: node.value }} />;'),
    ("settled blocks reused for text that no longer starts with them", M, 'const base = text.startsWith(previous.text) ? previous : UNSETTLED;', 'const base = previous;'),
    ("a later link definition leaves earlier references unlinked", M, 'if (defined && base !== UNSETTLED) return markdownBlocks(text);', ''),
    ("link definitions inside quotes and lists go unnoticed", M, '("children" in node && node.children.some(defines))', 'false'),
    ("blocks settle once a link definition is in play", M, 'const start = defined || open < 1 ?', 'const start = open < 1 ?'),
    ("nothing ever settles", M, 'const start = defined || open < 1 ? undefined :', 'const start = true ? undefined :'),
    ("a block settles while the line that closed it is still arriving", M, '<= complete);', '<= tail.length);'),
    ("settled text cut at the block instead of its line", M, 'const cut = tail.lastIndexOf("\\n", start - 1) + 1;', 'const cut = start;'),
    ("the newest settled block is left out", M, 'blocks: blocks.slice(0, base.blocks.length + open)', 'blocks: blocks.slice(0, base.blocks.length + open - 1)'),
    ("each render parses the whole text again (NEEDS A SEAM — static rendering keeps nothing between renders)", M, 'markdownBlocks(text, settled.current)', 'markdownBlocks(text)'),
    ("markdown re-renders when its text is unchanged (NEEDS A SEAM — static rendering has no re-renders)", M, 'export const Markdown = memo(function Markdown(', 'export const Markdown = (function Markdown('),
    ("saved messages re-render on every streamed frame (NEEDS A SEAM — no test renders a message row, whose module needs a browser location)", R, 'export const MessageRow = memo(function MessageRow(', 'export const MessageRow = (function MessageRow('),
    ("unknown stored theme accepted", H, 'return isThemeId(value) ? value : DEFAULT_THEME;', 'return (value ?? DEFAULT_THEME) as ThemeId;'),
    ("failed theme save reported as saved", H, 'error = "This browser couldn\'t save the theme, so it will reset on reload.";', 'error = "";'),
    ("theme changes from other tabs ignored", H, 'if (theme !== this.#theme) this.#set(theme, "");', ''),
    ("unknown stored text size accepted", Z, 'return isFontSizeId(value) ? value : DEFAULT_FONT_SIZE;', 'return (value ?? DEFAULT_FONT_SIZE) as FontSizeId;'),
    ("failed text size save reported as saved", Z, 'error = "This browser couldn\'t save the text size, so it will reset on reload.";', 'error = "";'),
    ("text size changes from other tabs ignored", Z, 'if (size !== this.#size) this.#set(size, "");', ''),
    ("text size not applied to the document", Z, 'root.dataset["fontSize"] = size;', ''),
    ("help shortcut fires while typing", S, 'if (!typing && !mod && !event.altKey && event.key === "?") return "help";', 'if (!mod && !event.altKey && event.key === "?") return "help";'),
    ("palette ignores the modifier", S, 'if (mod && !event.altKey && !event.shiftKey && event.key.toLowerCase() === "k") return "palette";', 'if (event.key.toLowerCase() === "k") return "palette";'),
    ("palette matches any word instead of every word", S, 'return words.every((word) => text.includes(word)) ? [index] : [];', 'return words.length === 0 || words.some((word) => text.includes(word)) ? [index] : [];'),
    ("conversation cycling stops at the end", S, 'return items[(index + step + items.length) % items.length];', 'return items[index + step];'),
    ("key=value lines truncated at later equals signs", F, 'pairs[line.slice(0, index).trim()] = line.slice(index + 1);', 'pairs[line.slice(0, index).trim()] = line.slice(index + 1).split("=")[0] ?? "";'),
    ("lines without a key accepted", F, 'if (index <= 0) throw', 'if (index < 0) throw'),
    ("uncertain requests look safe", F, 'Check the affected conversation or setting before trying again.", tone: "bad" };', 'Check the affected conversation or setting before trying again.", tone: "ok" };'),
    ("stale known gaps tolerated", P, 'if (stale.length > 0) throw', 'if (false) throw'),
    ("new gaps tolerated", P, 'if (unlisted.length > 0) throw', 'if (false) throw'),
    ("surfaces allowed at a less accessible tier", P, 'TIERS.indexOf(tier) > TIERS.indexOf(unit.tier)', 'false'),
    ("misspelled surfaces accepted", P, 'if (!referenced.has(key)) throw', 'if (false) throw'),
    ("partial field coverage counted as covered", P, 'if (tier === undefined) { covered = false; continue; }', 'if (tier === undefined) continue;'),
    ("removed terminal routes linger", P, 'if (!seen.has(path)) throw', 'if (false) throw'),
]

if __name__ == "__main__":
    sys.exit(run(MUTANTS, ["tests/browser_chat.test.ts", "tests/browser_workspace.test.ts", "tests/browser_settings.test.ts", "tests/browser_parity.test.ts"]))
