#!/usr/bin/env python3
"""Regression mutations for the shared generation lifecycle."""
import sys
from mutation import run

TESTS = ['tests/heartbeat_loop.test.ts', 'tests/autonomy_in_process.test.ts', 'tests/generic_loop.test.ts', 'tests/tool_loop.test.ts']

MUTANTS = [('send: the tag is first-wins, so a reconsidered message never replaces the draft',
  'src/autonomy/heartbeat_loop.ts',
  'if (message !== undefined) {',
  'if (message !== undefined && result.sendMessageText === undefined) {'),
 ('send: successful tool messages are discarded',
  'src/autonomy/heartbeat_loop.ts',
  'const sent = captured.filter((tool) => !tool.isError)',
  'const sent = captured.filter((tool) => tool.isError)'),
 ('send: the tag wins over the tool call in the same round',
  'src/autonomy/heartbeat_loop.ts',
  'captureToolSendMessage(sent) ?? extractSendMessage(text)',
  'extractSendMessage(text) ?? captureToolSendMessage(sent)'),
 ('send: the tool-call sink is dropped entirely',
  'src/autonomy/heartbeat_loop.ts',
  'const message = captureToolSendMessage(sent) ?? extractSendMessage(text);',
  'const message = extractSendMessage(text);'),
 ('send: the tag sink is dropped entirely',
  'src/autonomy/heartbeat_loop.ts',
  'captureToolSendMessage(sent) ?? extractSendMessage(text)',
  'captureToolSendMessage(sent)'),
 ('send: `content` is ignored when a response carries no blocks',
  'src/llm/providers/generic_loop.ts',
  'if (this.text === "") this.text = event.content;',
  'if (this.text === "") this.text = "";'),
 ("thinking: the message's reasoning never leaves the loop",
  'src/autonomy/heartbeat_loop.ts',
  '  return result;',
  '  return { ...result, thinking: [] };'),
 ("thinking: the last round's reasoning is paired with the message instead of its own",
  'src/autonomy/heartbeat_loop.ts',
  '    observe(response.content_blocks);',
  '    observe(response.content_blocks);\n    result.thinking = thinkingOf(response.content_blocks);'),
 ('thinking: an image-only tick loses the reasoning that chose the image',
  'src/autonomy/heartbeat_loop.ts',
  '      result.thinking = thinkingOf(response.content_blocks);',
  '      result.thinking = [];'),
 ('images: a generated image is dropped instead of riding out on the message',
  'src/autonomy/heartbeat_loop.ts',
  '        const ref = generatedImageRef(result.value);\n        if (ref !== undefined) images.push(ref);',
  '        void result;'),
 ('images: a failed generate_image still contributes a reference',
  'src/autonomy/heartbeat_loop.ts',
  '      if (!isError && name === "generate_image") {',
  '      if (name === "generate_image") {'),
 ('budget: the cap ends the loop instead of buying a wrap-up window',
  'src/autonomy/heartbeat_loop.ts',
  'if (action === "break" || iteration >= normalCap + deps.wrapUpGrace)',
  'if (action === "break" || action === "nudge" || iteration >= normalCap + deps.wrapUpGrace)'),
 ('budget: the grace rounds are not added, so the nudge is never answered',
  'src/autonomy/heartbeat_loop.ts',
  'iteration >= normalCap + deps.wrapUpGrace',
  'iteration >= normalCap'),
 ('budget: the nudge is spent again on every grace round',
  'src/autonomy/heartbeat_loop.ts',
  '      wrapUpNudged = true;',
  '      wrapUpNudged = false;'),
 ('budget: the nudge text is never appended, so the model is not told to wrap up',
  'src/autonomy/heartbeat_loop.ts',
  'appendWrapUpNudge(call.messages);',
  'void call;'),
 ('budget: the deadline is ignored, so a slow tick runs to the round cap',
  'src/autonomy/heartbeat_loop.ts',
  'budgetDecision(clock() >= deadline,',
  'budgetDecision(false,'),
 ('budget: the round cap is ignored, so only the deadline ever stops a tick',
  'src/autonomy/heartbeat_loop.ts',
  'iteration >= normalCap, deps.wrapUpGrace',
  'false, deps.wrapUpGrace'),
 ('budget: an absent cap is treated as zero rounds rather than unlimited',
  'src/autonomy/heartbeat_loop.ts',
  'deps.maxToolIterations ?? Number.POSITIVE_INFINITY',
  'deps.maxToolIterations ?? 0'),
 ('rounds: a response that does not finish on tool_use still dispatches',
  'src/engine/tool_loop.ts',
  'uses.length === 0 || driver.finishReason(turn) !== "tool_use"',
  'uses.length === 0'),
 ('rounds: the loop keeps calling after the model has finished',
  'src/engine/tool_loop.ts',
  'return { stop: "model_done", lastTurn: turn };',
  'await driver.callModel(); return { stop: "model_done", lastTurn: turn };'),
 ('rounds: a failed model call is treated as an empty round rather than the end',
  'src/autonomy/heartbeat_loop.ts',
  'result.failedRound = iteration;\n    } else if',
  'result.failedRound = undefined;\n    } else if'),
 ('rounds: every call is labelled a first call, so the ledger loses the loop',
  'src/autonomy/in_process.ts',
  'round++ === 0 ? "heartbeat" : "heartbeat_tool_loop"',
  '"heartbeat"'),
 ('rounds: the assistant turn is never appended, so the next round is malformed',
  'src/llm/providers/generic_loop.ts',
  '    pushAssistantBlocks(this.req, turn.blocks);',
  '    void turn;'),
 ('rounds: the tool results are never appended to the request',
  'src/llm/providers/generic_loop.ts',
  '    this.req.messages.push({ role: "user", content: blocks });',
  '    void blocks;'),
 ('rounds: the transcript is written before dispatch, so it carries no outputs',
  'src/autonomy/heartbeat_loop.ts',
  '      captured,',
  '      captured: [],'),
 ('heartbeat tools: set_next_wake writes a second ring-buffer line',
  'src/autonomy/heartbeat_loop.ts',
  '    if (name !== "set_next_wake" || isError) deps.note(`Tool: ${name} → ${truncateSummary(output, 80)}`);',
  '    deps.note(`Tool: ${name} → ${truncateSummary(output, 80)}`);'),
 ('heartbeat tools: a refused set_next_wake leaves no ring-buffer line',
  'src/autonomy/heartbeat_loop.ts',
  'name !== "set_next_wake" || isError',
  'name !== "set_next_wake"'),
 ('heartbeat tools: sendMessage falls through and the model is told it is unimplemented',
  'src/autonomy/heartbeat_loop.ts',
  '    if (isSendMessageTool(name)) {',
  '    if (false as boolean) {'),
 ('tools: the tick declares a tool of its own, so its prefix never matches the one chat cached',
  'src/autonomy/heartbeat_loop.ts',
  '  const result: HeartbeatLoopResult = { sendMessageText: undefined, images: [] };',
  '  request = { ...request, tools: [...(request.tools ?? []), '
  '{ name: "send_message", description: "Send a message.", input_schema: { type: "object" } }] };\n'
  '  const result: HeartbeatLoopResult = { sendMessageText: undefined, images: [] };'),
 ('heartbeat tools: a tool failure is reported to the model as a success',
  'src/autonomy/heartbeat_loop.ts',
  '      isError = result.isError;',
  '      isError = false;'),
 ('rounds: results come back out of order',
  'src/llm/providers/generic_loop.ts',
  '    const blocks = this.pendingResults;',
  '    const blocks = [...this.pendingResults].reverse();'),
 ('tools: the executed block is dropped, losing attached media',
  'src/autonomy/heartbeat_loop.ts',
  '    results.push(\n'
  '      block ?? { type: "tool_result", tool_use_id: id, content: output, is_error: isError },\n'
  '    );',
  '    results.push({ type: "tool_result", tool_use_id: id, content: output, is_error: isError });')]

if __name__ == "__main__":
    sys.exit(run(MUTANTS, TESTS))
