// Generated by scripts/contract_validators.ts. Do not edit.
import type { WebLogin } from "../protocol/WebLogin.ts";
export declare function validWebLogin(value: unknown): value is WebLogin;
import type { WebSessionInfo } from "../protocol/WebSessionInfo.ts";
export declare function validWebSession(value: unknown): value is WebSessionInfo;
import type { WebProblem } from "../protocol/WebProblem.ts";
export declare function validWebProblem(value: unknown): value is WebProblem;
import type { WebArchiveExport } from "../protocol/WebArchiveExport.ts";
export declare function validWebArchiveExport(value: unknown): value is WebArchiveExport;
import type { WebArchiveInfo } from "../protocol/WebArchiveInfo.ts";
export declare function validWebArchiveInfo(value: unknown): value is WebArchiveInfo;
import type { WebArchiveList } from "../protocol/WebArchiveList.ts";
export declare function validWebArchiveList(value: unknown): value is WebArchiveList;
import type { WebRequestInfo } from "../protocol/WebRequestInfo.ts";
export declare function validWebRequestInfo(value: unknown): value is WebRequestInfo;
import type { WebRequestList } from "../protocol/WebRequestList.ts";
export declare function validWebRequestList(value: unknown): value is WebRequestList;
