// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A base64-encoded image uploaded by the client.
 */
export type ImageUpload = { filename: string, 
/**
 * Base64-encoded image file bytes.
 */
data: string, 
/**
 * Declared media type (e.g. `image/png`). Optional: bridges whose source
 * protocol carries a media type but no reliable filename extension
 * (Matrix `info.mimetype`) should set it. The daemon also sniffs magic
 * bytes, so this is a fallback, not a requirement.
 */
mime_type?: string | null, };
