// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reference to an image file.
 */
export type ImageRef = { path: string, caption: string | null, 
/**
 * Base64-encoded image data for wire transfer. Stripped on disk storage.
 */
data?: string | null, };
