// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentBlock } from "./ContentBlock";
import type { ImageRef } from "./ImageRef";
import type { MessageAlternative } from "./MessageAlternative";
import type { MessageOrigin } from "./MessageOrigin";
import type { Role } from "./Role";

/**
 * A chat message. One shape everywhere — no polymorphism.
 *
 * `content_blocks` is the canonical content representation.
 * `content` is a derived convenience field (human-readable text summary).
 * On disk, only `content_blocks` is stored; `content` is derived on load.
 */
export type Message = { msg_id: string, role: Role, content: string, images: Array<ImageRef>, content_blocks: Array<ContentBlock>, alt_index: number | null, alt_count: number | null, alternatives?: Array<MessageAlternative>, timestamp: string, 
/**
 * Provider key that minted this message's content (e.g. `"anthropic"`,
 * `"openrouter-anthropic"`). Opaque thinking data — `thinking`
 * signatures and `redacted_thinking` blobs — is bound to its minting
 * provider and is not portable across a provider switch; the replay path
 * uses this to drop blocks the active provider cannot interpret. `None`
 * for messages persisted before provenance tracking, or for messages
 * (user turns, system recaps) that carry no provider-bound data.
 */
provider_key?: string | null, 
/**
 * Model id that minted this message's content (e.g. `"claude-opus-4-6"`,
 * `"anthropic/claude-opus-4.6"`), in the same vocabulary as the usage
 * ledger. Unlike [`Message::provider_key`] (which drives thinking-replay
 * portability), this is pure provenance: it lets history tooling
 * attribute a stored turn to the model that generated it. `None` for
 * messages persisted before model provenance tracking and for messages
 * no model minted (user turns, system recaps).
 */
model?: string | null, 
/**
 * How this message entered the conversation. Currently only
 * `Some(Autonomous)` is persisted (heartbeat `<sendMessage>` output);
 * compaction's deep-idle archive uses it to keep unanswered autonomous
 * messages visible across an archive boundary.
 */
origin?: MessageOrigin | null, };
