// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentBlock } from "./ContentBlock";
import type { ImageRef } from "./ImageRef";

/**
 * Stored alternate body for a regenerated assistant message.
 *
 * `Message` keeps the currently selected alternative in its top-level
 * `content`/`content_blocks` fields so existing clients and prompt assembly
 * keep reading the active response. `alternatives` stores every selectable
 * candidate, including the active one.
 */
export type MessageAlternative = { content: string, images: Array<ImageRef>, content_blocks: Array<ContentBlock>, timestamp: string, 
/**
 * Provider key that minted this alternative's content. A regenerated
 * assistant body can be produced under a different provider than the
 * original message or a sibling alternative, so each alternative carries
 * its own provenance rather than inheriting the single
 * [`Message::provider_key`]. The replay portability filter uses this to
 * drop opaque thinking data the active provider cannot interpret. `None`
 * for alternatives persisted before per-alternative provenance tracking,
 * in which case callers fall back to [`Message::provider_key`].
 */
provider_key?: string | null, 
/**
 * Model id that minted this alternative's content. Like
 * [`MessageAlternative::provider_key`], each alternative carries its own
 * provenance because regenerated bodies can come from different models.
 * `None` for alternatives persisted before model provenance tracking, in
 * which case callers fall back to [`Message::model`].
 */
model?: string | null, };
