// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A configured usage budget crossed one or more warning thresholds.
 */
export type UsageWarning = { rid?: string | null, 
/**
 * Configured budget name.
 */
budget: string, 
/**
 * Human-readable warning text.
 */
message: string, 
/**
 * Current spend for the budget window.
 */
current_cost: number, 
/**
 * Configured budget limit.
 */
cost_limit: number, 
/**
 * Fraction used, e.g. 0.8 for 80%.
 */
percent_used: number, 
/**
 * Newly crossed warning thresholds, as fractions.
 */
crossed_warn_at: Array<number>, 
/**
 * Calendar period name.
 */
period: string, 
/**
 * RFC3339 period start.
 */
period_start: string, 
/**
 * RFC3339 reset/end time.
 */
reset_at: string, 
/**
 * `reset_at` rendered in the daemon's local time as `YYYY-MM-DD HH:MM AM|PM`.
 * Clients that surface this string verbatim should prefer it over `reset_at`
 * (which is UTC); the structured `reset_at` stays for machine consumers.
 */
reset_at_display: string, 
/**
 * `"pace"` when the warning is about a budget's pace allowance rather than
 * its period cap; absent for the cap itself. The cost, period, and window
 * fields always describe whichever limit tripped, so a client that ignores
 * this still renders correct numbers — it just can't tell the two apart.
 */
scope?: string | null, };
