import { defaultAppConfig, defaultMatrixConfig, parseAppConfig } from "./app.ts";
import { configSchema } from "./schema.ts";
import { serializeConfigValue } from "./serialize.ts";
import { parseConfigPath, publicConfig, valueAt } from "./surface.ts";

export const CONFIG_EXAMPLES = [
  { title: "Provider and a qualified model override", text: `[providers.anthropic]
api_key_env = "ANTHROPIC_API_KEY"
cache_ttl = "1h"

[chat]
model = "anthropic:claude-opus-4-8"

[chat."anthropic:claude-opus-4-8"]
max_output_tokens = 16384
` },
  { title: "Background work and a budget", text: `[heartbeat]
enabled = true
interval = "6h"
min_interval = "4h"

[compaction]
idle_after = "50m"
min_turns = 4
keep_recent_turns = 0

[[budgets]]
name = "weekly"
cost_usd = 15
period = "week"
pace_period = "day"
warn_fractions = [0.9, 1.0]
limit_action = "block"
allow_compaction = true
` },
  { title: "Notifications and an MCP server", text: `[notifications]
via = "ntfy"
url = "https://ntfy.example.invalid"
topic = "your-private-topic"
token_env = "NTFY_TOKEN"
events = ["message_complete", "error"]
min_generation_duration = "10s"

[mcp.reference]
url = "https://mcp.example.invalid"
` },
  { title: "A character override", text: `[chat]
model = "anthropic:claude-opus-4-8"

[heartbeat]
enabled = false

[[budgets]]
name = "this-character"
cost_usd = 5
period = "day"
limit_action = "block"
` },
] as const;

export function renderConfigReference(): string {
  const defaults = publicConfig(serializeConfigValue(defaultAppConfig()) as Record<string, unknown>);
  const sample = parseAppConfig({ usage: { budgets: [{ cost_usd: 0 }] }, subagents: { "<name>": { description: "", prompt: "" } } });
  const instances = "ok" in sample ? publicConfig(serializeConfigValue(sample.ok) as Record<string, unknown>) : {};
  defaults.matrix = publicConfig({ connections: { matrix: serializeConfigValue(defaultMatrixConfig()) } }).matrix;
  const entries = configSchema({ instancesAt: () => [] });
  const escape = (text: string): string => text.replaceAll("|", "\\|");
  const lines = [
    "# Configuration reference", "",
    "Generated by `bun run config:reference` from the configuration schema. Do not edit the option table by hand.", "",
    "Set only the options you use. The main config loads first, followed by ordered `include` files, sorted `conf.d/*.toml`, and the active character's `characters/<name>/config.toml`. Tables merge; arrays replace. All options below support global and character scopes; startup-owned settings require a daemon restart.", "",
    "Use quoted TOML segments for identities containing punctuation, including in CLI keys: `shore config get 'chat.\"provider:model.v1\".max_output_tokens'`. `<name>`, `<index>`, and `<provider:model_id>` below are schema templates, not literal configuration names.", "",
    "Durations use strings such as `50m` or `6h`. Integer limits name their units; `u32` accepts 0 through 4,294,967,295. `max_tool_rounds` must be positive. A zero tool timeout disables the timeout, and a zero archive interval disables that trigger. Cache keepalive intervals and idle limits must be positive; use `cache_keepalive = \"off\"` to disable pings. Warning fractions are fractions, not percentages.", "",
    "Chat selection uses a thread pin, character preference, global preference, then `chat.model`. Each background task uses its own `model`, otherwise the active chat model. Subagents use their own model, then `subagents.model`, then the active chat model. Saved sampling settings retain their global/character/model precedence and separate subagent scopes.", "",
    "Model settings apply only where the SDK supports them. `openrouter_routing` is an opaque vendor routing object; `gemini_thinking_mode` selects auto inference, token budgets, or named levels; `zai_clear_reasoning` applies to Z.AI. Cache controls require an SDK with explicit cache support. `shore model setting` reports applicability for the selected model.", "",
    "| Setting | Type | Built-in default | Restart | Meaning |",
    "| --- | --- | --- | --- | --- |",
  ];
  for (const row of entries) {
    if (row.kind === "table" && !row.key.endsWith("openrouter_routing")) continue;
    const path = parseConfigPath(row.key);
    let value = valueAt(defaults, path);
    if (path[0] === "budgets" && path.at(-1) !== "cost_usd" || path[0] === "subagents" && !["description", "prompt"].includes(path.at(-1) ?? "")) value ??= valueAt(instances, path.map((part) => part === "<index>" ? "0" : part));
    if (path[0] === "providers" && path.length === 3) {
      if (path[2] === "enabled") value = true;
      if (path[2] === "discover") value = false;
      if (path[2] === "keys" || path[2] === "ignore_models") value = [];
    }
    const fallback = value === undefined || value === null ? "unset / instance-specific" : `\`${JSON.stringify(value)}\``;
    lines.push(`| \`${row.key}\` | ${escape(row.type)} | ${escape(fallback)} | ${row.restart_required ? "yes" : "no"} | ${escape(row.description ?? "")} |`);
  }
  for (const example of CONFIG_EXAMPLES) lines.push("", `## ${example.title}`, "", "```toml", example.text.trimEnd(), "```", "");
  lines.push("", "The character example belongs in `characters/<name>/config.toml`. Its budget array replaces inherited budgets and automatically scopes unqualified entries to that character.", "");
  lines.push("", "Legacy spellings are accepted with source-specific warnings during the compatibility window. They are listed separately by `shore config keys --json`; generated examples and normal completion use canonical names. Run `shore config migrate --config /path/config.toml --data-dir /path/data` locally to review a redacted plan. Add `--write` to apply it while the daemon is stopped. See [migration details](CONFIG_REDESIGN_MIGRATION.md).", "");
  return lines.join("\n");
}
