// Generated by scripts/contract_validators.ts. Do not edit.
import type { OperationInput, OperationName, OperationResult } from "./types.ts";
export interface ContractError { keyword: string; instancePath: string; params: Record<string, unknown>; message?: string }
export interface ContractValidator { (value: unknown): boolean; errors?: ContractError[] | null }
export declare function operationValidator(kind: "input" | "output", name: string): ContractValidator | undefined;
export declare function isOperationName(name: string): name is OperationName;
export declare function validOperationInput<N extends OperationName>(name: N, value: unknown): value is OperationInput<N>;
export declare function validOperationResult<N extends OperationName>(name: N, value: unknown): value is OperationResult<N>;
