/**
 * Parity for `AppConfig` — the whole `config.toml` schema.
 *
 * Replays `tests/config_fixtures/app_parity.json`, generated by driving the
 * real `shore_common::config::app` from `main`.
 *
 * Every parse case is recorded through both of the Rust's deserialization
 * paths. `src/config/app.ts` implements the **table** path, which is the only
 * one production takes, so that is what the assertions compare against — and
 * the two cases where the paths disagree are asserted to give the *table*
 * answer specifically, so a future rewrite toward document order fails here
 * rather than silently disagreeing with the daemon.
 */

import { describe, expect, test } from "bun:test";

import fixture from "./config_fixtures/app_parity.json" with { type: "json" };

import {
  anyToolEnabled,
  budgetPaceAction,
  budgetPaceWarnAt,
  budgetPeriodRank,
  defaultAppConfig,
  defaultToolsConfig,
  mapKeysInOrder,
  normalizeDeprecatedAliases,
  numDaysFromMonday,
  parseAppConfig,
  parseThinkingReplay,
  resolveBackgroundModelName,
  resolveDisplayName,
  resultCharsFor,
  subagentEnabled,
  timeoutFor,
  toolEnabled,
  toolPatternMatches,
  validateCompaction,
  type AppConfig,
  type BackgroundTask,
  type BudgetWeekday,
  type DefaultsConfig,
  type ToolsConfig,
  type UsageBudgetPeriod,
} from "../src/config/app.ts";
import { ConfigDuration } from "../src/config/duration.ts";

// ── Canonicalizing to the serde JSON the fixture holds ──────────────────

/**
 * Render a parsed value the way `serde_json::to_value` rendered the Rust one.
 *
 * `ConfigDuration` serializes through its `Display`, `Option::None` becomes
 * `null`, and a `BTreeMap` becomes an object. The map conversion walks the
 * `Map` in *its own* iteration order rather than sorting again — so if the
 * parser built it in the wrong order, {@link mapOrderOf} catches it below
 * instead of this function quietly repairing it.
 */
function canonical(value: unknown): unknown {
  if (value === undefined) return null;
  if (value instanceof ConfigDuration) return value.toString();
  if (value instanceof Map) {
    const out: Record<string, unknown> = {};
    for (const [k, v] of value) out[k] = canonical(v);
    return out;
  }
  if (Array.isArray(value)) return value.map(canonical);
  if (typeof value === "object" && value !== null) {
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(value)) out[k] = canonical(v);
    return out;
  }
  return value;
}

/** Every map-valued path in a parsed config, as `[label, keys-in-order]`. */
function mapOrderOf(config: AppConfig): [string, string[]][] {
  const out: [string, string[]][] = [
    ["subagents", [...config.subagents.keys()]],
    ["mcp", [...config.mcp.keys()]],
    ["tools.config", [...config.tools.config.keys()]],
  ];
  for (const [name, server] of config.mcp) {
    out.push([`mcp.${name}.env`, [...server.env.keys()]]);
  }
  return out;
}

function parseToml(src: string): unknown {
  return Bun.TOML.parse(src);
}

// ── Fields the fixture predates ─────────────────────────────────────────

/**
 * `[daemon]` keys the fixture has and the schema no longer does.
 *
 * `unsafe_allow_remote_access` and `allowed_hosts` were deleted when every
 * client started presenting a token: an address is not a credential, and a flag
 * asking you to acknowledge a risk is worse than not having the risk. The
 * fixture is a frozen capture of a Rust that still had them, and it cannot be
 * regenerated — so the *expectation* is trimmed here, the mirror of what
 * {@link withoutAddedBudgetFields} does for keys the fixture never had.
 *
 * Asserted below to really be present in the fixture, so this cannot quietly
 * start hiding a key that was supposed to survive.
 */
const DAEMON_FIELDS_REMOVED_SINCE = ["unsafe_allow_remote_access", "allowed_hosts"] as const;

/** The fixture's expected value with the deleted `[daemon]` keys dropped. */
function withoutRemovedDaemonFields(value: unknown): unknown {
  const daemon = (value as { daemon?: unknown } | null)?.daemon;
  if (typeof daemon !== "object" || daemon === null) return value;
  const copy = { ...(daemon as Record<string, unknown>) };
  for (const key of DAEMON_FIELDS_REMOVED_SINCE) delete copy[key];
  return { ...(value as object), daemon: copy };
}

/**
 * `[[usage.budgets]]` keys added after the fixture was frozen (#35).
 *
 * The fixture is a capture of a Rust that no longer exists, so it cannot grow
 * a field — and regenerating it is not possible. The technique is the one
 * `tool_surface` used for the frozen export strings: **cut the new keys back
 * out of our own answer before comparing**, so every field the Rust really
 * wrote stays compared literally, and only the additions are exempt.
 *
 * Both are asserted below to be genuinely absent from the fixture, so this
 * cannot quietly start hiding a field the Rust did have.
 */
const BUDGET_FIELDS_ADDED_SINCE = ["warn_action", "pace_warn_action"] as const;

/** The same value with the added keys dropped from every budget. */
function withoutAddedBudgetFields(value: unknown): unknown {
  const budgets = (value as { usage?: { budgets?: unknown } } | null)?.usage?.budgets;
  if (!Array.isArray(budgets)) return value;
  return {
    ...(value as object),
    usage: {
      ...(value as { usage: object }).usage,
      budgets: budgets.map((b) => {
        const copy = { ...(b as Record<string, unknown>) };
        for (const key of BUDGET_FIELDS_ADDED_SINCE) delete copy[key];
        return copy;
      }),
    },
  };
}

/**
 * The Rust's field count for `UsageBudgetConfig`, which the positional-array
 * error message interpolates and which the added keys move.
 */
const RUST_BUDGET_FIELD_COUNT = 18;

function withRustBudgetFieldCount(err: string): string {
  return err.replace(
    `UsageBudgetConfig with ${RUST_BUDGET_FIELD_COUNT + BUDGET_FIELDS_ADDED_SINCE.length} elements`,
    `UsageBudgetConfig with ${RUST_BUDGET_FIELD_COUNT} elements`,
  );
}

// ── Cases the TypeScript deliberately cannot match ──────────────────────

/**
 * Cases whose Rust answer depends on something `Bun.TOML.parse` destroys — or
 * refuses — before `app.ts` runs. Each is asserted explicitly below; they are
 * skipped in the bulk replay rather than expected to pass. The fixture header
 * spells out all four categories.
 */
/**
 * The one case whose Rust answer this schema deliberately no longer gives.
 *
 * Its TOML *sets* `unsafe_allow_remote_access` and `allowed_hosts`, which the
 * Rust parsed and this schema now rejects as unknown fields. Trimming the
 * expectation is not enough and would be dishonest — the outcome changed from
 * a parse to an error, not just its contents. Skipped in the bulk replay and
 * asserted on its own below, where the new behaviour is the subject.
 */
const DELIBERATELY_DIVERGENT = "the daemon section";

const BUN_CANNOT_SEE = new Set([
  // Datetime literals: rejected outright by Bun.
  "datetime where a string is expected",
  // Integer vs float: `20000.0` and `1e3` arrive as plain JS numbers.
  "a float that happens to be whole is still a float",
  "exponent notation is a float too",
  // u64 past 2^53.
  "u64 fields hold values a double cannot",
  // Nested array literals: rejected outright by Bun.
  "seq: UsageBudgetConfig, at its minimum",
  "a required field supplied positionally",
]);

// ── The fixture itself ──────────────────────────────────────────────────

describe("the fixture is real", () => {
  test("it was frozen, and says so", () => {
    expect(fixture._header.join(" ")).toContain("nothing");
    expect(fixture._header.join(" ")).toContain("regenerates it");
  });

  test("it names `main` as its source, not a worktree", () => {
    expect(fixture._header.join(" ")).toContain("GENERATED from `main`");
  });

  test("the trimmed daemon fields really are ones it had", () => {
    // The trim above is only honest if the fixture genuinely carries these.
    // If one ever stops appearing, the replay is hiding a real disagreement
    // rather than a key this schema deliberately dropped.
    const daemon = (fixture.defaults as { daemon: Record<string, unknown> }).daemon;
    for (const key of DAEMON_FIELDS_REMOVED_SINCE) {
      expect(Object.keys(daemon)).toContain(key);
    }
  });

  test("the exempted budget fields really are ones it never had", () => {
    // The exemption above is only honest if these keys are absent from every
    // budget the Rust recorded. If one ever appears, the replay is hiding a
    // real disagreement rather than a field that postdates the capture.
    const text = JSON.stringify(fixture);
    for (const key of BUDGET_FIELDS_ADDED_SINCE) {
      expect(text).not.toContain(`"${key}"`);
    }
    expect(text).toContain(`UsageBudgetConfig with ${RUST_BUDGET_FIELD_COUNT} elements`);
  });

  test("it records both parse paths, and they genuinely differ somewhere", () => {
    // A fixture whose two columns were identical everywhere would pass against
    // a port that walked the document instead of the table.
    const disagreements = fixture.parse.filter(
      (c) => "doc_err" in c && c.doc_err !== c.table_err,
    );
    expect(disagreements.length).toBeGreaterThan(0);
  });
});

// ── Defaults ────────────────────────────────────────────────────────────

describe("AppConfig::default", () => {
  test("every default matches the Rust's", () => {
    expect(canonical(defaultAppConfig())).toEqual(withoutRemovedDaemonFields(fixture.defaults));
  });

  test("ToolsConfig::default matches on its own", () => {
    expect(canonical(defaultToolsConfig())).toEqual(fixture.tools_defaults);
  });

  test("an empty document parses to exactly the defaults", () => {
    const parsed = parseAppConfig(parseToml(""));
    if ("err" in parsed) throw new Error(parsed.err);
    expect(canonical(parsed.ok)).toEqual(canonical(defaultAppConfig()));
  });
});

// ── Parsing ─────────────────────────────────────────────────────────────

describe("parsing config.toml", () => {
  for (const c of fixture.parse) {
    if (BUN_CANNOT_SEE.has(c.name) || c.name === DELIBERATELY_DIVERGENT) continue;

    test(c.name, () => {
      const parsed = parseAppConfig(parseToml(c.toml));

      // Three fixture shapes, all reduced to "what does the table path say":
      // `ok` (both paths agreed), `doc_err`/`table_err` (both failed, possibly
      // differently), and `doc`/`table` (the paths reached different outcomes).
      const want: { ok: unknown } | { err: string } =
        "ok" in c
          ? { ok: c.ok }
          : "table" in c
            ? (c.table as { ok: unknown } | { err: string })
            : { err: c.table_err as string };

      if ("err" in want) {
        if ("ok" in parsed) throw new Error("expected a parse error, got a config");
        expect(withRustBudgetFieldCount(parsed.err)).toBe(want.err);
      } else {
        if ("err" in parsed) throw new Error(`expected a parse, got: ${parsed.err}`);
        expect(withoutAddedBudgetFields(canonical(parsed.ok))).toEqual(
          withoutRemovedDaemonFields(want.ok),
        );
      }
    });
  }

  test("a config still setting the deleted [daemon] keys is now rejected", () => {
    // The fixture's `the daemon section` case, asserted as what it became. An
    // old config does not silently keep an inert key: it fails at load, naming
    // the key, which is the only way someone learns their allowlist stopped
    // being consulted. `addr` is all that is left of the section.
    const c = fixture.parse.find((x) => x.name === DELIBERATELY_DIVERGENT);
    expect(c).toBeDefined();

    const parsed = parseAppConfig(parseToml(c!.toml));
    expect("err" in parsed).toBe(true);
    expect((parsed as { err: string }).err).toBe(
      "unknown field `allowed_hosts`, expected `addr`",
    );

    // And the surviving key still parses on its own.
    const ok = parseAppConfig(parseToml(`[daemon]\naddr = "0.0.0.0:9999"\n`));
    if ("err" in ok) throw new Error(ok.err);
    expect(ok.ok.daemon).toEqual({ addr: "0.0.0.0:9999" });
  });

  test("map-valued sections are built in code point order, not document order", () => {
    // `subagents` and `mcp` decide the order tools reach the model, which is
    // the head of the prompt cache key. A `Record` built from document order
    // would pass every value assertion above and still reorder the cache.
    const src =
      '[subagents.zed]\ndescription = "z"\nprompt = "p"\n\n' +
      '[subagents."\u{1F3B5}drum"]\ndescription = "d"\nprompt = "p"\n\n' +
      '[subagents."\u{FB00}ute"]\ndescription = "f"\nprompt = "p"\n\n' +
      '[mcp.zebra]\ncommand = "z"\nenv = { ZED = "1", ABLE = "2" }\n\n' +
      '[mcp.alpha]\ncommand = "a"\n\n' +
      "[tools.config.zoom]\nmax_result_chars = 1\n\n" +
      "[tools.config.abacus]\nmax_result_chars = 2\n";
    const parsed = parseAppConfig(parseToml(src));
    if ("err" in parsed) throw new Error(parsed.err);

    expect(Object.fromEntries(mapOrderOf(parsed.ok))).toEqual({
      // `ﬀ` is U+FB00 and `🎵` is U+1F3B5, so code point order puts the
      // emoji last where a UTF-16 sort would put it first.
      subagents: ["zed", "\u{FB00}ute", "\u{1F3B5}drum"],
      mcp: ["alpha", "zebra"],
      "tools.config": ["abacus", "zoom"],
      "mcp.alpha.env": [],
      "mcp.zebra.env": ["ABLE", "ZED"],
    });
  });
});

describe("the two parse paths, where they disagree", () => {
  /** A fixture case that failed on *both* paths, with both messages. */
  const caseNamed = (name: string): { toml: string; doc_err: string; table_err: string } => {
    const found = fixture.parse.find((c) => c.name === name);
    if (found === undefined) throw new Error(`fixture case missing: ${name}`);
    if (!("doc_err" in found) || !("table_err" in found)) {
      throw new Error(`fixture case is not a two-column error: ${name}`);
    }
    return found as { toml: string; doc_err: string; table_err: string };
  };

  test("two unknown keys: the code-point-smallest is reported, not the first written", () => {
    const c = caseNamed(
      "two unknown top-level keys: the document reports the first written, " +
        "the table reports the code-point-smallest",
    );
    const parsed = parseAppConfig(parseToml(c.toml));
    if ("ok" in parsed) throw new Error("expected a parse error");
    expect(parsed.err).toContain("`aaa_unknown`");
    expect(parsed.err).not.toContain("`zzz_unknown`");
    expect(parsed.err).toBe(c.table_err);
    expect(parsed.err).not.toBe(c.doc_err);
  });

  test("a bad type sorting before an unknown key wins the race", () => {
    const c = caseNamed("an unknown key and a bad type: which is reported depends on the path");
    const parsed = parseAppConfig(parseToml(c.toml));
    if ("ok" in parsed) throw new Error("expected a parse error");
    // serde descends into `autonomy` first and never reaches `zzz_unknown`.
    expect(parsed.err).toBe('invalid type: string "yes", expected a boolean');
    expect(parsed.err).toBe(c.table_err);
    expect(parsed.err).not.toBe(c.doc_err);
  });
});

describe("distinctions Bun's TOML parser destroys", () => {
  test("a datetime never reaches app.ts — Bun rejects the document", () => {
    const c = fixture.parse.find((x) => x.name === "datetime where a string is expected");
    if (c === undefined) throw new Error("fixture case missing");
    // The Rust's table path accepts it as a string; its document path rejects
    // it. Neither is reachable, because the parse fails first.
    expect(() => parseToml(c.toml)).toThrow();
    const table = c.table?.ok as { defaults: { model: string } } | undefined;
    if (table === undefined) throw new Error("expected a table-path success");
    expect(table.defaults.model).toBe("1979-05-27T07:32:00Z");
    expect(c.doc?.err).toBe("invalid type: map, expected a string");
  });

  for (const name of ["a float that happens to be whole is still a float", "exponent notation is a float too"]) {
    test(`${name} — accepted here, rejected in Rust`, () => {
      const c = fixture.parse.find((x) => x.name === name);
      if (c === undefined) throw new Error("fixture case missing");
      expect(c.table_err).toContain("expected usize");

      const parsed = parseAppConfig(parseToml(c.toml));
      if ("err" in parsed) throw new Error(`expected the looser parse, got: ${parsed.err}`);
      // Bun yields a JS number with no trace of the `.0` or the exponent.
      expect(parsed.ok.tools.max_result_chars).toBe(name.startsWith("exponent") ? 1000 : 20000);
    });
  }

  test("a nested array literal is rejected by Bun, whatever the Rust says", () => {
    // Not a value-level rejection — the whole document fails. No field in this
    // schema is a `Vec<Vec<_>>`, and `[[usage.budgets]]` is array-of-tables
    // syntax rather than a nested array, so nothing real reaches it. A schema
    // that later grows one would be unreadable here with no other warning.
    expect(() => parseToml("a = [[1]]")).toThrow();
    for (const name of ["seq: UsageBudgetConfig, at its minimum", "a required field supplied positionally"]) {
      const c = fixture.parse.find((x) => x.name === name);
      if (c === undefined) throw new Error(`fixture case missing: ${name}`);
      expect(() => parseToml(c.toml)).toThrow();
    }
    // Array-of-tables, which is what a real budget list uses, is fine.
    expect(() =>
      parseToml('[[usage.budgets]]\ncost_usd = 1.0\nwarn_at = [0.5]\n'),
    ).not.toThrow();
  });

  test("a u64 past 2^53 loses its last digit here and keeps it in Rust", () => {
    const c = fixture.parse.find((x) => x.name === "u64 fields hold values a double cannot");
    if (c === undefined) throw new Error("fixture case missing");
    const rust = c.ok as { advanced: { max_image_size: number } } | undefined;
    if (rust === undefined) throw new Error("expected a recorded success");
    expect(rust.advanced.max_image_size).toBe(9007199254740993);

    const parsed = parseAppConfig(parseToml(c.toml));
    if ("err" in parsed) throw new Error(parsed.err);
    expect(parsed.ok.advanced.max_image_size).toBe(9007199254740992);
  });
});

// ── ToolsConfig ─────────────────────────────────────────────────────────

describe("the tool allowlist and per-tool resolution", () => {
  for (const c of fixture.tools_queries) {
    test(c.name, () => {
      const parsed = parseAppConfig(parseToml(c.toml));
      if ("err" in parsed) throw new Error(parsed.err);
      const tools: ToolsConfig = parsed.ok.tools;

      expect(anyToolEnabled(tools)).toBe(c.any_enabled);

      for (const t of c.tools) {
        expect({
          name: t.name,
          enabled: toolEnabled(tools, t.name),
          result_chars: resultCharsFor(tools, t.name),
          timeout_ms: Number(timeoutFor(tools, t.name)?.asMillisExact() ?? NaN),
        }).toEqual({
          name: t.name,
          enabled: t.enabled,
          result_chars: t.result_chars,
          timeout_ms: t.timeout_ms ?? NaN,
        });
      }

      for (const s of c.subagents) {
        expect(subagentEnabled(tools, s.name)).toBe(s.enabled);
      }
    });
  }

  test("no deadline is `undefined`, not a zero duration", () => {
    // Distinguishing the two matters: a caller that treated a zero-millisecond
    // deadline as a deadline would cancel every tool immediately.
    const parsed = parseAppConfig(parseToml("[tools]\ntimeout = 0\n"));
    if ("err" in parsed) throw new Error(parsed.err);
    expect(timeoutFor(parsed.ok.tools, "read")).toBeUndefined();
  });
});

describe("tool_pattern_matches", () => {
  for (const c of fixture.tool_patterns) {
    test(`${JSON.stringify(c.pattern)} vs ${JSON.stringify(c.name)}`, () => {
      expect(toolPatternMatches(c.pattern, c.name)).toBe(c.matches);
    });
  }

  test("the cases cover both branches and both answers", () => {
    const globs = fixture.tool_patterns.filter((c) => c.pattern.endsWith("*"));
    const exact = fixture.tool_patterns.filter((c) => !c.pattern.endsWith("*"));
    expect(globs.some((c) => c.matches)).toBe(true);
    expect(globs.some((c) => !c.matches)).toBe(true);
    expect(exact.some((c) => c.matches)).toBe(true);
    expect(exact.some((c) => !c.matches)).toBe(true);
  });
});

// ── DefaultsConfig ──────────────────────────────────────────────────────

/** Rebuild a `DefaultsConfig` from the serde JSON the fixture recorded. */
function defaultsFromJson(json: {
  model: string | null;
  background: { model: string | null; heartbeat: string | null; compaction: string | null };
  heartbeat: string | null;
  embedding: string | null;
  image_generation: string | null;
  subagent_model: string | null;
  display_name: string | null;
  stream: boolean;
}): DefaultsConfig {
  const or = (v: string | null) => v ?? undefined;
  return {
    model: or(json.model),
    background: {
      model: or(json.background.model),
      heartbeat: or(json.background.heartbeat),
      compaction: or(json.background.compaction),
    },
    heartbeat: or(json.heartbeat),
    embedding: or(json.embedding),
    image_generation: or(json.image_generation),
    subagent_model: or(json.subagent_model),
    display_name: or(json.display_name),
    stream: json.stream,
  };
}

describe("background model resolution", () => {
  for (const c of fixture.background) {
    test(c.name, () => {
      const defaults = defaultsFromJson(c.defaults);
      for (const [task, want] of [
        ["heartbeat", c.heartbeat],
        ["compaction", c.compaction],
      ] as [BackgroundTask, string | null][]) {
        expect(resolveBackgroundModelName(defaults, task) ?? null).toBe(want);
      }
    });
  }
});

describe("normalize_deprecated_aliases", () => {
  for (const c of fixture.normalize) {
    test(c.name, () => {
      const parsed = parseAppConfig(parseToml(c.toml));
      if ("err" in parsed) throw new Error(parsed.err);

      expect(canonical(parsed.ok.defaults)).toEqual(c.before);
      normalizeDeprecatedAliases(parsed.ok.defaults);
      expect(canonical(parsed.ok.defaults)).toEqual(c.once);
      normalizeDeprecatedAliases(parsed.ok.defaults);
      expect(canonical(parsed.ok.defaults)).toEqual(c.twice);
    });
  }

  test("a case where the alias actually moves is present", () => {
    // Every case being a no-op would pass against a function body of `return`.
    const moved = fixture.normalize.filter(
      (c) => JSON.stringify(c.before) !== JSON.stringify(c.once),
    );
    expect(moved.length).toBeGreaterThan(0);
  });
});

describe("resolve_display_name", () => {
  for (const c of fixture.display_name) {
    test(c.name, () => {
      const defaults = {
        ...defaultAppConfig().defaults,
        display_name: c.display_name ?? undefined,
      };
      // $USER is injected rather than read, so the result does not depend on
      // the account running the suite.
      const env = c.user_env === null ? {} : { USER: c.user_env };
      expect(resolveDisplayName(defaults, env)).toBe(c.resolved);
    });
  }
});

// ── CompactionConfig::validate ──────────────────────────────────────────

describe("compaction validation", () => {
  for (const c of fixture.compaction_validate) {
    test(c.name, () => {
      const compaction = {
        enabled: c.compaction.enabled,
        idle_trigger: durationFrom(c.compaction.idle_trigger),
        archive_after: durationFrom(c.compaction.archive_after),
        min_turns: c.compaction.min_turns,
        max_turns: c.compaction.max_turns,
        max_context_tokens: c.compaction.max_context_tokens,
        keep_recent_turns: c.compaction.keep_recent_turns,
      };
      expect(validateCompaction(compaction) ?? null).toBe(c.err);
    });
  }

  test("the rejection names the two values that would work", () => {
    const c = fixture.compaction_validate.find((x) =>
      x.name.includes("names the two values"),
    );
    if (c === undefined || c.err === null) throw new Error("fixture case missing");
    expect(c.err).toContain("`90s`");
    expect(c.err).toContain("`91s`");
  });
});

/** Re-parse a duration out of its serialized form. */
function durationFrom(display: string): ConfigDuration {
  const parsed = ConfigDuration.parse(display);
  if ("err" in parsed) throw new Error(`${display}: ${parsed.err}`);
  return parsed.ok;
}

// ── Usage budgets ───────────────────────────────────────────────────────

describe("budget pace fallbacks", () => {
  for (const c of fixture.budget_pace) {
    test(c.name, () => {
      const parsed = parseAppConfig(parseToml(c.toml));
      if ("err" in parsed) throw new Error(parsed.err);

      expect(
        parsed.ok.usage.budgets.map((b) => ({
          pace_action: budgetPaceAction(b) as string,
          pace_warn_at: [...budgetPaceWarnAt(b)],
        })),
      ).toEqual(c.budgets);
    });
  }
});

describe("budget enum tables", () => {
  test("period ranks", () => {
    expect(
      fixture.budget_periods.map((p) => ({
        period: p.period,
        rank: budgetPeriodRank(p.period as UsageBudgetPeriod),
      })),
    ).toEqual(fixture.budget_periods);
  });

  test("weekday offsets", () => {
    expect(
      fixture.budget_weekdays.map((d) => ({
        weekday: d.weekday,
        num_days_from_monday: numDaysFromMonday(d.weekday as BudgetWeekday),
      })),
    ).toEqual(fixture.budget_weekdays);
  });

  test("every action variant round-trips through the schema", () => {
    for (const action of fixture.budget_actions) {
      const parsed = parseAppConfig(
        parseToml(`[[usage.budgets]]\ncost_usd = 1.0\nlimit = ${JSON.stringify(action)}\n`),
      );
      if ("err" in parsed) throw new Error(parsed.err);
      expect(parsed.ok.usage.budgets[0]?.limit as string | undefined).toBe(action);
    }
  });
});

// ── ThinkingReplay ──────────────────────────────────────────────────────

describe("parse_wire for replay_prior_thinking", () => {
  for (const c of fixture.thinking_replay) {
    test(JSON.stringify(c.input), () => {
      expect((parseThinkingReplay(c.input) ?? null) as string | null).toBe(c.parsed);
    });
  }

  test("the retired last_turn mode is accepted, not rejected", () => {
    // Rejecting it would stop the daemon starting on any config still
    // carrying it, which is the whole reason the branch exists.
    expect(parseThinkingReplay("last_turn")).toBe("all");
  });
});

// ── Map iteration helper ────────────────────────────────────────────────

describe("mapKeysInOrder", () => {
  test("sorts by code point, not UTF-16 code unit", () => {
    const m = new Map([
      ["\u{1F3B5}drum", 1],
      ["\u{FB00}ute", 2],
      ["zed", 3],
    ]);
    expect(mapKeysInOrder(m)).toEqual(["zed", "\u{FB00}ute", "\u{1F3B5}drum"]);
  });
});
