/**
 * Parity for `crates/daemon/src/characters.rs` — the character registry.
 *
 * Replays `tests/engine_fixtures/characters_parity.json`, generated by driving
 * the real Rust `CharacterRegistry` in a worktree at 9023b46d.
 *
 * Every case is a scripted run, not a single call, because every decision in
 * this module is about caching. The replay rebuilds the same directory tree,
 * applies the same steps in the same order, and compares the registry's
 * observable state after each one — including the `active_prompt/` directories
 * on disk, which is how "the registry prepares every character's workspace on
 * construction, refresh and reload, and nowhere else" is checked at all.
 */

import { afterEach, describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import fixture from "./engine_fixtures/characters_parity.json" with { type: "json" };

import {
  CharacterError,
  CharacterRegistry,
  EngineCharacterNotFound,
} from "../src/characters.ts";
import { loadConfig, parseConfigTable, type LoadedConfig } from "../src/config/loader.ts";
import { defaultAppConfig } from "../src/config/app.ts";
import { emptyCatalog } from "../src/config/models.ts";
import { ProviderRegistry } from "../src/config/providers.ts";
import { compareByCodePoint } from "../src/sort.ts";

// ── Fixture shape ───────────────────────────────────────────────────────

interface Step {
  op: string;
  state: { available: string[]; snapshots: string[] };
  name?: string;
  soul?: boolean;
  toml?: string;
  path?: string;
  body?: string;
  requested?: string | null;
  result?: unknown;
  summary?: {
    available_before: number;
    available_after: number;
    character_discovery_changed: boolean;
    dropped_engines: number;
  };
}

interface Scenario {
  name: string;
  /** Exactly how the generator built the tree before the first step. */
  seed: {
    global_toml: string | null;
    raw_table: boolean;
    characters: { name: string; soul: boolean }[];
  };
  steps: Step[];
}

const scenarios = fixture.scenarios as unknown as Scenario[];

// ── Harness ─────────────────────────────────────────────────────────────

const roots: string[] = [];

afterEach(() => {
  for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true });
});

function makeRoot(): string {
  const root = mkdtempSync(join(tmpdir(), "shore-characters-"));
  roots.push(root);
  return root;
}

function writeCharacter(configDir: string, name: string, soul: boolean): void {
  const dir = join(configDir, "characters", name);
  if (soul) {
    mkdirSync(join(dir, "workspace"), { recursive: true });
    writeFileSync(join(dir, "workspace", "SOUL.md"), `${name} soul`);
  } else {
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, "character.md"), `${name} legacy`);
  }
}

function isDir(path: string): boolean {
  try {
    return statSync(path).isDirectory();
  } catch {
    return false;
  }
}

/** The generator's `snapshot()`: which characters have an `active_prompt/`. */
function snapshotsOnDisk(dataDir: string): string[] {
  let entries: string[];
  try {
    entries = readdirSync(dataDir);
  } catch {
    return [];
  }
  return entries
    .filter((name) => isDir(join(dataDir, name, "active_prompt")))
    .sort(compareByCodePoint);
}

/**
 * The `none_available` message the Rust returned, verbatim.
 *
 * It cites `characters/<name>/workspace/SOUL.md` relative to the config
 * directory and says so nowhere, which is #41: it is the first error a fresh
 * install hits, from every command, and the reader's working directory is the
 * obvious wrong guess. The port resolves the path instead.
 *
 * The fixture keeps the Rust's string — that is the only thing it records —
 * and {@link withResolvedSoulPath} rewrites it into the run's absolute form
 * before comparing. The rewrite is deliberately keyed on the *exact* old
 * string, so the day the message changes again this stops matching and the
 * divergence has to be restated rather than silently widened.
 */
const RUST_NONE_AVAILABLE =
  "no characters available — create one at characters/<name>/workspace/SOUL.md";

/** The same failure, with the path resolved against `configDir` (#41). */
function withResolvedSoulPath(result: unknown, configDir: string): unknown {
  if (typeof result !== "object" || result === null) return result;
  const record = result as Record<string, unknown>;
  if (record["err"] !== RUST_NONE_AVAILABLE) return result;
  return {
    ...record,
    err:
      `no characters available — create one at ${configDir}/characters/<name>/workspace/SOUL.md, ` +
      "or run: shore character --new <name>",
  };
}

/** The generator's `config_marks()`. */
function configMarks(config: LoadedConfig): unknown {
  return {
    stream: config.app.defaults.stream,
    display_name: config.app.defaults.display_name ?? null,
    addr: config.app.daemon.addr,
  };
}

/**
 * A `LoadedConfig` built the way `LoadedConfig::new_for_test` does — no raw
 * table, so a character override merges over nothing.
 */
function newForTest(configDir: string, dataDir: string, root: string): LoadedConfig {
  return {
    app: defaultAppConfig(),
    models: emptyCatalog(),
    providers: ProviderRegistry.empty(),
    dirs: {
      config: configDir,
      data: dataDir,
      runtime: join(root, "runtime"),
      cache: join(root, "cache"),
    },
    rawTable: undefined,
  };
}

function loadFrom(path: string): LoadedConfig {
  // Warnings are the config layer's own parity subject; silence them here so a
  // 22-scenario replay does not put a hundred advisory lines through the runner.
  return loadConfig(path, { onWarn: () => {} });
}

// ── Replay ──────────────────────────────────────────────────────────────

describe("the fixture is real", () => {
  const header = (fixture._header as string[]).join(" ");

  test("it was frozen, and says so", () => {
    expect(header).toContain("nothing regenerates this file");
  });

  test("it names the worktree it came from", () => {
    expect(header).toContain("9023b46d");
  });

  test("every scenario is a run, not a call", () => {
    // One-step scenarios would mean the caching this module exists for was
    // never exercised.
    for (const s of scenarios) expect(s.steps.length).toBeGreaterThan(1);
    expect(scenarios.length).toBeGreaterThan(15);
  });
});

describe("CharacterRegistry", () => {
  for (const scenario of scenarios) {
    test(scenario.name, async () => {
      const root = makeRoot();
      const configDir = join(root, "config");
      const dataDir = join(root, "data");
      mkdirSync(configDir, { recursive: true });
      mkdirSync(dataDir, { recursive: true });

      // Engine identity, assigned in first-seen order exactly as the generator
      // assigned it from `Arc::as_ptr`.
      const engineIds: object[] = [];
      const engineId = (engine: object): number => {
        const seen = engineIds.indexOf(engine);
        if (seen >= 0) return seen;
        engineIds.push(engine);
        return engineIds.length - 1;
      };

      let registry: CharacterRegistry | undefined;

      for (const [index, step] of scenario.steps.entries()) {
        const where = `${scenario.name} step ${String(index)} (${step.op})`;

        switch (step.op) {
          // ── construction ───────────────────────────────────────────
          case "new": {
            writeFileSync(join(configDir, "config.toml"), scenario.seed.global_toml as string);
            seedCharacters(configDir, scenario);
            registry = await CharacterRegistry.create(
              configDir,
              dataDir,
              loadFrom(join(configDir, "config.toml")),
            );
            break;
          }
          case "new_for_test": {
            seedCharacters(configDir, scenario);
            registry = await CharacterRegistry.create(
              configDir,
              dataDir,
              newForTest(configDir, dataDir, root),
            );
            break;
          }

          // ── filesystem mutations ───────────────────────────────────
          case "fs:add_character":
            writeCharacter(configDir, step.name as string, step.soul as boolean);
            break;
          case "fs:remove_character":
            rmSync(join(configDir, "characters", step.name as string), {
              recursive: true,
              force: true,
            });
            break;
          case "fs:write_character_config": {
            const dir = join(configDir, "characters", step.name as string);
            mkdirSync(dir, { recursive: true });
            writeFileSync(join(dir, "config.toml"), step.toml as string);
            break;
          }
          case "fs:write": {
            const path = join(configDir, step.path as string);
            mkdirSync(join(path, ".."), { recursive: true });
            writeFileSync(path, step.body as string);
            break;
          }
          case "fs:block_data_dir":
            // A regular file where a character's data directory belongs, so
            // preparing its workspace cannot succeed.
            writeFileSync(join(dataDir, step.name as string), "not a directory");
            break;

          // ── registry operations ────────────────────────────────────
          case "refresh":
            await required(registry, where).refresh();
            break;

          case "has_character":
            expect(
              required(registry, where).hasCharacter(step.name as string),
              where,
            ).toBe(step.result as boolean);
            break;

          case "resolve_character": {
            const requested = step.requested ?? undefined;
            let got: unknown;
            try {
              got = { ok: required(registry, where).resolveCharacter(requested) };
            } catch (e) {
              if (!(e instanceof CharacterError)) throw e;
              got = { err: e.message, variant: e.kind };
            }
            expect(got, where).toEqual(withResolvedSoulPath(step.result, configDir));
            break;
          }

          case "get_or_create": {
            let got: unknown;
            try {
              const engine = await required(registry, where).getOrCreate(step.name as string);
              // `root` is which of the two roots the engine was opened under,
              // as a label rather than a machine-specific path. An engine
              // opened against the config directory would read an empty
              // conversation and silently lose the character's history —
              // identity alone would not notice.
              got = {
                ok: true,
                engine: engineId(engine),
                root: rootOf(engine.characterDir, dataDir, configDir),
                leaf: basename(engine.characterDir),
              };
            } catch (e) {
              if (!(e instanceof EngineCharacterNotFound)) throw e;
              got = { err: e.message };
            }
            expect(got, where).toEqual(step.result);
            break;
          }

          case "effective_config":
            expect(
              configMarks(required(registry, where).effectiveConfig(step.name as string)),
              where,
            ).toEqual(step.result);
            break;

          case "invalidate_configs":
            required(registry, where).invalidateConfigs();
            break;

          case "set_runtime_effective_config": {
            const path = join(root, "runtime_override.toml");
            writeFileSync(path, step.toml as string);
            required(registry, where).setRuntimeEffectiveConfig(
              step.name as string,
              loadFrom(path),
            );
            break;
          }

          case "set_global_config": {
            const path = join(configDir, "config.toml");
            writeFileSync(path, step.toml as string);
            required(registry, where).setGlobalConfig(loadFrom(path));
            break;
          }

          case "set_global_config_elsewhere": {
            const dir = join(root, "elsewhere");
            mkdirSync(dir, { recursive: true });
            const path = join(dir, "config.toml");
            writeFileSync(path, step.toml as string);
            required(registry, where).setGlobalConfig(loadFrom(path));
            break;
          }

          case "reload_runtime_state": {
            const reg = required(registry, where);
            const summary = await reg.reloadRuntimeState(reg.globalConfig());
            expect(summary, where).toEqual({
              availableBefore: step.summary?.available_before as number,
              availableAfter: step.summary?.available_after as number,
              characterDiscoveryChanged: step.summary
                ?.character_discovery_changed as boolean,
              droppedEngines: step.summary?.dropped_engines as number,
            });
            break;
          }

          case "character_definition":
            expect(
              required(registry, where).characterDefinition(step.name as string) ?? null,
              where,
            ).toBe(step.result as string | null);
            break;

          case "user_definition":
            expect(
              required(registry, where).userDefinition(step.name as string) ?? null,
              where,
            ).toBe(step.result as string | null);
            break;

          default:
            throw new Error(`${where}: unhandled op`);
        }

        // State after every step, including the pure filesystem ones — that is
        // what shows a mutation is invisible until something re-scans.
        const reg = required(registry, where);
        expect(
          {
            available: [...reg.availableCharacters()],
            snapshots: snapshotsOnDisk(dataDir),
          },
          `${where}: state`,
        ).toEqual(step.state);
      }
    });
  }
});

/**
 * The characters the generator created before constructing the registry.
 *
 * Recorded in the fixture rather than inferred from the first step's results:
 * whether a character was seeded with `workspace/SOUL.md` or the legacy
 * `character.md` changes what `characterDefinition` returns, and reconstructing
 * that from the answers would make the replay agree with itself instead of
 * with the Rust.
 */
function seedCharacters(configDir: string, scenario: Scenario): void {
  for (const { name, soul } of scenario.seed.characters) {
    writeCharacter(configDir, name, soul);
  }
}

/** Which root a path sits under, matching the generator's `starts_with` order. */
function rootOf(path: string, dataDir: string, configDir: string): string {
  if (path.startsWith(dataDir)) return "data";
  if (path.startsWith(configDir)) return "config";
  return "other";
}

/** Rust's `Path::file_name()`, for the paths this test produces. */
function basename(path: string): string {
  const at = path.lastIndexOf("/");
  return at < 0 ? path : path.slice(at + 1);
}

function required(registry: CharacterRegistry | undefined, where: string): CharacterRegistry {
  if (registry === undefined) throw new Error(`${where}: registry not constructed yet`);
  return registry;
}
