/**
 * Replay of `commands_fixtures/model_settings_parity.json` against
 * `src/commands/model_settings.ts` and the two capability functions it added to
 * `src/llm/capabilities.ts`.
 *
 * Generated by driving the real Rust at `9023b46d` with the dreaming removal
 * applied, so the worktree's `models.rs` is HEAD's. Frozen — a diff here is a
 * defect in the port, not a fixture to update.
 *
 * Two bridges the replay makes explicit:
 *
 * - **`SamplerSettings` is snake_case with nulls in the fixture and camelCase
 *   with absent fields in the port.** Serde wrote all fourteen fields whether
 *   set or not; the port leaves them `undefined`. {@link toWire} spells the
 *   conversion out field by field rather than mangling keys, so a field the two
 *   sides genuinely disagree about cannot be smoothed over by a rule.
 * - **`CacheKeepaliveSetting` serialized as its `Display` string** (`"off"`,
 *   `"55m"`), where the port holds a tagged object. Converted in the same place.
 *
 * `openrouter_provider` values compare by structure, not key order: the Rust
 * round-tripped them through a `toml::Value`, which sorts its table keys, and
 * the port stores the object as it arrived. Nothing reads that ordering.
 */

import { describe, expect, test } from "bun:test";

import fixture from "./commands_fixtures/model_settings_parity.json" with { type: "json" };

import { CommandError } from "../src/commands/errors.ts";
import {
  applySamplerValue,
  capabilityCheck,
  keyApplicability,
  reasoningEffortDomain,
  SAMPLER_KEYS,
} from "../src/commands/model_settings.ts";
import { supportsReasoningOff } from "../src/llm/capabilities.ts";
import type { Sdk } from "../src/config/models.ts";
import type { SamplerSettings } from "../src/config/preferences.ts";

// ── fixture shapes ──────────────────────────────────────────────────────

interface WireError {
  code: string;
  message: string;
}

/** `SamplerSettings` as serde wrote it: every field present, absent is `null`. */
type WireSampler = Record<string, unknown>;

interface SamplerCase {
  name: string;
  key: string;
  value: unknown;
  base: "empty" | "populated";
  before: WireSampler;
  after: WireSampler;
  err?: WireError;
}

interface CapabilityCase {
  name: string;
  sdk: string;
  model_id: string;
  key: string;
  value: unknown;
  err?: WireError;
}

interface ApplicabilityCase {
  name: string;
  sdk: string;
  model_id: string;
  applicability: Record<string, string>;
  reasoning_effort_domain: string[];
  supports_reasoning_off: boolean;
}

const samplerCases = fixture.apply_sampler_value as unknown as SamplerCase[];
const capabilityCases = fixture.capability_check as unknown as CapabilityCase[];
const applicabilityCases = fixture.applicability as unknown as ApplicabilityCase[];
const scopes = fixture.scopes as unknown as { scope: string; label: string }[];

// ── the shape bridge ────────────────────────────────────────────────────

/** The port's settings block in the fixture's spelling. */
function toWire(s: SamplerSettings): WireSampler {
  const keepalive = s.cacheKeepalive;
  return {
    temperature: s.temperature ?? null,
    top_p: s.topP ?? null,
    reasoning_effort: s.reasoningEffort ?? null,
    budget_tokens: s.budgetTokens ?? null,
    max_output_tokens: s.maxOutputTokens ?? null,
    cache_ttl: s.cacheTtl ?? null,
    cache_keepalive:
      keepalive === undefined
        ? null
        : keepalive.kind === "off"
          ? "off"
          : keepalive.interval.toString(),
    sdk: s.sdk ?? null,
    replay_prior_thinking: s.replayPriorThinking ?? null,
    max_tool_iterations: s.maxToolIterations ?? null,
    openrouter_provider: s.openrouterProvider ?? null,
    gemini_generation: s.geminiGeneration ?? null,
    zai_clear_thinking: s.zaiClearThinking ?? null,
    zai_subscription: s.zaiSubscription ?? null,
  };
}

/** Rebuild a settings block from the fixture's `before` snapshot. */
function fromWire(w: WireSampler): SamplerSettings {
  const out: SamplerSettings = {};
  for (const [key, value] of Object.entries(w)) {
    if (value === null) continue;
    applySamplerValue(out, key, value);
  }
  return out;
}

function expectError(thrown: unknown, expected: WireError, label: string): void {
  expect(thrown, label).toBeInstanceOf(CommandError);
  expect((thrown as CommandError).code, label).toBe(expected.code as never);
  expect((thrown as CommandError).message, label).toBe(expected.message);
}

// ── the key list ────────────────────────────────────────────────────────

test("the settable keys, and their order", () => {
  // The order is load-bearing: `set_model_setting` joins this list into its
  // rejection message.
  expect(SAMPLER_KEYS).toEqual(fixture.sampler_keys as unknown as string[]);
});

// ── apply_sampler_value ─────────────────────────────────────────────────

describe("applySamplerValue", () => {
  for (const c of samplerCases) {
    test(c.name, () => {
      const sampler = fromWire(c.before);
      // The reconstruction has to be exact, or the "leaves the old value alone"
      // half of every rejected case is checked against the wrong starting point.
      expect(toWire(sampler), `${c.name} — reconstructed base`).toEqual(c.before as never);

      let thrown: unknown;
      try {
        applySamplerValue(sampler, c.key, c.value);
      } catch (e) {
        thrown = e;
      }

      if (c.err !== undefined) {
        expectError(thrown, c.err, c.name);
      } else {
        expect(thrown, c.name).toBeUndefined();
      }
      // Recorded whether the call succeeded or not: a parser that writes on the
      // way to failing would leave a changed block behind an error.
      expect(toWire(sampler), `${c.name} — after`).toEqual(c.after as never);
    });
  }
});

// ── capability_check ────────────────────────────────────────────────────

describe("capabilityCheck", () => {
  // 2,800-odd cases: one test per sdk/model pair, asserting inside.
  const groups = new Map<string, CapabilityCase[]>();
  for (const c of capabilityCases) {
    const key = `${c.sdk} / ${c.model_id}`;
    const list = groups.get(key);
    if (list === undefined) groups.set(key, [c]);
    else list.push(c);
  }

  for (const [group, cases] of groups) {
    test(group, () => {
      for (const c of cases) {
        const failure = capabilityCheck(c.sdk as Sdk, c.model_id, c.key, c.value);
        if (c.err !== undefined) {
          expect(failure, c.name).toBeInstanceOf(CommandError);
          expect(failure!.code, c.name).toBe(c.err.code as never);
          expect(failure!.message, c.name).toBe(c.err.message);
        } else {
          expect(failure, c.name).toBeUndefined();
        }
      }
    });
  }
});

// ── the two tables ──────────────────────────────────────────────────────

describe("keyApplicability and the reasoning domain", () => {
  for (const c of applicabilityCases) {
    test(c.name, () => {
      expect(keyApplicability(c.sdk as Sdk, c.model_id)).toEqual(c.applicability as never);
      expect(reasoningEffortDomain(c.sdk as Sdk, c.model_id)).toEqual(
        c.reasoning_effort_domain as never,
      );
      expect(supportsReasoningOff(c.sdk as Sdk)).toBe(c.supports_reasoning_off);
    });
  }
});

test("the five preference scopes spell the same strings on both sides", () => {
  // `scope_str` has no counterpart in the port — `PreferenceScope` is already
  // the wire string — so this is what stops the two enums drifting apart.
  expect(scopes.map((s) => s.label)).toEqual([
    "static_default",
    "global_default",
    "character_default",
    "global_model",
    "character_model",
  ]);
});
