/**
 * Parity tests for the model catalog against a frozen fixture generated by
 * driving the real `shore_common::config`.
 *
 * Unlike every earlier port in this series, the fixture was generated from
 * `main` rather than a detached worktree: `shore-common` still compiles, so
 * this pins current behaviour instead of behaviour from the last green daemon
 * commit.
 */

import { describe, expect, test } from "bun:test";

import fixture from "./config_fixtures/models_parity.json" with { type: "json" };

import { expectedKeepalive, withoutDefaultedKeepalive } from "./support/keepalive_default.ts";
import { ConfigDuration } from "../src/config/duration.ts";
import {
  applicability,
  defaultValue,
  fieldFromKey,
  type Applicability,
  type Field,
  type Sdk,
} from "../src/llm/capabilities.ts";
import {
  CatalogError,
  catalogFromSections,
  chatModelNames,
  defaultSdk,
  findModel,
  firstChatModel,
  hardcodedProviderDefaults,
  keepaliveIntervalMs,
  keepaliveToString,
  mergeFrom,
  orFallback,
  parseCacheKeepalive,
  resolvedModelFromParts,
  sdkEchoesUnsignedThinking,
  sdkFromWire,
  sdkUsesAnthropicPromptCache,
  type ModelConfigFields,
  type ProviderRegistryEntry,
  type ProviderRegistryView,
  type ResolvedModel,
} from "../src/config/models.ts";

// ── fixture shapes ───────────────────────────────────────────────────────────

interface DurationRow {
  raw: string;
  millis?: string;
  err?: string;
}
interface DisplayRow {
  millis: string;
  display: string;
  secs: string;
  json: string;
}
interface FromSecsRow {
  secs: string;
  millis: string;
}
interface KeepaliveRow {
  raw: string;
  display?: string;
  interval_millis?: string | null;
  json?: string;
  err?: string;
}
interface SdkWireRow {
  raw: string;
  sdk: string | null;
}
interface SdkFlagsRow {
  sdk: string;
  as_str: string;
  echoes_unsigned_thinking: boolean;
  uses_anthropic_prompt_cache: boolean;
}
interface ApplicabilityRow {
  sdk: string;
  model_id: string;
  field: string;
  applicability: string;
}
interface DefaultValueRow {
  sdk: string;
  field: string;
  default: string | null;
}
interface FieldFromKeyRow {
  key: string;
  field: string | null;
}
interface ProviderDefaultsRow {
  provider: string;
  fields: Record<string, unknown>;
  default_sdk: string;
}
interface FromPartsRow {
  sdk_fallback: string;
  model_id: string;
  explicit_samplers?: boolean;
  resolved: Record<string, unknown>;
}
interface CatalogRow {
  name: string;
  chat_toml: string;
  embedding_toml: string;
  image_generation_toml: string;
  providers_toml: string;
  catalog?: {
    chat: Record<string, Record<string, unknown>>;
    chat_order: string[];
    embedding: Record<string, Record<string, unknown>>;
    embedding_order: string[];
    image_generation: Record<string, Record<string, unknown>>;
    image_generation_order: string[];
  };
  err?: string;
}
interface LookupSection {
  toml: string;
  cases: { name: string; qualified_name?: string; err?: string }[];
  first_chat_model: string | null;
  chat_model_names: string[];
}

const fx = fixture as unknown as {
  duration_parse: DurationRow[];
  duration_display: DisplayRow[];
  duration_from_secs: FromSecsRow[];
  keepalive_parse: KeepaliveRow[];
  sdk_parse_wire: SdkWireRow[];
  sdk_flags: SdkFlagsRow[];
  applicability: ApplicabilityRow[];
  default_value: DefaultValueRow[];
  field_keys: { field: string; key: string }[];
  field_from_key: FieldFromKeyRow[];
  provider_defaults: ProviderDefaultsRow[];
  from_parts: FromPartsRow[];
  catalogs: CatalogRow[];
  lookup: LookupSection;
};

// ── helpers ──────────────────────────────────────────────────────────────────

/**
 * The Rust `Serialize` impl writes every absent field as an explicit `null`;
 * the TypeScript leaves it off entirely, because `exactOptionalPropertyTypes`
 * makes "absent" and "present and undefined" different types. Normalize to the
 * Rust shape so a field that should be gone cannot pass by being `undefined`.
 */
function toWire(model: ResolvedModel): Record<string, unknown> {
  const keepalive = model.cacheKeepalive;
  return {
    name: model.name,
    qualified_name: model.qualifiedName,
    category: model.category,
    provider_key: model.providerKey,
    sdk: model.sdk,
    model_id: model.modelId,
    api_key_env: model.apiKeyEnv ?? null,
    base_url: model.baseUrl ?? null,
    max_context_tokens: model.maxContextTokens ?? null,
    max_output_tokens: model.maxOutputTokens ?? null,
    temperature: model.temperature ?? null,
    top_p: model.topP ?? null,
    reasoning_effort: model.reasoningEffort ?? null,
    budget_tokens: model.budgetTokens ?? null,
    cache_ttl: model.cacheTtl ?? null,
    cache_keepalive: keepalive === undefined ? null : keepaliveToString(keepalive),
    openrouter_provider: model.openrouterProvider ?? null,
    gemini_generation: model.geminiGeneration ?? null,
    zai_clear_thinking: model.zaiClearThinking ?? null,
    zai_subscription: model.zaiSubscription ?? null,
    replay_prior_thinking: model.replayPriorThinking ?? null,
    max_tool_iterations: model.maxToolIterations ?? null,
  };
}

/** The same normalization for a bare field bag (`ModelConfigFields`). */
function fieldsToWire(fields: ModelConfigFields): Record<string, unknown> {
  const keepalive = fields.cacheKeepalive;
  return {
    sdk: fields.sdk ?? null,
    api_key_env: fields.apiKeyEnv ?? null,
    base_url: fields.baseUrl ?? null,
    max_context_tokens: fields.maxContextTokens ?? null,
    max_output_tokens: fields.maxOutputTokens ?? null,
    temperature: fields.temperature ?? null,
    top_p: fields.topP ?? null,
    reasoning_effort: fields.reasoningEffort ?? null,
    budget_tokens: fields.budgetTokens ?? null,
    cache_ttl: fields.cacheTtl ?? null,
    cache_keepalive: keepalive === undefined ? null : keepaliveToString(keepalive),
    openrouter_provider: fields.openrouterProvider ?? null,
    gemini_generation: fields.geminiGeneration ?? null,
    zai_clear_thinking: fields.zaiClearThinking ?? null,
    zai_subscription: fields.zaiSubscription ?? null,
  };
}

function parseToml(text: string): Record<string, unknown> | undefined {
  if (text.trim() === "") return undefined;
  return Bun.TOML.parse(text) as Record<string, unknown>;
}

/** A registry view backed by a parsed `[providers]` table, standing in until
 *  `providers.ts` lands. Only the two transport fields and `defaults` matter
 *  to the cascade. */
function registryFromToml(text: string): ProviderRegistryView | undefined {
  const table = parseToml(text);
  if (table === undefined) return undefined;
  const entries = new Map<string, ProviderRegistryEntry>();
  for (const [name, raw] of Object.entries(table)) {
    const body = raw as Record<string, unknown>;
    const defaultsTable = (body["defaults"] ?? {}) as Record<string, unknown>;
    const defaults: ModelConfigFields = {};
    if (typeof defaultsTable["max_output_tokens"] === "number") {
      defaults.maxOutputTokens = defaultsTable["max_output_tokens"];
    }
    if (typeof defaultsTable["max_context_tokens"] === "number") {
      defaults.maxContextTokens = defaultsTable["max_context_tokens"];
    }
    if (typeof defaultsTable["temperature"] === "number") {
      defaults.temperature = defaultsTable["temperature"];
    }
    if (typeof defaultsTable["cache_ttl"] === "string") {
      defaults.cacheTtl = defaultsTable["cache_ttl"];
    }
    const entry: ProviderRegistryEntry = { defaults };
    if (typeof body["sdk"] === "string") entry.sdk = body["sdk"] as Sdk;
    if (typeof body["base_url"] === "string") entry.baseUrl = body["base_url"];
    entries.set(name, entry);
  }
  return { get: (name) => entries.get(name) };
}

/**
 * The daemon-authored part of a catalog error.
 *
 * `CatalogError::ParseEntry` embeds a `toml::de::Error`, which appends its own
 * presentation — a trailing newline and, when the crate happens to have kept
 * the key in scope, an `in \`<key>\`` line. That decoration is the TOML
 * crate's, is inconsistent between otherwise identical failures (`model_id`
 * gets the key annotation; a flattened field does not), and is not something
 * a port should reproduce. Everything before the first newline is Shore's own
 * message and is pinned exactly.
 */
function firstLine(message: string): string {
  return message.split("\n")[0] as string;
}

function catchCatalogError(fn: () => unknown): CatalogError {
  try {
    fn();
  } catch (e) {
    if (e instanceof CatalogError) return e;
    throw e;
  }
  throw new Error("expected a CatalogError");
}

describe("the fixture is real", () => {
  test("it was frozen, and says so", () => {
    const header = fixture._header.join(" ");
    expect(header).toContain("nothing regenerates this file");
  });

  // Every other fixture in this series was generated from the 9023b46d
  // worktree, and this one was not. Asserting the provenance it actually has
  // is what stops a later edit from copying a neighbour's header onto it.
  test("it names `main` as its source, not the worktree", () => {
    expect(fixture._header.join(" ")).toContain("GENERATED from `main`");
  });
});

// ── duration ─────────────────────────────────────────────────────────────────

describe("ConfigDuration.parse", () => {
  for (const row of fx.duration_parse) {
    test(`parses ${JSON.stringify(row.raw)}`, () => {
      const result = ConfigDuration.parse(row.raw);
      if (row.err !== undefined) {
        expect(result).toEqual({ err: row.err });
      } else {
        expect("ok" in result).toBe(true);
        if ("ok" in result) {
          expect(result.ok.asMillisExact().toString()).toBe(row.millis as string);
        }
      }
    });
  }

  test("rejects the BOM that JavaScript's own trim would have swallowed", () => {
    // `String.prototype.trim` strips U+FEFF; Rust's `str::trim` does not, so
    // the BOM stays in the string and makes the whole thing an invalid suffix.
    expect(ConfigDuration.parse("\ufeff30s")).toEqual({
      err: "invalid duration suffix: \ufeff30s",
    });
    expect("\ufeff30s".trim()).toBe("30s");
  });

  test("accepts the NEL that JavaScript's own trim would have kept", () => {
    // The mirror image: U+0085 has the Unicode White_Space property, so Rust
    // trims it, but it is neither a JavaScript WhiteSpace nor a LineTerminator.
    const parsed = ConfigDuration.parse("\u008530s");
    expect(parsed).toHaveProperty("ok");
    expect("\u008530s".trim()).toBe("\u008530s");
  });
});

describe("ConfigDuration display and accessors", () => {
  for (const row of fx.duration_display) {
    test(`renders ${row.millis} as ${row.display}`, () => {
      const d = ConfigDuration.fromMillis(BigInt(row.millis));
      expect(d.toString()).toBe(row.display);
      expect(d.asSecs().toString()).toBe(row.secs);
      expect(d.toJSON()).toBe(row.json);
    });
  }

  test("every rendered form parses back to the same milliseconds", () => {
    for (const row of fx.duration_display) {
      const reparsed = ConfigDuration.parse(row.display);
      expect(reparsed).toHaveProperty("ok");
      if ("ok" in reparsed) {
        expect(reparsed.ok.asMillisExact().toString()).toBe(row.millis);
      }
    }
  });
});

describe("ConfigDuration.fromSecs", () => {
  for (const row of fx.duration_from_secs) {
    test(`${row.secs}s saturates to ${row.millis}ms`, () => {
      expect(ConfigDuration.fromSecs(BigInt(row.secs)).asMillisExact().toString()).toBe(row.millis);
    });
  }
});

// ── cache keepalive ──────────────────────────────────────────────────────────

describe("parseCacheKeepalive", () => {
  for (const row of fx.keepalive_parse) {
    test(`parses ${JSON.stringify(row.raw)}`, () => {
      const result = parseCacheKeepalive(row.raw);
      if (row.err !== undefined) {
        expect(result).toEqual({ err: row.err });
        return;
      }
      expect(result).toHaveProperty("ok");
      if (!("ok" in result)) return;
      expect(keepaliveToString(result.ok)).toBe(row.display as string);
      const interval = keepaliveIntervalMs(result.ok);
      const expected = row.interval_millis;
      expect(interval === undefined ? null : String(interval)).toEqual(expected ?? null);
    });
  }

  test("the off spellings fold with ASCII case only", () => {
    // Rust uses `to_ascii_lowercase`. A Kelvin sign lowercases to `k` under
    // full Unicode folding but not under ASCII folding, so it must stay an
    // error rather than becoming an unrecognised-but-lowercased spelling.
    expect(parseCacheKeepalive("OFF")).toEqual({ ok: { kind: "off" } });
    expect("\u212a".toLowerCase()).toBe("k");
    expect(parseCacheKeepalive("\u212a")).toHaveProperty("err");
  });

  test("a zero interval is rejected rather than spinning a ping loop", () => {
    expect(parseCacheKeepalive("0s")).toEqual({
      err: 'cache_keepalive interval must be > 0; use "off" to disable',
    });
    // `"0"` is an *off* spelling, not a zero duration — checked first.
    expect(parseCacheKeepalive("0")).toEqual({ ok: { kind: "off" } });
  });
});

// ── sdk ──────────────────────────────────────────────────────────────────────

describe("Sdk", () => {
  for (const row of fx.sdk_parse_wire) {
    test(`parse_wire ${JSON.stringify(row.raw)}`, () => {
      expect<string | null>(sdkFromWire(row.raw) ?? null).toBe(row.sdk);
    });
  }

  for (const row of fx.sdk_flags) {
    test(`${row.sdk} flags`, () => {
      const sdk = row.sdk as Sdk;
      expect(sdk).toBe(row.as_str as Sdk);
      expect(sdkEchoesUnsignedThinking(sdk)).toBe(row.echoes_unsigned_thinking);
      expect(sdkUsesAnthropicPromptCache(sdk)).toBe(row.uses_anthropic_prompt_cache);
    });
  }

  test("moonshotai is an alias, not a distinct sdk", () => {
    expect(sdkFromWire("moonshotai")).toBe("moonshot");
  });
});

// ── capability matrix ────────────────────────────────────────────────────────

describe("applicability", () => {
  for (const row of fx.applicability) {
    test(`${row.sdk} / ${row.model_id || "<empty>"} / ${row.field}`, () => {
      expect(applicability(row.sdk as Sdk, row.model_id, row.field as Field)).toBe(
        row.applicability as Applicability,
      );
    });
  }
});

describe("defaultValue", () => {
  for (const row of fx.default_value) {
    test(`${row.sdk} / ${row.field}`, () => {
      expect(defaultValue(row.sdk as Sdk, row.field as Field) ?? null).toBe(
        row.field === "cache_keepalive" ? expectedKeepalive(row.default) : row.default,
      );
    });
  }
});

describe("Field keys", () => {
  test("every field's key is its own name", () => {
    for (const row of fx.field_keys) expect(row.field).toBe(row.key);
  });

  for (const row of fx.field_from_key) {
    test(`fieldFromKey ${JSON.stringify(row.key)}`, () => {
      expect<string | null>(fieldFromKey(row.key) ?? null).toBe(row.field);
    });
  }
});

// ── provider defaults ────────────────────────────────────────────────────────

describe("hardcodedProviderDefaults", () => {
  for (const row of fx.provider_defaults) {
    test(`${row.provider || "<empty>"}`, () => {
      expect(fieldsToWire(hardcodedProviderDefaults(row.provider).fields)).toEqual(row.fields);
      expect(defaultSdk(row.provider)).toBe(row.default_sdk as Sdk);
    });
  }

  test("an unknown provider gets nothing, not the shared baseline", () => {
    // Every known provider spreads `baseProviderDefaults()`; the catch-all arm
    // does not, so an unrecognised key resolves with no temperature, no token
    // limits, and no credential env name at all.
    expect(hardcodedProviderDefaults("whoknows").fields).toEqual({});
    expect(hardcodedProviderDefaults("anthropic").fields.maxContextTokens).toBe(200_000);
  });

  test("opencode-go deliberately leaves sdk unset", () => {
    // It serves two wire dialects behind one key, so the per-model SDK that
    // discovery stamps has to win over a blanket provider default.
    expect(hardcodedProviderDefaults("opencode-go").fields.sdk).toBeUndefined();
    expect(defaultSdk("opencode-go")).toBe("openai");
  });
});

// ── from_parts ───────────────────────────────────────────────────────────────

describe("resolvedModelFromParts", () => {
  for (const [i, row] of fx.from_parts.entries()) {
    test(`${i}: ${row.sdk_fallback} / ${row.model_id}`, () => {
      const fields: ModelConfigFields =
        row.explicit_samplers === true
          ? { temperature: 0.3, topP: 0.9, budgetTokens: 4096 }
          : { temperature: 1.0, maxOutputTokens: 8192 };
      const resolved = resolvedModelFromParts(
        "m",
        "chat.p.m",
        "chat",
        "p",
        row.model_id,
        row.sdk_fallback as Sdk,
        fields,
      );
      expect(toWire(resolved)).toEqual(withoutDefaultedKeepalive(row.resolved));
    });
  }

  test("an anthropic/* slug promotes the sdk only when none was pinned", () => {
    const promoted = resolvedModelFromParts(
      "m", "chat.p.m", "chat", "p", "anthropic/claude-opus-4-6", "openrouter", {},
    );
    expect(promoted.sdk).toBe("anthropic");
    // Promotion is what turns caching on, so it has to reach the ttl default.
    expect(promoted.cacheTtl).toBe("1h");

    const pinned = resolvedModelFromParts(
      "m", "chat.p.m", "chat", "p", "anthropic/claude-opus-4-6", "openrouter",
      { sdk: "openrouter" },
    );
    expect(pinned.sdk).toBe("openrouter");
    expect(pinned.cacheTtl).toBeUndefined();
  });

  test("an explicit cache_ttl of empty string survives the default", () => {
    const model = resolvedModelFromParts(
      "m", "chat.p.m", "chat", "p", "claude-opus-4-6", "anthropic", { cacheTtl: "" },
    );
    expect(model.cacheTtl).toBe("");
  });

  test("an explicit keepalive is carried, and nothing is defaulted in beside it", () => {
    const off = resolvedModelFromParts(
      "m", "chat.p.m", "chat", "p", "claude-opus-4-6", "anthropic",
      { cacheKeepalive: { kind: "off" } },
    );
    expect(keepaliveToString(off.cacheKeepalive as never)).toBe("off");

    const every = resolvedModelFromParts(
      "m", "chat.p.m", "chat", "p", "claude-opus-4-6", "anthropic",
      { cacheKeepalive: { kind: "every", interval: ConfigDuration.fromSecs(3300) } as never },
    );
    expect(keepaliveToString(every.cacheKeepalive as never)).toBe("55m");

    // #47: the Rust defaulted this to `55m` for every Anthropic model. Turning
    // a cache keepalive on is a spend decision, and `off` is the only default
    // that does not make it for the user. `cache_ttl` still defaults to `1h`,
    // because a longer TTL costs nothing until something pings.
    const defaulted = resolvedModelFromParts(
      "m", "chat.p.m", "chat", "p", "claude-opus-4-6", "anthropic", {},
    );
    expect(defaulted.cacheKeepalive).toBeUndefined();
    expect(defaulted.cacheTtl).toBe("1h");
  });

  test("the input fields are not mutated", () => {
    // `from_parts` takes `mut fields` by value in Rust; the port takes an
    // object by reference and has to copy before stripping, or a caller's
    // provider-default bag would lose `temperature` for every later model.
    const fields: ModelConfigFields = { temperature: 1.0 };
    resolvedModelFromParts("m", "q", "chat", "p", "claude-opus-4-7", "anthropic", fields);
    expect(fields.temperature).toBe(1.0);
  });

  test("the runtime-overlay fields are left absent, not null", () => {
    const model = resolvedModelFromParts("m", "q", "chat", "p", "x", "openai", {});
    expect("replayPriorThinking" in model).toBe(false);
    expect("maxToolIterations" in model).toBe(false);
  });
});

// ── field merging ────────────────────────────────────────────────────────────

describe("field merging", () => {
  test("mergeFrom overwrites only present overlay fields", () => {
    const target: ModelConfigFields = { temperature: 1.0, maxOutputTokens: 8192 };
    mergeFrom(target, { temperature: 0.2 });
    expect(target).toEqual({ temperature: 0.2, maxOutputTokens: 8192 });
  });

  test("orFallback prefers self and fills the rest", () => {
    const self: ModelConfigFields = { temperature: 0.2 };
    const fallback: ModelConfigFields = { temperature: 1.0, maxOutputTokens: 8192 };
    expect(orFallback(self, fallback)).toEqual({ temperature: 0.2, maxOutputTokens: 8192 });
  });

  test("orFallback does not alias the openrouter_provider value", () => {
    const fallback: ModelConfigFields = { openrouterProvider: { order: ["a"] } };
    const merged = orFallback({}, fallback);
    expect(merged.openrouterProvider).toEqual({ order: ["a"] });
  });

  test("a false boolean is a value, not an absence", () => {
    // `zai_clear_thinking = false` is the zai provider default; `??` would be
    // correct here but `||` would silently fall through to the fallback.
    const merged = orFallback({ zaiClearThinking: false }, { zaiClearThinking: true });
    expect(merged.zaiClearThinking).toBe(false);
  });
});

// ── catalog ──────────────────────────────────────────────────────────────────

describe("catalogFromSections", () => {
  for (const row of fx.catalogs) {
    test(row.name, () => {
      const build = () =>
        catalogFromSections(
          parseToml(row.chat_toml),
          parseToml(row.embedding_toml),
          parseToml(row.image_generation_toml),
          registryFromToml(row.providers_toml),
        );

      if (row.err !== undefined) {
        const error = catchCatalogError(build);
        expect(firstLine(error.message)).toBe(firstLine(row.err));
        return;
      }

      const catalog = build();
      const expected = row.catalog as NonNullable<CatalogRow["catalog"]>;

      expect([...catalog.chat.keys()]).toEqual(expected.chat_order);
      for (const [key, model] of catalog.chat) {
        expect(toWire(model)).toEqual(
          withoutDefaultedKeepalive(expected.chat[key]) as Record<string, unknown>,
        );
      }

      expect([...catalog.embedding.keys()]).toEqual(expected.embedding_order);
      for (const [key, settings] of catalog.embedding) {
        const want = expected.embedding[key] as Record<string, unknown>;
        expect<Record<string, unknown>>({ dimensions: settings.dimensions ?? null }).toEqual(want);
      }

      expect([...catalog.imageGeneration.keys()]).toEqual(expected.image_generation_order);
      for (const [key, settings] of catalog.imageGeneration) {
        const want = expected.image_generation[key] as Record<string, unknown>;
        expect<Record<string, unknown>>({
          size: settings.size ?? null,
          quality: settings.quality ?? null,
          aspect_ratio: settings.aspectRatio ?? null,
          image_size: settings.imageSize ?? null,
        }).toEqual(want);
      }
    });
  }

  test("catalog order is code point order, not UTF-16 order", () => {
    // The fixture case pins this, but only a direct assertion says why: under
    // JavaScript's default sort the emoji provider — a surrogate pair starting
    // at 0xD83C — would sort below `ﬀute` at 0xFB00 instead of above it.
    const catalog = catalogFromSections(
      Bun.TOML.parse(
        '["🎵drum".m]\nmodel_id = "a"\n["ﬀute".m]\nmodel_id = "b"\n[zzz.m]\nmodel_id = "c"\n',
      ) as Record<string, unknown>,
      undefined,
      undefined,
    );
    expect([...catalog.chat.keys()]).toEqual([
      "chat.zzz.m",
      "chat.ﬀute.m",
      "chat.🎵drum.m",
    ]);
    // What the naive sort would have produced, kept as the contrast.
    expect([...catalog.chat.keys()].sort()).not.toEqual([...catalog.chat.keys()]);
  });

  test("Bun's TOML parser mishandles the \\U escape Rust's handles", () => {
    // Not a defect in this port, but a hazard underneath it, recorded here so
    // it is not rediscovered from a corrupted character name.
    //
    // TOML spec escapes a non-BMP scalar as `\UXXXXXXXX` (8 hex digits). The
    // Rust `toml` crate decodes it; `Bun.TOML.parse` drops the backslash and
    // yields the *literal text* `U0001F3B5` — silently wrong data rather than
    // a parse error. The 4-digit `\uXXXX` form works in both.
    expect(Bun.TOML.parse('a = "\\U0001F3B5"')).toEqual({ a: "U0001F3B5" });
    expect(Bun.TOML.parse('a = "\\u00e9"')).toEqual({ a: "é" });
    expect(Bun.TOML.parse('a = "🎵"')).toEqual({ a: "🎵" });
  });

  test("the retired-scalar error names the first offending key in BTreeMap order", () => {
    // Rust iterates a `BTreeMap`, so `aaa` is reached before `zzz` even though
    // the document lists `zzz` first. Walking the parsed object in insertion
    // order would name the wrong key.
    const error = catchCatalogError(() =>
      catalogFromSections(
        Bun.TOML.parse('[anthropic]\nzzz = 1\naaa = 2\n[anthropic.opus]\nmodel_id = "x"\n') as Record<
          string,
          unknown
        >,
        undefined,
        undefined,
      ),
    );
    expect(error.message).toContain("`aaa`");
    expect(error.message).not.toContain("`zzz`");
  });

  test("a transport scalar and a behavioral scalar point at different homes", () => {
    const transport = catchCatalogError(() =>
      catalogFromSections(
        Bun.TOML.parse('[anthropic]\nsdk = "anthropic"\n') as Record<string, unknown>,
        undefined,
        undefined,
      ),
    );
    expect(transport.message).toContain("the matching [providers.<name>] entry");

    const behavioral = catchCatalogError(() =>
      catalogFromSections(
        Bun.TOML.parse("[anthropic]\nmax_output_tokens = 1\n") as Record<string, unknown>,
        undefined,
        undefined,
      ),
    );
    expect(behavioral.message).toContain("[providers.<name>.defaults]");
  });

  test("the registry cascade sits between hardcoded defaults and per-model fields", () => {
    const chat = Bun.TOML.parse(
      '[custom.fast]\nmodel_id = "m"\nmax_output_tokens = 111\n',
    ) as Record<string, unknown>;
    const registry = registryFromToml(
      '[custom]\nsdk = "openai"\nbase_url = "https://custom.example/v1"\n' +
        "[custom.defaults]\nmax_output_tokens = 4096\ntemperature = 0.7\n",
    );
    const catalog = catalogFromSections(chat, undefined, undefined, registry);
    const model = catalog.chat.get("chat.custom.fast") as ResolvedModel;

    expect(model.maxOutputTokens).toBe(111); // per-model wins over registry defaults
    expect(model.temperature).toBe(0.7); // registry defaults win over nothing
    expect(model.baseUrl).toBe("https://custom.example/v1"); // registry transport
    expect(model.sdk).toBe("openai");
  });

  test("registry credentials deliberately do not cascade", () => {
    // `api_key_env` is folded into the registry's `keys[]` list and read from
    // there by the credential resolver; overlaying a single env name back onto
    // the static model would defeat the multi-key fallback.
    const registry: ProviderRegistryView = {
      get: () => ({ sdk: "openai", defaults: {}, baseUrl: "https://x/v1" }),
    };
    const catalog = catalogFromSections(
      Bun.TOML.parse('[custom.fast]\nmodel_id = "m"\n') as Record<string, unknown>,
      undefined,
      undefined,
      registry,
    );
    expect((catalog.chat.get("chat.custom.fast") as ResolvedModel).apiKeyEnv).toBeUndefined();
  });

  test("the provider defaults are not shared between models", () => {
    // One `hardcodedProviderDefaults` bag is built per provider and read by
    // every model under it. If `from_parts` stripped in place, the first
    // Claude 4.7 model would delete `temperature` for its siblings too.
    const catalog = catalogFromSections(
      Bun.TOML.parse(
        '[anthropic.new]\nmodel_id = "claude-opus-4-7"\n[anthropic.old]\nmodel_id = "claude-opus-4-6"\n',
      ) as Record<string, unknown>,
      undefined,
      undefined,
    );
    expect((catalog.chat.get("chat.anthropic.new") as ResolvedModel).temperature).toBeUndefined();
    expect((catalog.chat.get("chat.anthropic.old") as ResolvedModel).temperature).toBe(1.0);
  });

  test("the final sort is load-bearing, not a formality", () => {
    // `a` sorts before `a-b`, but `chat.a-b.m` sorts before `chat.a.m`,
    // because `-` (0x2D) precedes `.` (0x2E). Walking providers in order and
    // inserting as you go therefore does not produce a `BTreeMap`-ordered
    // catalog; the sort at the end is what does.
    const catalog = catalogFromSections(
      Bun.TOML.parse('[a.m]\nmodel_id = "x"\n["a-b".m]\nmodel_id = "y"\n') as Record<
        string,
        unknown
      >,
      undefined,
      undefined,
    );
    expect([...catalog.chat.keys()]).toEqual(["chat.a-b.m", "chat.a.m"]);
  });

  test("a non-table provider value is skipped, not an error", () => {
    const catalog = catalogFromSections(
      Bun.TOML.parse("anthropic = 1\n") as Record<string, unknown>,
      undefined,
      undefined,
    );
    expect(catalog.chat.size).toBe(0);
  });
});

// ── lookup ───────────────────────────────────────────────────────────────────

describe("findModel", () => {
  const catalog = catalogFromSections(
    Bun.TOML.parse(fx.lookup.toml) as Record<string, unknown>,
    undefined,
    undefined,
  );

  for (const row of fx.lookup.cases) {
    test(`looks up ${JSON.stringify(row.name)}`, () => {
      if (row.err !== undefined) {
        const error = catchCatalogError(() => findModel(catalog, row.name));
        expect(error.message).toBe(row.err);
        return;
      }
      expect(findModel(catalog, row.name).qualifiedName).toBe(row.qualified_name as string);
    });
  }

  test("first_chat_model and chat_model_names follow catalog order", () => {
    expect(firstChatModel(catalog)?.qualifiedName ?? null).toBe(fx.lookup.first_chat_model);
    expect(chatModelNames(catalog)).toEqual(fx.lookup.chat_model_names);
  });

  test("a qualified name beats a short name", () => {
    // Both providers define `opus`, so the short name is ambiguous — but the
    // qualified form still resolves, which means the qualified pass has to run
    // first rather than falling out of the ambiguity check.
    expect(findModel(catalog, "chat.openrouter.opus").providerKey).toBe("openrouter");
    expect(() => findModel(catalog, "opus")).toThrow(/ambiguous/);
  });

  test("an empty catalog reports not-found rather than throwing something else", () => {
    const empty = catalogFromSections(undefined, undefined, undefined);
    const error = catchCatalogError(() => findModel(empty, "opus"));
    expect(error.kind).toBe("not_found");
    expect(firstChatModel(empty)).toBeUndefined();
  });
});
