/**
 * Replay of `handler_fixtures/resize_parity.json` against the TypeScript
 * resize port.
 *
 * Generated by driving the real `handler::resize` at `9023b46d`. Frozen.
 *
 * **Encoded bytes are deliberately not asserted.** Rust used `image` +
 * `fast_image_resize`; this uses libvips. What is asserted is everything around
 * the encoder — the arithmetic, the format choice, the floor, the cache — plus
 * the one property the encoder must deliver: the result fits the budget.
 */

import { describe, expect, test } from "bun:test";
import { mkdir, mkdtemp, readdir, stat, writeFile } from "node:fs/promises";
import { join } from "node:path";

import sharp from "sharp";

import fixture from "./handler_fixtures/resize_parity.json" with { type: "json" };

import {
  cachedResize,
  computeCacheKey,
  DIMENSION_FLOOR,
  hasMeaningfulAlpha,
  planOpaqueDims,
  planRetryDims,
  planTransparentDims,
  readCache,
  scaledDims,
  smartResize,
  warmImageCache,
  writeCache,
} from "../src/handler/resize.ts";
import { testTmp } from "./support/tmp.ts";

/** Directory listing that reads an absent directory as empty. */
async function readdirSafe(dir: string): Promise<string[]> {
  try {
    return await readdir(dir);
  } catch {
    return [];
  }
}

async function tmp(): Promise<string> {
  return await mkdtemp(testTmp("shore-resize-"));
}

/**
 * The same generator the fixture used: a deterministic high-frequency pattern,
 * so the encoder cannot meet the byte budget by compressing a flat field.
 */
async function noisy(w: number, h: number, alpha: number): Promise<Buffer> {
  const raw = Buffer.alloc(w * h * 4);
  for (let y = 0; y < h; y += 1) {
    for (let x = 0; x < w; x += 1) {
      const i = (y * w + x) * 4;
      raw[i] = (x * 7 + y * 13) % 256;
      raw[i + 1] = (x * 31 + y * 17) % 256;
      raw[i + 2] = ((x ^ y) * 3) % 256;
      raw[i + 3] = alpha;
    }
  }
  return await sharp(raw, { raw: { width: w, height: h, channels: 4 } }).png().toBuffer();
}

/** A smooth, highly compressible image — the opposite of {@link noisy}. */
async function gradient(w: number, h: number, alpha: number): Promise<Buffer> {
  const raw = Buffer.alloc(w * h * 4);
  for (let y = 0; y < h; y += 1) {
    for (let x = 0; x < w; x += 1) {
      const i = (y * w + x) * 4;
      raw[i] = (x >> 3) % 256;
      raw[i + 1] = (y >> 3) % 256;
      raw[i + 2] = 128;
      raw[i + 3] = alpha;
    }
  }
  return await sharp(raw, { raw: { width: w, height: h, channels: 4 } }).png().toBuffer();
}

async function dimsOf(bytes: Uint8Array): Promise<[number, number]> {
  const m = await sharp(Buffer.from(bytes)).metadata();
  return [m.width ?? 0, m.height ?? 0];
}

// ── Scale arithmetic ────────────────────────────────────────────────────

describe("scaledDims", () => {
  for (const row of fixture.scaled_dims as { w: number; h: number; scale: number; out: number[] }[]) {
    test(`${row.w}x${row.h} @ ${row.scale}`, () => {
      expect(scaledDims(row.w, row.h, row.scale)).toEqual(row.out as [number, number]);
    });
  }

  test("never produces a zero dimension", () => {
    // Every encoder rejects a 0-pixel image, so this is the difference between
    // a small picture and a failed turn.
    expect(scaledDims(1000, 500, 0)).toEqual([1, 1]);
    expect(scaledDims(1000, 500, 0.0001)).toEqual([1, 1]);
  });

  test("rounds rather than truncating", () => {
    expect(scaledDims(3, 3, 0.5)).toEqual([2, 2]);
    expect(scaledDims(7, 7, 0.5)).toEqual([4, 4]);
  });

  test("saturates instead of wrapping", () => {
    expect(scaledDims(4_294_967_295, 2, 1.0)).toEqual([4_294_967_295, 2]);
    // Past u32::MAX the Rust cast saturated. A plain assignment would hand the
    // encoder a dimension it cannot allocate.
    expect(scaledDims(4_294_967_295, 2, 2.0)).toEqual([4_294_967_295, 4]);
    expect(scaledDims(3_000_000_000, 1, 4.0)).toEqual([4_294_967_295, 4]);
  });
});

describe("planOpaqueDims / planTransparentDims", () => {
  for (const row of fixture.plan_dims as {
    label: string;
    src_dims: number[];
    src_bytes: number;
    max_bytes: number;
    opaque: number[];
    transparent: number[];
  }[]) {
    test(row.label, () => {
      const [w, h] = row.src_dims as [number, number];
      expect(planOpaqueDims(w, h, row.src_bytes, row.max_bytes)).toEqual(
        row.opaque as [number, number],
      );
      expect(planTransparentDims(w, h, row.src_bytes, row.max_bytes)).toEqual(
        row.transparent as [number, number],
      );
    });
  }

  test("the bytes-per-pixel threshold is strict", () => {
    // At exactly 3.0 the format factor stays 1.0; one byte more and the budget
    // is trebled, which roughly doubles the planned dimensions.
    expect(planOpaqueDims(1000, 1000, 3_000_000, 100_000)).toEqual([155, 155]);
    expect(planOpaqueDims(1000, 1000, 3_000_001, 100_000)).toEqual([269, 269]);
  });

  test("the dimension floor turns on at exactly 2048", () => {
    // A 2048-wide source is pulled back up to 2048; a 2047-wide one is not, and
    // the two land an order of magnitude apart.
    expect(planOpaqueDims(2048, 100, 10_000_000, 5_000)[0]).toBe(2048);
    expect(planOpaqueDims(2047, 100, 10_000_000, 5_000)[0]).toBe(67);
  });

  test("the floor is opaque-only — transparent images are never boosted", () => {
    expect(planTransparentDims(4000, 3000, 40_000_000, 5_000)).toEqual([38, 29]);
    expect(planOpaqueDims(4000, 3000, 40_000_000, 5_000)).toEqual([2048, 1520]);
  });

  test("a scale over 1.0 is clamped, never upscaling", () => {
    expect(planOpaqueDims(100, 100, 1_000, 1_000_000)).toEqual([100, 100]);
    expect(planTransparentDims(100, 100, 1_000, 1_000_000)).toEqual([100, 100]);
  });
});

describe("planRetryDims", () => {
  for (const row of fixture.plan_retry_dims as {
    label: string;
    dims: number[];
    encoded_len: number;
    max_bytes: number;
    factor: number;
    out: number[];
  }[]) {
    test(row.label, () => {
      const [w, h] = row.dims as [number, number];
      expect(planRetryDims(w, h, row.encoded_len, row.max_bytes, row.factor)).toEqual(
        row.out as [number, number],
      );
    });
  }

  test("the two paths use different pessimism factors", () => {
    // 0.85 transparent, 0.9 opaque — the opaque retry also drops quality, so it
    // is buying headroom twice and needs less of it here.
    const transparent = planRetryDims(800, 600, 900_000, 500_000, 0.85);
    const opaque = planRetryDims(800, 600, 900_000, 500_000, 0.9);
    expect(transparent).toEqual([507, 380]);
    expect(opaque).toEqual([537, 402]);
    expect(opaque[0]).toBeGreaterThan(transparent[0]);
  });

  test("is not floored — a brutal budget goes below 2048", () => {
    expect(planRetryDims(2048, 1536, 5_000_000, 5_000, 0.9)[0]).toBeLessThan(DIMENSION_FLOOR);
  });
});

// ── Alpha ───────────────────────────────────────────────────────────────

describe("hasMeaningfulAlpha", () => {
  test("a fully opaque RGBA image has none", async () => {
    expect(await hasMeaningfulAlpha(sharp(await noisy(8, 8, 255)))).toBe(false);
  });

  test("one step down from opaque counts", async () => {
    // The Rust asked `p[3] < 255`, not `p[3] < some threshold`.
    expect(await hasMeaningfulAlpha(sharp(await noisy(8, 8, 254)))).toBe(true);
  });

  test("fully transparent counts", async () => {
    expect(await hasMeaningfulAlpha(sharp(await noisy(8, 8, 0)))).toBe(true);
  });

  test("an image with no alpha channel is opaque without scanning", async () => {
    const rgb = await sharp(await noisy(8, 8, 255)).removeAlpha().png().toBuffer();
    expect(await hasMeaningfulAlpha(sharp(rgb))).toBe(false);
  });

  test("an image without an alpha channel is never scanned", async () => {
    // The guard is not just an optimisation. `stats()` walks every pixel, and
    // for a source it cannot analyse the catch below assumes transparency —
    // which would flip an ordinary opaque JPEG onto the PNG path and stop it
    // ever being compressed. A failing `stats()` must not be reachable when
    // the metadata already says there is no alpha.
    const rgb = await sharp(await noisy(8, 8, 255)).removeAlpha().png().toBuffer();
    const image = sharp(rgb);
    let scanned = false;
    const guarded = Object.assign(Object.create(Object.getPrototypeOf(image)), image, {
      metadata: () => image.metadata(),
      stats: () => {
        scanned = true;
        return Promise.reject(new Error("stats unavailable"));
      },
    }) as typeof image;
    expect(await hasMeaningfulAlpha(guarded)).toBe(false);
    expect(scanned).toBe(false);
  });

  test("a single non-opaque pixel among many is enough", async () => {
    // The one case that decides whether a screenshot with a rounded corner
    // survives as a PNG or gets flattened into a JPEG.
    const w = 32;
    const raw = Buffer.alloc(w * w * 4, 255);
    raw[(5 * w + 5) * 4 + 3] = 254;
    const png = await sharp(raw, { raw: { width: w, height: w, channels: 4 } }).png().toBuffer();
    expect(await hasMeaningfulAlpha(sharp(png))).toBe(true);
  });
});

// ── smartResize ─────────────────────────────────────────────────────────

describe("smartResize: the early returns", () => {
  test("an image already under the limit is untouched", async () => {
    const src = await noisy(64, 64, 255);
    expect(await smartResize(src, "image/png", 1_000_000)).toBeUndefined();
  });

  test("exactly at the limit is untouched; one byte over is not", async () => {
    const src = await noisy(64, 64, 255);
    expect(await smartResize(src, "image/png", src.length)).toBeUndefined();
    expect(await smartResize(src, "image/png", src.length - 1)).toBeDefined();
  });

  test("a zero limit disables resizing entirely", async () => {
    const src = await noisy(600, 400, 255);
    expect(await smartResize(src, "image/png", 0)).toBeUndefined();
  });

  test("a GIF is never resized, however far over", async () => {
    // Resizing one means dropping every frame but the first. A still where an
    // animation was is a worse answer than a large file.
    const src = await noisy(600, 400, 255);
    expect(await smartResize(src, "image/gif", 1_000)).toBeUndefined();
  });

  test("undecodable bytes pass through rather than failing the turn", async () => {
    const junk = Buffer.from("definitely not an image");
    expect(await smartResize(junk, "image/png", 4)).toBeUndefined();
  });
});

describe("smartResize: format choice", () => {
  test("an opaque image becomes JPEG", async () => {
    const src = await noisy(1500, 1200, 255);
    const out = await smartResize(src, "image/png", 400_000);
    expect(out?.mediaType).toBe("image/jpeg");
  });

  test("a transparent image stays PNG on the first attempt", async () => {
    // A *compressible* transparent source, so the first re-encode genuinely
    // fits and this exercises the first return rather than the retry. The
    // noise pattern cannot do it: re-encoding it at smaller dimensions
    // produces more bytes than the original, so it always reaches the retry
    // and a wrong media type on the first path would go unnoticed.
    const src = await gradient(1200, 900, 200);
    const budget = Math.floor(src.length / 2);
    const [planW, planH] = planTransparentDims(1200, 900, src.length, budget);
    const firstAttempt = await sharp(src)
      .resize(planW, planH, { fit: "fill" })
      .png({ compressionLevel: 9, adaptiveFiltering: true })
      .toBuffer();
    expect(firstAttempt.length).toBeLessThanOrEqual(budget);

    const out = await smartResize(src, "image/png", budget);
    expect(out?.mediaType).toBe("image/png");
    expect(await dimsOf(out!.bytes)).toEqual([planW, planH]);
  }, 60_000);

  test("a transparent image stays PNG through the retry too", async () => {
    const src = await noisy(2600, 1800, 128);
    const out = await smartResize(src, "image/png", 60_000);
    expect(out?.mediaType).toBe("image/png");
  }, 60_000);

  test("the result fits the budget", async () => {
    // The one thing the encoder must deliver, whichever encoder it is.
    for (const [w, h, alpha, max] of [
      [1500, 1200, 255, 400_000],
      [1500, 1200, 255, 20_000],
      [3000, 2000, 255, 500_000],
      [2600, 1800, 128, 500_000],
    ] as const) {
      const out = await smartResize(await noisy(w, h, alpha), "image/png", max);
      expect(out).toBeDefined();
      expect(out!.bytes.length).toBeLessThanOrEqual(max);
    }
  }, 60_000);

  test("an opaque image within the floor keeps its dimensions when quality alone suffices", async () => {
    // The quality-only ladder runs first for anything at or under 2048 on its
    // longest side, so a generous budget costs no pixels at all.
    const src = await noisy(800, 600, 255);
    const out = await smartResize(src, "image/png", Math.floor(src.length / 2));
    expect(out?.mediaType).toBe("image/jpeg");
    expect(await dimsOf(out!.bytes)).toEqual([800, 600]);
  });

  test("the quality ladder is not offered above the floor", async () => {
    // A large but highly compressible image: quality-only at full size would
    // clear a generous budget easily. It must not be tried, because a
    // 3000-wide JPEG is exactly what the floor exists to avoid shipping.
    const w = 3000;
    const h = 2000;
    const raw = Buffer.alloc(w * h * 4, 255);
    for (let y = 0; y < h; y += 1) {
      for (let x = 0; x < w; x += 1) raw[(y * w + x) * 4] = (x >> 6) % 256;
    }
    const src = await sharp(raw, { raw: { width: w, height: h, channels: 4 } })
      .removeAlpha()
      .png()
      .toBuffer();
    // Over the source's own size the call short-circuits, so the budget sits
    // between "smaller than the PNG" and "larger than a full-size q90 JPEG" —
    // the exact window where the quality ladder would succeed if it ran.
    const budget = 100_000;
    expect(src.length).toBeGreaterThan(budget);
    const fullSizeJpeg = await sharp(src).resize(w, h, { fit: "fill" }).jpeg({ quality: 90 }).toBuffer();
    expect(fullSizeJpeg.length).toBeLessThan(budget);

    const out = await smartResize(src, "image/png", budget);
    const [outW] = await dimsOf(out!.bytes);
    expect(outW).toBeLessThan(w);
    expect(outW).toBe(planOpaqueDims(w, h, src.length, budget)[0]);
  }, 60_000);
});

describe("smartResize: the retry's own parameters", () => {
  // The retry is reproducible from outside even though the encoder is not:
  // re-encode at the planned dimensions with the same settings, and the byte
  // length that drives the correction is in hand. That makes the factor and
  // the quality step assertable rather than merely documented.

  test("the opaque retry corrects by 0.9 and drops quality to 85", async () => {
    const w = 3000;
    const h = 2000;
    const src = await noisy(w, h, 255);
    const budget = 500_000;

    const [planW, planH] = planOpaqueDims(w, h, src.length, budget);
    const firstAttempt = await sharp(src)
      .resize(planW, planH, { fit: "fill" })
      .jpeg({ quality: 90 })
      .toBuffer();
    // This case exists to exercise the retry; if the first attempt ever fits,
    // the assertions below would be vacuous.
    expect(firstAttempt.length).toBeGreaterThan(budget);

    const out = await smartResize(src, "image/png", budget);
    const [outW, outH] = await dimsOf(out!.bytes);
    expect([outW, outH]).toEqual(planRetryDims(planW, planH, firstAttempt.length, budget, 0.9));

    // And the second encode is at 85, not 90 — same pixels, fewer bytes.
    const atRetryDims = async (quality: number) =>
      (await sharp(src).resize(outW, outH, { fit: "fill" }).jpeg({ quality }).toBuffer()).length;
    expect(out!.bytes.length).toBe(await atRetryDims(85));
    expect(await atRetryDims(85)).not.toBe(await atRetryDims(90));
  }, 60_000);

  test("the transparent retry corrects by 0.85 and stays PNG", async () => {
    const w = 2600;
    const h = 1800;
    const src = await noisy(w, h, 128);
    const budget = 60_000;

    const [planW, planH] = planTransparentDims(w, h, src.length, budget);
    const firstAttempt = await sharp(src)
      .resize(planW, planH, { fit: "fill" })
      .png({ compressionLevel: 9, adaptiveFiltering: true })
      .toBuffer();
    expect(firstAttempt.length).toBeGreaterThan(budget);

    const out = await smartResize(src, "image/png", budget);
    expect(await dimsOf(out!.bytes)).toEqual(
      planRetryDims(planW, planH, firstAttempt.length, budget, 0.85),
    );
    expect(out!.mediaType).toBe("image/png");
  }, 60_000);
});

describe("smartResize: the floor end-to-end, and where the encoders part", () => {
  // The floor arithmetic is verified exactly against the fixture in
  // `planOpaqueDims` above. What can be asserted *end to end* is narrower,
  // because the retry triggers on encoded size and the two encoders disagree
  // about that. Measured: for the same 3000x2000 noise pattern, Rust's PNG is
  // 17.7 MB and libvips' is 2.0 MB, and Rust's JPEG at 2048x1365 fits a 500 KB
  // budget where libvips' does not. Both plans are identical; only the retry
  // differs. So the invariants below are the ones that survive the swap.

  test("the output never exceeds the planned dimensions", async () => {
    // Planned dims are the ceiling: the first attempt uses them exactly, and
    // the retry only ever scales down from them.
    const src = await noisy(3000, 2000, 255);
    const out = await smartResize(src, "image/png", 500_000);
    const [planW, planH] = planOpaqueDims(3000, 2000, src.length, 500_000);
    const [w, h] = await dimsOf(out!.bytes);
    expect(w).toBeLessThanOrEqual(planW);
    expect(h).toBeLessThanOrEqual(planH);
    expect(w).toBeGreaterThan(0);
    expect(h).toBeGreaterThan(0);
  }, 60_000);

  test("the aspect ratio survives both attempts", async () => {
    const src = await noisy(3000, 2000, 255);
    const out = await smartResize(src, "image/png", 500_000);
    const [w, h] = await dimsOf(out!.bytes);
    // 3:2, allowing for a rounded pixel on each axis.
    expect(Math.abs(w / h - 3 / 2)).toBeLessThan(0.01);
  }, 60_000);

  test("a brutal budget drops below the floor, because the retry is not floored", async () => {
    // Worth knowing, and encoder-independent: whichever encoder is in use, a
    // 5 KB budget cannot hold a 2048-wide JPEG, so the retry always runs and
    // always lands under the floor. The floor is a first-attempt guarantee,
    // not an invariant — the fixture recorded the Rust doing exactly this.
    const src = await noisy(4000, 3000, 255);
    const out = await smartResize(src, "image/png", 5_000);
    const [w, h] = await dimsOf(out!.bytes);
    expect(Math.max(w, h)).toBeLessThan(DIMENSION_FLOOR);
    expect(out!.bytes.length).toBeLessThanOrEqual(5_000);
    // ...while the plan it started from was at the floor.
    expect(Math.max(...planOpaqueDims(4000, 3000, src.length, 5_000))).toBe(DIMENSION_FLOOR);
  }, 60_000);
});

// ── Cache ───────────────────────────────────────────────────────────────

describe("computeCacheKey", () => {
  for (const row of fixture.compute_cache_key as {
    path: string;
    mtime_nanos: string;
    max_bytes: string;
    key: string;
  }[]) {
    test(`${JSON.stringify(row.path)} @ ${row.mtime_nanos} / ${row.max_bytes}`, () => {
      // Both widths are carried as strings: a nanosecond timestamp and a u64
      // byte limit both exceed 2^53, and reading them as JSON numbers silently
      // rounds the very input the digest is over.
      const nanos = row.mtime_nanos === "pre-epoch" ? -1n : BigInt(row.mtime_nanos);
      expect(computeCacheKey(row.path, nanos, BigInt(row.max_bytes))).toBe(row.key);
    });
  }

  test("the mtime is hashed as 16 bytes, not 8", () => {
    // A u64-wide mtime produces a different digest for the same inputs, so a
    // narrower write is not a cosmetic difference: it is a cache that never
    // hits and re-encodes every image on every turn.
    expect(computeCacheKey("/a/b.png", 0n, 0)).toBe(
      "9184850d3857e78ac967c72c73fb9de957c55158100fa8ca933f544dc9fe44b9",
    );
  });

  test("every input changes the key", () => {
    const base = computeCacheKey("/a/b.png", 1n, 4096);
    expect(computeCacheKey("/a/c.png", 1n, 4096)).not.toBe(base);
    expect(computeCacheKey("/a/b.png", 2n, 4096)).not.toBe(base);
    expect(computeCacheKey("/a/b.png", 1n, 4097)).not.toBe(base);
  });

  test("a pre-epoch mtime clamps to zero rather than failing", () => {
    expect(computeCacheKey("/a/b.png", -1n, 4096)).toBe(computeCacheKey("/a/b.png", 0n, 4096));
  });
});

describe("cache lookup", () => {
  test("replays the fixture's lookup order", async () => {
    const dir = await tmp();
    await writeCache(dir, "onlyjpg", Buffer.from("JPGDATA"), "image/jpeg");
    await writeCache(dir, "onlypng", Buffer.from("PNGDATA"), "image/png");
    await writeCache(dir, "both", Buffer.from("JPGDATA"), "image/jpeg");
    await writeCache(dir, "both", Buffer.from("PNGDATA"), "image/png");
    await writeCache(dir, "weird", Buffer.from("WEIRD"), "image/webp");

    for (const row of fixture.cache_lookup as {
      key: string;
      hit: { bytes: string; media_type: string } | null;
    }[]) {
      const hit = await readCache(dir, row.key);
      if (row.hit === null) {
        expect(hit).toBeUndefined();
      } else {
        expect(Buffer.from(hit!.bytes).toString()).toBe(row.hit.bytes);
        expect(hit!.mediaType).toBe(row.hit.media_type);
      }
    }
  });

  test("JPEG wins when both extensions exist", async () => {
    const dir = await tmp();
    await writeCache(dir, "k", Buffer.from("JPG"), "image/jpeg");
    await writeCache(dir, "k", Buffer.from("PNG"), "image/png");
    expect((await readCache(dir, "k"))?.mediaType).toBe("image/jpeg");
  });

  test("an unknown media type is filed as jpg", async () => {
    const dir = await tmp();
    await writeCache(dir, "k", Buffer.from("X"), "image/webp");
    expect((await readCache(dir, "k"))?.mediaType).toBe("image/jpeg");
  });

  test("a miss is undefined, not a throw", async () => {
    expect(await readCache(await tmp(), "nope")).toBeUndefined();
  });
});

describe("cachedResize", () => {
  /** The exact file `cachedResize` should have written, derived independently. */
  async function cachePathFor(path: string, maxBytes: number, ext: string): Promise<string> {
    const key = computeCacheKey(path, (await stat(path, { bigint: true })).mtimeNs, maxBytes);
    return join("resized", `${key}.${ext}`);
  }

  test("returns undefined without touching the cache when under the limit", async () => {
    const dir = await tmp();
    const src = await noisy(64, 64, 255);
    const path = join(dir, "small.png");
    await writeFile(path, src);
    expect(await cachedResize(path, src, "image/png", 1_000_000, dir)).toBeUndefined();
    expect(await readdirSafe(join(dir, "resized"))).toEqual([]);
  });

  test("a zero limit returns undefined and writes nothing", async () => {
    const dir = await tmp();
    const src = await noisy(600, 400, 255);
    const path = join(dir, "x.png");
    await writeFile(path, src);
    expect(await cachedResize(path, src, "image/png", 0, dir)).toBeUndefined();
    expect(await readdirSafe(join(dir, "resized"))).toEqual([]);
  }, 60_000);

  test("writes to exactly the key the cache function computes, under resized/", async () => {
    // Both halves matter: the wrong subdirectory or the wrong key is a cache
    // that never hits, which costs a full decode and re-encode every turn
    // while looking like it works.
    const dir = await tmp();
    const src = await noisy(1200, 900, 255);
    const path = join(dir, "photo.png");
    await writeFile(path, src);

    const result = await cachedResize(path, src, "image/png", 60_000, dir);
    expect(result?.mediaType).toBe("image/jpeg");

    const expected = join(dir, await cachePathFor(path, 60_000, "jpg"));
    expect(await Bun.file(expected).exists()).toBe(true);
    expect(Buffer.from(await Bun.file(expected).arrayBuffer())).toEqual(Buffer.from(result!.bytes));
  }, 60_000);

  test("serves a planted entry rather than re-encoding", async () => {
    // Proves the read actually happens: the planted bytes are not something
    // any encoder would produce.
    const dir = await tmp();
    const src = await noisy(1200, 900, 255);
    const path = join(dir, "photo.png");
    await writeFile(path, src);

    const planted = Buffer.from("NOT-AN-IMAGE-BUT-CACHED");
    const target = join(dir, await cachePathFor(path, 60_000, "jpg"));
    await mkdir(join(dir, "resized"), { recursive: true });
    await writeFile(target, planted);

    const result = await cachedResize(path, src, "image/png", 60_000, dir);
    expect(Buffer.from(result!.bytes)).toEqual(planted);
    expect(result!.mediaType).toBe("image/jpeg");
  }, 60_000);

  test("the key tracks nanosecond mtime, not milliseconds", async () => {
    // `mtimeMs` is a float that cannot carry nanosecond precision. A key built
    // from it changes between runs on an unmodified file, so nothing ever hits.
    const dir = await tmp();
    const path = join(dir, "photo.png");
    await writeFile(path, await noisy(64, 64, 255));
    const { mtimeNs, mtimeMs } = await stat(path, { bigint: true }).then((st) => ({
      mtimeNs: st.mtimeNs,
      mtimeMs: BigInt(Math.trunc(Number(st.mtimeNs) / 1e6)),
    }));
    // The file's own timestamp has sub-millisecond precision, so the two keys
    // must differ — that is what makes the width load-bearing rather than
    // theoretical.
    expect(mtimeNs).not.toBe(mtimeMs);
    expect(computeCacheKey(path, mtimeNs, 60_000)).not.toBe(
      computeCacheKey(path, mtimeMs, 60_000),
    );
  });

  test("a changed limit does not reuse the previous entry", async () => {
    const dir = await tmp();
    const src = await noisy(1200, 900, 255);
    const path = join(dir, "photo.png");
    await writeFile(path, src);

    const tight = await cachedResize(path, src, "image/png", 20_000, dir);
    const loose = await cachedResize(path, src, "image/png", 300_000, dir);
    expect(tight!.bytes.length).toBeLessThanOrEqual(20_000);
    expect(loose!.bytes.length).toBeGreaterThan(20_000);
  }, 60_000);
});

// ── Pre-warming ─────────────────────────────────────────────────────────

describe("warmImageCache", () => {
  async function cachePathFor(path: string, maxBytes: number, ext: string): Promise<string> {
    const key = computeCacheKey(path, (await stat(path, { bigint: true })).mtimeNs, maxBytes);
    return join("resized", `${key}.${ext}`);
  }

  test("a zero limit does nothing", async () => {
    const dir = await tmp();
    const path = join(dir, "big.png");
    await writeFile(path, await noisy(1200, 900, 255));
    await warmImageCache([{ images: [{ path }] }], 0, dir);
    expect(await readdirSafe(join(dir, "resized"))).toEqual([]);
  }, 60_000);

  test("warms an oversized image into the cache", async () => {
    const dir = await tmp();
    const path = join(dir, "big.png");
    await writeFile(path, await noisy(1200, 900, 255));
    await warmImageCache([{ images: [{ path }] }], 60_000, dir);
    expect(await Bun.file(join(dir, await cachePathFor(path, 60_000, "jpg"))).exists()).toBe(true);
  }, 60_000);

  test("skips an image already under the limit", async () => {
    // The gate is a stat, so the common case costs one syscall and no decode.
    const dir = await tmp();
    const path = join(dir, "small.png");
    await writeFile(path, await noisy(32, 32, 255));
    await warmImageCache([{ images: [{ path }] }], 60_000, dir);
    expect(await readdirSafe(join(dir, "resized"))).toEqual([]);
  });

  test("an image exactly at the limit is not warmed", async () => {
    const dir = await tmp();
    const src = await noisy(600, 400, 255);
    const path = join(dir, "exact.png");
    await writeFile(path, src);
    await warmImageCache([{ images: [{ path }] }], src.length, dir);
    expect(await readdirSafe(join(dir, "resized"))).toEqual([]);
  }, 60_000);

  test("skips an unknown extension without decoding it", async () => {
    const dir = await tmp();
    const path = join(dir, "big.bmp");
    await writeFile(path, await noisy(1200, 900, 255));
    await warmImageCache([{ images: [{ path }] }], 60_000, dir);
    expect(await readdirSafe(join(dir, "resized"))).toEqual([]);
  }, 60_000);

  test("a missing file never fails the warm-up", async () => {
    const dir = await tmp();
    await expect(
      warmImageCache([{ images: [{ path: join(dir, "gone.png") }] }], 1_000, dir),
    ).resolves.toBeUndefined();
  });

  test("warms every message's images, not just the first", async () => {
    const dir = await tmp();
    const a = join(dir, "a.png");
    const b = join(dir, "b.png");
    await writeFile(a, await noisy(1200, 900, 255));
    await writeFile(b, await noisy(1100, 800, 255));
    await warmImageCache([{ images: [{ path: a }] }, { images: [{ path: b }] }], 60_000, dir);
    expect((await readdirSafe(join(dir, "resized"))).length).toBe(2);
  }, 60_000);
});
