/**
 * Cross-language parity for outbound tool-pair sanitization.
 *
 * The fixture was generated by driving the real Rust in a throwaway worktree at
 * 9023b46d and is frozen. A diff against it is a defect, not a fixture to
 * regenerate.
 *
 * What a failure means: an orphaned `tool_use` or `tool_result` reaching a
 * provider is a hard 400 from Anthropic and the OpenAI family — the turn dies
 * outright, and the user sees a failed message with no indication that the
 * cause was a block left over from an earlier interruption. Failing the other
 * way is quieter and worse: stripping a *paired* block silently removes a tool
 * call the model made from the history it is about to reason over.
 */

import { describe, expect, test } from "bun:test";

import { sanitizeToolPairs } from "../src/llm/sanitize";
import type { WireMessage } from "../src/llm/types";

interface Case {
  name: string;
  messages: WireMessage[];
  /** `null` when the Rust returned `None` — no orphans, send the original. */
  expect: WireMessage[] | null;
}

interface Fixture {
  _header: string[];
  sanitize_tool_pairs: Case[];
}

const fixture = (await Bun.file(
  new URL("./llm_fixtures/sanitize_parity.json", import.meta.url),
).json()) as Fixture;

describe("the fixture is real", () => {
  test("it was frozen, and says so", () => {
    const header = fixture._header.join(" ");
    expect(header).toContain("9023b46d");
    expect(header).toContain("nothing regenerates this file");
  });

  test("both answers are represented", () => {
    // A fixture of only-clean or only-dirty conversations would pass against
    // an implementation that always returned one of them.
    const clean = fixture.sanitize_tool_pairs.filter((c) => c.expect === null);
    const dirty = fixture.sanitize_tool_pairs.filter((c) => c.expect !== null);
    expect(clean.length).toBeGreaterThan(0);
    expect(dirty.length).toBeGreaterThan(0);
  });

  test("a case exists where stripping empties a message entirely", () => {
    const dropped = fixture.sanitize_tool_pairs.filter(
      (c) => c.expect !== null && c.expect.length < c.messages.length,
    );
    expect(dropped.length).toBeGreaterThan(0);
  });

  test("a case exists where a message survives with fewer blocks", () => {
    const trimmed = fixture.sanitize_tool_pairs.filter((c) => {
      if (c.expect === null) return false;
      const before = c.messages.reduce((n, m) => n + m.content.length, 0);
      const after = c.expect.reduce((n, m) => n + m.content.length, 0);
      return c.expect.length === c.messages.length && after < before;
    });
    expect(trimmed.length).toBeGreaterThan(0);
  });
});

describe("sanitizeToolPairs matches the Rust", () => {
  for (const c of fixture.sanitize_tool_pairs) {
    test(c.name, () => {
      const got = sanitizeToolPairs(c.messages);
      if (c.expect === null) {
        // `undefined` is the answer, not an empty array and not a copy.
        expect(got).toBeUndefined();
        return;
      }
      expect(got).toEqual(c.expect);
    });
  }

  test("the input is never mutated", () => {
    // The Rust took `&[WireMessage]` and could not have; TypeScript can, and a
    // caller that passed the request's own messages would find them edited.
    for (const c of fixture.sanitize_tool_pairs) {
      const before = JSON.stringify(c.messages);
      sanitizeToolPairs(c.messages);
      expect(JSON.stringify(c.messages), c.name).toBe(before);
    }
  });
});
