/**
 * Replay of `handler_fixtures/setup_parity.json` against `resolveGenerationModel`
 * and `buildGenerationRequest`.
 *
 * Generated by driving the real Rust at `9023b46d`. Frozen — a diff here is a
 * defect in the port, not a fixture to update.
 *
 * Two shape differences the replay bridges rather than papers over:
 *
 * - **`ResolvedModel` is snake_case in the fixture and camelCase in the port.**
 *   Serde wrote the Rust struct; the catalog port renamed the fields. The
 *   conversion is spelled out here rather than done with a generic key mangler,
 *   so a field the two sides genuinely disagree about cannot be smoothed over
 *   by a rule.
 * - **The engine is an interface, not a conversation on disk.** The Rust locked
 *   a real `ConversationEngine` twice for two reads; `buildGenerationRequest`
 *   takes those two reads directly, so the fixture's recorded history and
 *   segment count are handed straight in. The engine itself is pinned by its
 *   own parity fixture and is not what this one is about.
 *
 * The timezone is passed explicitly for the same reason as `context_parity`:
 * time markers render in local wall-clock, and reading the host's would make the
 * anchor cases pass on the generator's machine and nowhere else.
 */

import { describe, expect, test } from "bun:test";
import { mkdir, mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";

import fixture from "./handler_fixtures/setup_parity.json" with { type: "json" };

import { defaultAppConfig, type AppConfig } from "../src/config/app.ts";
import { characterDataDir, characterWorkspaceDir } from "../src/config/dirs.ts";
import type { ShoreDirs } from "../src/config/dirs.ts";
import type { LoadedConfig } from "../src/config/loader.ts";
import {
  catalogFromSections,
  emptyCatalog,
  type ModelCatalog,
  type ResolvedModel,
} from "../src/config/models.ts";
import { ProviderRegistry } from "../src/config/providers.ts";
import { cachePath } from "../src/llm/discovery.ts";
import type { SamplerSettings } from "../src/config/preferences.ts";
import type { Message } from "../src/engine/types.ts";
import { McpRegistry } from "../src/tools/mcp_registry.ts";
import {
  buildGenerationRequest,
  resolveGenerationModel,
  type MessageOverrides,
  type SetupEngine,
} from "../src/handler/setup.ts";

const ZONE = fixture.timezone as string;

// ── Fixture shapes ──────────────────────────────────────────────────────

/** `ResolvedModel` as serde wrote it: snake_case, absent spelled `null`. */
interface WireModel {
  name: string;
  qualified_name: string;
  category: string;
  provider_key: string;
  sdk: string;
  model_id: string;
  api_key_env: string | null;
  base_url: string | null;
  max_context_tokens: number | null;
  max_output_tokens: number | null;
  temperature: number | null;
  top_p: number | null;
  reasoning_effort: string | null;
  budget_tokens: number | null;
  cache_ttl: string | null;
  cache_keepalive: string | null;
  openrouter_provider: unknown;
  gemini_generation: number | null;
  zai_clear_thinking: boolean | null;
  zai_subscription: boolean | null;
  replay_prior_thinking: string | null;
  max_tool_iterations: number | null;
}

interface ResolveCase {
  name: string;
  note: string;
  input: {
    active_model: WireModel | null;
    default_model: string | null;
    with_catalog: boolean;
    discovery: {
      provider: string;
      /** `visible: false` means the id is listed in `discovery.ignore`. */
      models: { model_id: string; visible: boolean }[];
    } | null;
    overlay: Record<string, unknown>;
  };
  result: { ok: WireModel } | { err: string };
}

interface BuildCase {
  name: string;
  note: string;
  input: {
    history: Message[];
    with_segments: boolean;
    regen: boolean;
    enabled_tools: string[];
    mcp_tools: { server: string; tool: string }[];
    overrides: MessageOverrides | null;
    sdk: string;
    timestamps: "never" | "always" | "auto";
    rich_model: boolean;
    max_context_tokens: number;
    max_output_tokens: number;
    temperature: number;
  };
  request: Record<string, unknown>;
}

const resolveCases = fixture.resolve_generation_model as unknown as ResolveCase[];
const buildCases = fixture.build_generation_request as unknown as BuildCase[];

/** The same two static models the generator's catalog had. */
const CATALOG_TOML = {
  anthropic: {
    alpha: { model_id: "alpha-id", sdk: "anthropic", temperature: 0.1 },
    beta: { model_id: "beta-id", sdk: "anthropic", temperature: 0.2 },
  },
};

// ── Conversions ─────────────────────────────────────────────────────────

/** Drop a serde `null` back to an absent field. */
function some<T>(value: T | null | undefined): T | undefined {
  return value === null ? undefined : value;
}

function opt<K extends string, V>(key: K, value: V | null | undefined): { [P in K]?: V } {
  return (value === null || value === undefined ? {} : { [key]: value }) as { [P in K]?: V };
}

/** The fixture's model, in the catalog's spelling. */
function toModel(w: WireModel): ResolvedModel {
  return {
    name: w.name,
    qualifiedName: w.qualified_name,
    category: w.category,
    providerKey: w.provider_key,
    sdk: w.sdk as ResolvedModel["sdk"],
    modelId: w.model_id,
    ...opt("apiKeyEnv", w.api_key_env),
    ...opt("baseUrl", w.base_url),
    ...opt("maxContextTokens", w.max_context_tokens),
    ...opt("maxOutputTokens", w.max_output_tokens),
    ...opt("temperature", w.temperature),
    ...opt("topP", w.top_p),
    ...opt("reasoningEffort", w.reasoning_effort),
    ...opt("budgetTokens", w.budget_tokens),
    ...opt("cacheTtl", w.cache_ttl),
    ...opt("openrouterProvider", w.openrouter_provider),
    ...opt("geminiGeneration", w.gemini_generation),
    ...opt("zaiClearThinking", w.zai_clear_thinking),
    ...opt("zaiSubscription", w.zai_subscription),
    ...opt("replayPriorThinking", w.replay_prior_thinking as ResolvedModel["replayPriorThinking"]),
    ...opt("maxToolIterations", w.max_tool_iterations),
    // `cache_keepalive` is `"off"` or a duration string on the wire and a parsed
    // union here. No case in this fixture sets it, so rather than reimplement
    // the parser the replay asserts that.
    ...(() => {
      expect(w.cache_keepalive).toBeNull();
      return {};
    })(),
  };
}

/** The port's model, back in the fixture's spelling, for comparison. */
function fromModel(m: ResolvedModel): WireModel {
  return {
    name: m.name,
    qualified_name: m.qualifiedName,
    category: m.category,
    provider_key: m.providerKey,
    sdk: m.sdk,
    model_id: m.modelId,
    api_key_env: m.apiKeyEnv ?? null,
    base_url: m.baseUrl ?? null,
    max_context_tokens: m.maxContextTokens ?? null,
    max_output_tokens: m.maxOutputTokens ?? null,
    temperature: m.temperature ?? null,
    top_p: m.topP ?? null,
    reasoning_effort: m.reasoningEffort ?? null,
    budget_tokens: m.budgetTokens ?? null,
    cache_ttl: m.cacheTtl ?? null,
    cache_keepalive:
      m.cacheKeepalive === undefined
        ? null
        : m.cacheKeepalive.kind === "off"
          ? "off"
          : m.cacheKeepalive.interval.toString(),
    openrouter_provider: m.openrouterProvider ?? null,
    gemini_generation: m.geminiGeneration ?? null,
    zai_clear_thinking: m.zaiClearThinking ?? null,
    zai_subscription: m.zaiSubscription ?? null,
    replay_prior_thinking: m.replayPriorThinking ?? null,
    max_tool_iterations: m.maxToolIterations ?? null,
  };
}

/** The overlay in the port's spelling. Only the fields these cases set. */
function toOverlay(raw: Record<string, unknown>): SamplerSettings {
  return {
    ...opt("temperature", raw["temperature"] as number | null),
    ...opt("topP", raw["top_p"] as number | null),
    ...opt("reasoningEffort", raw["reasoning_effort"] as string | null),
    ...opt("budgetTokens", raw["budget_tokens"] as number | null),
    ...opt("maxOutputTokens", raw["max_output_tokens"] as number | null),
    ...opt("maxToolIterations", raw["max_tool_iterations"] as number | null),
  };
}

function baseConfig(dirs: ShoreDirs, app: AppConfig, models: ModelCatalog): LoadedConfig {
  return { app, models, providers: ProviderRegistry.empty(), dirs, rawTable: undefined };
}

// ── resolve_generation_model ────────────────────────────────────────────

describe("resolveGenerationModel", () => {
  for (const c of resolveCases) {
    test(c.name, async () => {
      const root = await mkdtemp(join(tmpdir(), "shore-resolve-"));
      const dirs: ShoreDirs = {
        config: join(root, "config"),
        data: join(root, "data"),
        cache: join(root, "cache"),
        runtime: join(root, "run"),
      };
      await mkdir(dirs.cache, { recursive: true });

      const app = defaultAppConfig();
      const defaultModel = some(c.input.default_model);
      if (defaultModel !== undefined) app.defaults.model = defaultModel;
      const models = c.input.with_catalog
        ? catalogFromSections(CATALOG_TOML, undefined, undefined, undefined)
        : emptyCatalog();

      let providers = ProviderRegistry.empty();
      const discovery = c.input.discovery;
      if (discovery !== null) {
        providers = ProviderRegistry.fromSection({
          [discovery.provider]: {
            sdk: "anthropic",
            api_key_env: "TEST_KEY",
            discovery: {
              enabled: true,
              ignore: discovery.models.filter((m) => !m.visible).map((m) => m.model_id),
            },
          },
        });
        const path = cachePath(dirs.cache, discovery.provider);
        await mkdir(dirname(path), { recursive: true });
        await writeFile(
          path,
          JSON.stringify({
            version: 1,
            provider_key: discovery.provider,
            fetched_at: "2026-07-01T00:00:00Z",
            models: discovery.models.map((m) => ({
              provider_key: discovery.provider,
              model_id: m.model_id,
              sdk: "anthropic",
              // Required, and its absence is not a soft failure: both sides
              // swallow an unparseable cache into "no cache", so a record
              // without it would leave these cases resolving off the provider
              // entry alone and never touching the cache at all.
              discovered_at: "2026-07-01T00:00:00Z",
              // Upstream metadata is why a cached record is preferred over the
              // bare provider entry. Without it a cache hit and a cache miss
              // build the same model, and the cache directory stops mattering.
              context_length: 250000,
              max_output_tokens: 32000,
            })),
          }),
        );
      }

      const config = { ...baseConfig(dirs, app, models), providers };
      const active = c.input.active_model === null ? undefined : toModel(c.input.active_model);
      const overlay = toOverlay(c.input.overlay);

      if ("err" in c.result) {
        expect(() => resolveGenerationModel(active, config, overlay)).toThrow(c.result.err);
        return;
      }
      expect(fromModel(resolveGenerationModel(active, config, overlay))).toEqual(c.result.ok);
    });
  }
});

// ── build_generation_request ────────────────────────────────────────────

/** The two reads, straight off the fixture. */
function engineFor(c: BuildCase): SetupEngine {
  const history = c.input.history;
  return {
    messages: () => history,
    // `messages_through_last_user_turn`: everything up to and including the
    // most recent user turn. The engine's own fixture pins this; here it is an
    // input, so it is spelled out rather than imported.
    messagesThroughLastUserTurn: () => {
      const last = history.findLastIndex((m) => m.role === "user");
      return last < 0 ? [] : history.slice(0, last + 1);
    },
    segmentCount: () => (c.input.with_segments ? 1 : 0),
  };
}

describe("buildGenerationRequest", () => {
  for (const c of buildCases) {
    test(c.name, async () => {
      const root = await mkdtemp(join(tmpdir(), "shore-build-"));
      const dirs: ShoreDirs = {
        config: join(root, "config"),
        data: join(root, "data"),
        cache: join(root, "cache"),
        runtime: join(root, "run"),
      };
      const workspace = characterWorkspaceDir(dirs.config, "qifei");
      await mkdir(workspace, { recursive: true });
      await writeFile(join(workspace, "SOUL.md"), "I am qifei.\n");
      // Under the *character's* directory, not the data dir: an AGENTS.md that
      // only exists at the right path, so pointing the lookup one level up
      // produces a visibly different system prompt rather than the same one.
      const activePrompt = join(characterDataDir(dirs.data, "qifei"), "active_prompt");
      await mkdir(activePrompt, { recursive: true });
      await writeFile(join(activePrompt, "AGENTS.md"), "Answer as qifei, tersely.\n");
      await mkdir(dirs.cache, { recursive: true });

      const app = defaultAppConfig();
      app.defaults.display_name = "Ash";
      app.behavior.user_message_timestamps = c.input.timestamps;
      app.advanced.max_image_size = 1024;
      app.tools.enabled_tools = c.input.enabled_tools;

      const resolved: ResolvedModel = {
        name: "opus",
        qualifiedName: "chat.anthropic.opus",
        category: "chat",
        providerKey: "anthropic",
        sdk: c.input.sdk as ResolvedModel["sdk"],
        modelId: "opus-id",
        apiKeyEnv: "TEST_KEY",
        maxContextTokens: c.input.max_context_tokens,
        maxOutputTokens: c.input.max_output_tokens,
        temperature: c.input.temperature,
        ...(c.input.rich_model ? { topP: 0.77, reasoningEffort: "high" } : {}),
      };

      // The real registry, not a stand-in: the allowlist match is a glob rule
      // this module hands off rather than owns, and reimplementing it in the
      // replay would test the replay.
      const registry = McpRegistry.fromTools(
        c.input.mcp_tools.map((t) => ({
          server: t.server,
          tool: t.tool,
          full_name: `mcp__${t.server}__${t.tool}`,
          // What the generator's `McpToolDef::new_for_test` produced. The
          // registry forwards both verbatim, so they are inputs here.
          description: `${t.tool} tool`,
          input_schema: { type: "object" },
        })),
      );

      const built = await buildGenerationRequest({
        engine: engineFor(c),
        dataDir: dirs.data,
        charName: "qifei",
        config: baseConfig(dirs, app, emptyCatalog()),
        resolved,
        regen: c.input.regen,
        mcpRegistry: registry,
        ...(c.input.overrides === null ? {} : { overrides: c.input.overrides }),
        timeZone: ZONE,
      });

      expect(JSON.parse(JSON.stringify(built.request))).toEqual(c.request);
    });
  }
});
