/**
 * Parity for `parse_config_table` + `validate_config` — the assembly and
 * cross-field validation half of `crates/common/src/config/mod.rs`.
 *
 * Replays `tests/config_fixtures/validate_parity.json`, generated by driving
 * the real `shore_common::config::load_config` from `main`.
 *
 * Each case is a whole `config.toml`, loaded through `parseConfigTable`. Three
 * things are compared: the outcome, the warnings, and — on success — the parts
 * of the result this layer decides. Warnings are not incidental here: five of
 * `validateConfig`'s six advisory paths have no other observable effect, so an
 * outcome-only replay would pass unchanged against a port that dropped them.
 */

import { describe, expect, test } from "bun:test";

import fixture from "./config_fixtures/validate_parity.json" with { type: "json" };

import {
  ConfigError,
  parseConfigTable,
  type ConfigErrorKind,
  type ConfigWarn,
  type LoadedConfig,
  type TomlTable,
} from "../src/config/loader.ts";
import type { ShoreDirs } from "../src/config/dirs.ts";
import { compareByCodePoint } from "../src/sort.ts";
import { defaultCompactionConfig } from "../src/config/app.ts";

import { pathsSetBy } from "./config_delta.ts";

interface Warning {
  message: string;
  fields: [string, string][];
}

interface Case {
  name: string;
  toml: string;
  warnings: Warning[];
  ok?: {
    chat: { name: string; sdk: string; base_url: string | null }[];
    embedding: string[];
    image_generation: string[];
    providers: { key: string; enabled: boolean }[];
    defaults: Record<string, unknown>;
    raw_table_keys: string[] | null;
    enabled_tools: string[];
    enabled_subagents: string[];
    subagents: string[];
    mcp: string[];
    compaction_enabled: boolean;
  };
  err?: { kind: ConfigErrorKind; message: string };
}

const cases = fixture.cases as unknown as Case[];

/**
 * Cases the sidecar cannot reproduce, because `Bun.TOML.parse` does not decode
 * TOML's non-finite floats.
 *
 * Not a defect in the port and not fixable inside it — the document is already
 * wrong by the time `parseConfigTable` sees it. Excluded here and asserted
 * exactly, in `Bun.TOML.parse non-finite floats` below, so the day Bun fixes
 * this the assertion fails and these come back rather than staying skipped
 * forever.
 */
const BUN_TOML_NONFINITE = new Set([
  "NaN spike multiplier passes every guard",
  "infinite spike multiplier passes",
  "negative infinite min_cost_usd is rejected",
  "NaN budget cost_usd passes",
]);

/**
 * Cases whose TOML sets a `[daemon]` key this schema no longer has.
 *
 * `unsafe_allow_remote_access` and `allowed_hosts` went when every client
 * started presenting a token, so a document carrying them is now a rejection
 * rather than a load. Unlike {@link BUN_TOML_NONFINITE} this is not a gap to
 * be reclaimed later — it is the intended behaviour, asserted on its own in
 * `a config with the deleted [daemon] keys` below.
 */
const USES_DELETED_DAEMON_KEYS = new Set(["unified config"]);

const replayable = cases.filter(
  (c) => !BUN_TOML_NONFINITE.has(c.name) && !USES_DELETED_DAEMON_KEYS.has(c.name),
);

/**
 * Dirs are not what this layer decides — they are `dirs_parity.json`'s subject
 * — and `parseConfigTable` only carries them through onto the result.
 */
const DIRS: ShoreDirs = {
  config: "/nonexistent/config",
  data: "/nonexistent/data",
  runtime: "/nonexistent/runtime",
  cache: "/nonexistent/cache",
};

/**
 * The `[defaults]` block as `serde_json::to_value` rendered it: `Option::None`
 * is `null`, and the key order is the struct's declaration order rather than
 * the object's.
 */
function canonicalDefaults(defaults: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(defaults)) {
    out[key] =
      value === undefined
        ? null
        : typeof value === "object" && value !== null
          ? canonicalDefaults(value as Record<string, unknown>)
          : value;
  }
  return out;
}

function okDigest(loaded: LoadedConfig): Case["ok"] {
  return {
    // `sdk` and `base_url` are recorded because they are what the provider
    // registry cascades into a static entry — the only visible evidence that
    // `parseConfigTable` passed the registry to the catalog builder.
    chat: [...loaded.models.chat].map(([name, model]) => ({
      name,
      sdk: model.sdk,
      base_url: model.baseUrl ?? null,
    })),
    embedding: [...loaded.models.embedding.keys()],
    image_generation: [...loaded.models.imageGeneration.keys()],
    providers: loaded.providers
      .entries()
      .map(([key, entry]) => ({ key, enabled: entry.enabled })),
    defaults: canonicalDefaults(loaded.app.defaults as unknown as Record<string, unknown>),
    // The Rust reads these off a BTreeMap, so code-point order, not the
    // UTF-16 order `Array.prototype.sort` defaults to.
    raw_table_keys: Object.keys(loaded.rawTable ?? {}).sort(compareByCodePoint),
    enabled_tools: loaded.app.tools.enabled_tools,
    enabled_subagents: loaded.app.tools.enabled_subagents,
    subagents: [...loaded.app.subagents.keys()],
    mcp: [...loaded.app.mcp.keys()],
    compaction_enabled: loaded.app.memory.compaction.enabled,
  };
}

/** Run one case, collecting warnings instead of printing them. */
function run(src: string): {
  loaded?: LoadedConfig;
  error?: ConfigError;
  warnings: Warning[];
} {
  const warnings: Warning[] = [];
  const onWarn: ConfigWarn = (message, fields) => {
    warnings.push({ message, fields: fields.map(([k, v]) => [k, v]) });
  };

  const table = Bun.TOML.parse(src) as TomlTable;
  try {
    return { loaded: parseConfigTable(table, { ...DIRS }, onWarn), warnings };
  } catch (e) {
    if (!(e instanceof ConfigError)) throw e;
    return { error: e, warnings };
  }
}

// ── The fixture itself ──────────────────────────────────────────────────

describe("the fixture is real", () => {
  const header = (fixture._header as string[]).join(" ");

  test("it was frozen, and says so", () => {
    expect(header).toContain("nothing");
    expect(header).toContain("regenerates it");
  });

  test("it names `main` as its source, not a worktree", () => {
    expect(header).toContain("GENERATED from `main`");
  });

  test("it covers both outcomes, and warnings on both sides of them", () => {
    // An outcome-only fixture, or one with no multi-fault documents, would
    // pass against a port that got every ordering and severity wrong.
    const errs = replayable.filter((c) => c.err !== undefined);
    expect(replayable.filter((c) => c.err === undefined).length).toBeGreaterThan(30);
    expect(errs.filter((c) => c.err?.kind === "validation").length).toBeGreaterThan(35);
    expect(replayable.filter((c) => c.warnings.length > 0).length).toBeGreaterThan(15);
    // Warnings emitted by a load that then fails: proof the advisory pass runs
    // to completion before the first hard check.
    expect(
      errs.filter((c) => c.warnings.length > 0).length,
    ).toBeGreaterThan(0);
    // More than one warning from a single load, which is what pins their order.
    expect(replayable.filter((c) => c.warnings.length > 1).length).toBeGreaterThan(0);
  });
});

// ── The loads ───────────────────────────────────────────────────────────

describe("the deleted [daemon] keys", () => {
  test("a config that still sets them is rejected, naming the key", () => {
    // The excluded `unified config` case, asserted as what it became. Failing
    // at load is the point: an allowlist that stayed in a file and silently
    // stopped being consulted is the one outcome worth avoiding.
    for (const name of USES_DELETED_DAEMON_KEYS) {
      const c = cases.find((x) => x.name === name);
      expect(c, name).toBeDefined();
      const { error } = run(c!.toml);
      expect(error?.kind, name).toBe("parse_app");
      expect(error?.message, name).toContain("allowed_hosts");
    }
  });
});

const RECORDED_DEFAULT_MAX_TURNS = 16;

function withCurrentCompactionDefaults(message: string, toml: string): string {
  if (pathsSetBy(Bun.TOML.parse(toml)).has("memory.compaction.max_turns")) return message;
  return message.replace(
    `max_turns (${RECORDED_DEFAULT_MAX_TURNS})`,
    `max_turns (${defaultCompactionConfig().max_turns})`,
  );
}

describe("parseConfigTable + validateConfig", () => {
  for (const c of replayable) {
    test(c.name, () => {
      const { loaded, error, warnings } = run(c.toml);

      if (c.err === undefined) {
        expect(error, "expected a successful load").toBeUndefined();
        expect(loaded).toBeDefined();
        if (loaded !== undefined) expect(okDigest(loaded)).toEqual(c.ok);
      } else {
        expect(loaded, "expected a rejection").toBeUndefined();
        expect(error?.kind).toBe(c.err.kind);
        // Validation messages are reproduced exactly. A `toml` parse error's
        // is not — only its semantic half is recorded, and Bun's wording for
        // the same fault is its own. See the fixture header.
        if (c.err.kind === "validation") {
          expect(error?.message).toBe(withCurrentCompactionDefaults(c.err.message, c.toml));
        }
      }

      expect(warnings).toEqual(c.warnings);
    });
  }
});

/**
 * `Bun.TOML.parse` does not implement TOML's non-finite floats, and gets them
 * wrong in three different ways rather than one.
 *
 * Two of them are the dangerous kind. `-inf` and `+inf` come back as signed
 * *zero*, so `min_cost_usd = -inf` — which the daemon rejects — silently
 * passes the sidecar's `< 0.0` guard with no error anywhere. `nan` and `inf`
 * come back as strings, which at least fails loudly as a type error. A float
 * that overflows to infinity takes the whole document down.
 *
 * Nothing in a plausible config writes any of these, and the sidecar has no
 * way to repair a value it never received. It is asserted rather than merely
 * noted because a silent wrong number is exactly the failure that goes
 * unnoticed, and because {@link BUN_TOML_NONFINITE} above should stop excluding
 * cases the moment this changes.
 */
describe("Bun.TOML.parse non-finite floats", () => {
  test("decodes them wrongly, in these specific ways", () => {
    const decode = (src: string): unknown => (Bun.TOML.parse(src) as { a: unknown }).a;

    // Strings, not numbers. Loud: a type error at parse.
    expect(decode("a = nan")).toBe("nan");
    expect(decode("a = inf")).toBe("inf");
    expect(decode("a = [nan]")).toEqual(["nan"]);

    // Signed zero, not infinity. Silent, and the wrong side of every guard.
    expect(Object.is(decode("a = -inf"), -0)).toBe(true);
    expect(Object.is(decode("a = +inf"), 0)).toBe(true);
    expect(Object.is(decode("a = +nan"), 0)).toBe(true);

    // Overflow to infinity takes the document with it.
    expect(() => Bun.TOML.parse("a = 1e400")).toThrow();

    // Finite floats are fine, negative zero included — which is why
    // `cost_usd = -0.0` replays but `-inf` does not.
    expect(Object.is(decode("a = -0.0"), -0)).toBe(true);
    expect(decode("a = 1.5")).toBe(1.5);
  });
});

describe("warning sink", () => {
  // The default sink is what an operator actually reads, so its rendering is
  // asserted rather than left to whatever `console.warn` happened to receive.
  test("renders message then fields", async () => {
    const { consoleConfigWarn } = await import("../src/config/loader.ts");
    const lines: string[] = [];
    const real = console.warn;
    console.warn = (...args: unknown[]) => {
      lines.push(args.map(String).join(" "));
    };
    try {
      consoleConfigWarn("something is off", [
        ["field", "defaults.model"],
        ["name", "ghost"],
      ]);
      consoleConfigWarn("no fields here", []);
    } finally {
      console.warn = real;
    }

    expect(lines).toEqual([
      "shore: something is off field=defaults.model name=ghost",
      "shore: no fields here",
    ]);
  });
});
