// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Base64-encoded character avatar for clients that cannot read the daemon's
 * local config filesystem.
 */
export type CharacterAvatar = { mime_type: string, data: string, };
