// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tool invoked during generation.
 */
export type ToolCall = { rid?: string | null, tool_id: string, tool_name: string, input: unknown, 
/**
 * Sub-agent name when this call is from a nested `ask_<name>` loop; see
 * [`StreamStart::subagent`].
 */
subagent?: string | null, };
