/**
 * Cross-language parity for usage budgets, including the DST-sensitive paths.
 *
 * The fixture was generated by `crates/daemon/tests/budget_parity.rs` under
 * `TZ=America/New_York`, with `now` values straddling both 2026 US transitions.
 * That generator is gone with the Rust budget module it exercised, so the
 * fixture is frozen: it is the last word on what the daemon did, and this is
 * what holds the port to it. The zone is pinned explicitly here.
 *
 * Why this one matters more than most: `enforceBudgetForCall` decides whether a
 * call may spend at all, and it is wrong in two directions. A false allow
 * overspends a budget the user set; a false block silently stops a character
 * from replying. Both halves are compared here, along with the reporting the
 * CLI prints.
 *
 * The warning cases run twice on purpose. Threshold warnings dedup through the
 * `usage_budget_warnings` table, so the second call must return only the "still
 * over budget" re-fires. That is a stateful rule a port can get right the first
 * time and wrong the second.
 */

import { Database } from "bun:sqlite";
import { copyFileSync } from "node:fs";
import { afterAll, expect, test } from "bun:test";

import fixture from "./ledger_fixtures/ledger_budget_parity.json";
import {
  budgetStatuses,
  enforceBudgetForCall,
  newlyCrossedBudgetWarnings,
  spikeWarnings,
  type BudgetCallContext,
  type UsageBudgetConfig,
  type UsageBudgetPeriod,
  type UsageConfig,
} from "../src/ledger/budget.ts";
import { freshLedger, openLedger } from "./support/ledger_fixture.ts";

interface Case {
  config: string;
  now_name: string;
  now: string;
  statuses: unknown[];
  spike_warnings: unknown[];
  warnings_first: unknown[];
  warnings_second: unknown[];
  enforce: Record<string, { allowed: boolean } & Record<string, unknown>>;
}

const doc = fixture as unknown as {
  timezone: string;
  seed: Record<string, unknown>[];
  cases: Case[];
};

const opts = { localZone: doc.timezone };

// ── The configs, mirroring `configs()` in budget_parity.rs ───────────────────

const budget = (
  name: string,
  period: UsageBudgetPeriod,
  cost_usd: number,
): UsageBudgetConfig => ({
  name,
  period,
  cost_usd,
  warn_at: [0.5, 0.805, 1.0],
  limit: "warn",
  usage_kind: [],
});

const pacedWeekly: UsageBudgetConfig = {
  ...budget("weekly", "week", 14.0),
  reset_hour: 6,
  reset_day_of_week: "wednesday",
  pace_period: "day",
};

const blockingDay: UsageBudgetConfig = {
  ...budget("daily-block", "day", 2.0),
  limit: "block",
  reset_hour: 6,
  pace_period: "hour",
  pace_action: "pause_background",
};

const filtered: UsageBudgetConfig = {
  ...budget("aria-tools", "month", 5.0),
  character: "aria",
  usage_kind: ["message_with_tools"],
  limit: "warn",
};

/** Over limit, pausing only background work. */
const backgroundPause: UsageBudgetConfig = {
  ...budget("aria-background", "month", 2.0),
  character: "aria",
  limit: "pause_background",
};

/** Spend lands exactly on the limit — the `>=` boundary. */
const exactLimit: UsageBudgetConfig = {
  ...budget("kai-exact", "month", 0.4),
  character: "kai",
  limit: "block",
};

/** Matches only calls with no configured key name. */
const unknownKey: UsageBudgetConfig = {
  ...budget("unknown-key", "month", 0.5),
  api_key: "unknown",
  limit: "block",
};

const clampedMonth: UsageBudgetConfig = {
  ...budget("month-31", "month", 20.0),
  reset_day_of_month: 31,
  reset_hour: 9,
  pace_period: "week",
};

const SPIKE = {
  enabled: true,
  period: "day" as const,
  multiplier: 1.5,
  min_cost_usd: 0.5,
};

const CONFIGS: Record<string, UsageConfig> = {
  local_paced_weekly: {
    timezone: "local",
    allow_compaction_over_budget: true,
    budgets: [pacedWeekly],
    spike_warnings: SPIKE,
  },
  utc_paced_weekly: {
    timezone: "utc",
    allow_compaction_over_budget: true,
    budgets: [pacedWeekly],
    spike_warnings: SPIKE,
  },
  local_mixed: {
    timezone: "local",
    allow_compaction_over_budget: true,
    budgets: [blockingDay, filtered, clampedMonth],
    spike_warnings: SPIKE,
  },
  local_edges: {
    timezone: "local",
    allow_compaction_over_budget: true,
    budgets: [backgroundPause, exactLimit, unknownKey],
  },
};

/** The call contexts, mirroring `calls()` in budget_parity.rs. */
const CALLS: Record<string, BudgetCallContext> = {
  foreground_aria: {
    provider: "anthropic",
    api_key_name: "default",
    model: "claude-opus-4-6",
    call_type: "message",
    character: "aria",
  },
  tool_loop_aria: {
    provider: "anthropic",
    api_key_name: "default",
    model: "claude-opus-4-6",
    call_type: "tool_loop",
    character: "aria",
  },
  heartbeat_kai: {
    provider: "anthropic",
    api_key_name: "default",
    model: "claude-opus-4-6",
    call_type: "heartbeat",
    character: "kai",
  },
  keepalive_aria: {
    provider: "anthropic",
    api_key_name: "default",
    model: "claude-opus-4-6",
    call_type: "keepalive",
    character: "aria",
  },
  compaction_aria: {
    provider: "anthropic",
    api_key_name: "default",
    model: "claude-opus-4-6",
    call_type: "compaction",
    character: "aria",
  },
  subscription_provider: {
    provider: "opencode-go",
    model: "kimi-k3",
    call_type: "message",
    character: "aria",
  },
  // No key name, which `budgetMatchesCall` reads as "unknown".
  no_key_name: {
    provider: "anthropic",
    model: "claude-opus-4-6",
    call_type: "message",
    character: "aria",
  },
};

// ── Ledger plumbing ──────────────────────────────────────────────────────────

const cleanups: Array<() => void> = [];
afterAll(() => {
  for (const c of cleanups) c();
});

let template: string | undefined;

/** A fresh copy of a daemon-made ledger, seeded with the fixture's rows.
 *
 *  One per case, because `newlyCrossedBudgetWarnings` writes dedup rows — a
 *  shared ledger would make each case depend on the ones before it, which is
 *  exactly the coupling the Rust generator avoids. Booting the daemon 21 times
 *  would be slow, so it boots once for the schema and each case copies the file. */
function caseLedger(index: number): Database {
  if (template === undefined) {
    const f = freshLedger();
    cleanups.push(f.cleanup);
    // Fold the WAL back into the main file so a plain copy carries the schema.
    const db = openLedger(f.path);
    db.run("PRAGMA wal_checkpoint(TRUNCATE)");
    db.close();
    template = f.path;
  }
  const path = `${template}.case${index}`;
  copyFileSync(template, path);
  const db = openLedger(path);
  const columns = Object.keys(doc.seed[0]!);
  const sql = `INSERT INTO calls (${columns.join(", ")}) VALUES (${columns
    .map((c) => `$${c}`)
    .join(", ")})`;
  for (const row of doc.seed) {
    db.query(sql).run(
      Object.fromEntries(
        columns.map((c) => [`$${c}`, row[c] as string | number | null]),
      ),
    );
  }
  return db;
}

test("cross-language budget parity", () => {
  expect(doc.cases.length).toBeGreaterThan(0);

  doc.cases.forEach((c, i) => {
    const config = CONFIGS[c.config];
    expect(config, `fixture config "${c.config}" has no local definition`).toBeDefined();
    const now = Date.parse(c.now);
    const db = caseLedger(i);
    const at = (what: string) => `${c.config}/${c.now_name}: ${what}`;

    expect(budgetStatuses(db, config!, now, opts), at("statuses")).toEqual(
      c.statuses as never,
    );
    expect(spikeWarnings(db, config!, now, opts), at("spike_warnings")).toEqual(
      c.spike_warnings as never,
    );

    // Enforcement before the warning calls, matching the generator: the
    // warnings write rows, and enforcement reads none of them, but ordering is
    // kept identical so any hidden coupling shows up as a diff rather than as
    // a flake.
    for (const [name, call] of Object.entries(CALLS)) {
      const block = enforceBudgetForCall(db, config!, call, now, opts);
      const expected = c.enforce[name]!;
      if (expected.allowed) {
        expect(block, at(`enforce ${name} (expected allow)`)).toBeUndefined();
      } else {
        expect(block, at(`enforce ${name} (expected block)`)).toBeDefined();
        expect({ allowed: false, ...block }, at(`enforce ${name}`)).toEqual(
          expected as never,
        );
      }
    }

    expect(
      newlyCrossedBudgetWarnings(db, config!, now, opts),
      at("warnings_first"),
    ).toEqual(c.warnings_first as never);
    expect(
      newlyCrossedBudgetWarnings(db, config!, now, opts),
      at("warnings_second"),
    ).toEqual(c.warnings_second as never);

    db.close();
  });
});
