/**
 * Cross-language parity for `shore usage`.
 *
 * The fixture was generated by `crates/daemon/tests/usage_parity.rs` under
 * `TZ=America/New_York` at a fixed instant. That generator is gone — the Rust
 * it exercised was deleted once every reader came through the sidecar — so the
 * fixture is frozen, and this is what keeps the port honest against it.
 *
 * What is actually at stake here is narrower than the budget fixture but no
 * less load-bearing: these payloads are what `crates/cli/src/output/commands.rs`
 * renders, key by key. A renamed field prints a blank column, and a `--last`
 * boundary an hour out reports the wrong window — quietly, and in the
 * reassuring direction, because a window that starts too late shows *less*
 * spend than there was.
 *
 * Both timezones are generated because they disagree. At the fixture's `now`,
 * local midnight is 04:00Z, so a seeded call at 02:00Z is inside `today` for a
 * UTC config and outside it for a local one. A port that resolved calendar
 * boundaries in UTC passes every `utc` case here and fails every `local` one.
 */

import { Database } from "bun:sqlite";
import { afterAll, expect, test } from "bun:test";

import fixture from "./ledger_fixtures/ledger_usage_parity.json";
import type { UsageConfig } from "../src/ledger/budget.ts";
import { closeLedgers } from "../src/ledger/record.ts";
import { parseLastPeriod, usageReport } from "../src/ledger/usage.ts";
import { freshLedger, openLedger } from "./support/ledger_fixture.ts";

interface PeriodCase {
  timezone: string;
  last: string;
  since: string | null;
}

interface PayloadCase {
  timezone: string;
  mode: string;
  last: string;
  filter: string;
  payload: unknown;
}

const doc = fixture as unknown as {
  timezone: string;
  now: string;
  seed: Record<string, unknown>[];
  periods: PeriodCase[];
  payloads: PayloadCase[];
};

const NOW = Date.parse(doc.now);
const opts = { localZone: doc.timezone, now: NOW };

/** Mirrors `config()` in usage_parity.rs. */
function config(timezone: string): UsageConfig {
  return {
    timezone,
    allow_compaction_over_budget: false,
    budgets: [
      {
        name: "daily",
        period: "day",
        cost_usd: 0.05,
        warn_at: [0.5, 1.0],
        limit: "warn",
        usage_kind: [],
        reset_hour: 6,
      },
    ],
    spike_warnings: {
      enabled: true,
      period: "day",
      multiplier: 1.5,
      min_cost_usd: 0.001,
    },
  };
}

/** Mirrors `modes()` in usage_parity.rs. */
const MODES: Record<string, Record<string, unknown>> = {
  summary: {},
  budget: { budget: true },
  tsv: { export_tsv: true },
  csv: { export_csv: true },
  by_kind: { by_kind: true },
  by_api_key: { by_api_key: true },
  by_call_type: { by_call_type: true },
  anomalies: { anomalies: true },
};

/** Mirrors `filters()` in usage_parity.rs. */
const FILTERS: Record<string, Record<string, unknown>> = {
  none: {},
  character: { character: "aria" },
  provider: { provider: "anthropic" },
  api_key_unknown: { api_key: "unknown" },
  model: { model: "gpt-5.5" },
  call_type: { call_type: "tool_loop" },
};

const cleanups: Array<() => void> = [];
afterAll(() => {
  closeLedgers();
  for (const c of cleanups) c();
});

/**
 * A daemon-made ledger seeded with the fixture's rows.
 *
 * One for the whole suite: nothing in a `usage` payload writes, so the cases
 * cannot contaminate each other the way the budget fixture's warning dedup can.
 */
function seededLedgerPath(): string {
  const f = freshLedger();
  cleanups.push(f.cleanup);
  const db = openLedger(f.path);
  const columns = Object.keys(doc.seed[0]!);
  const sql = `INSERT INTO calls (${columns.join(", ")}) VALUES (${columns
    .map((c) => `$${c}`)
    .join(", ")})`;
  for (const row of doc.seed) {
    db.query(sql).run(
      Object.fromEntries(columns.map((c) => [`$${c}`, row[c] as string | number | null])),
    );
  }
  db.run("PRAGMA wal_checkpoint(TRUNCATE)");
  db.close();
  return f.path;
}

test("cross-language `--last` window parity", () => {
  expect(doc.periods.length).toBeGreaterThan(0);

  for (const c of doc.periods) {
    expect(
      parseLastPeriod(c.last, NOW, c.timezone, opts) ?? null,
      `${c.timezone}/${JSON.stringify(c.last)}`,
    ).toBe(c.since);
  }
});

test("cross-language usage payload parity", async () => {
  expect(doc.payloads.length).toBeGreaterThan(0);
  const ledger = seededLedgerPath();

  for (const c of doc.payloads) {
    const mode = MODES[c.mode];
    const filter = FILTERS[c.filter];
    expect(mode, `fixture mode "${c.mode}" has no local definition`).toBeDefined();
    expect(filter, `fixture filter "${c.filter}" has no local definition`).toBeDefined();

    const actual = await usageReport(
      {
        ledger,
        args: { last: c.last, ...mode, ...filter },
        usage: config(c.timezone),
      },
      opts,
    );
    expect(
      actual,
      `${c.timezone}/${c.mode}/${c.last}/${c.filter}`,
    ).toEqual(c.payload as never);
  }
});
