/**
 * Cross-language parity for the retry and credential-rotation decisions.
 *
 * The fixture was generated by driving the real Rust in a throwaway worktree at
 * 9023b46d — the last commit where the daemon crate builds — and is frozen. A
 * diff against it is a defect, not a fixture to regenerate.
 *
 * Both of these fail silently, and in opposite directions:
 *
 * - A **retry decision** that gives up too early loses a turn the user paid
 *   for; one that retries a hopeless request spends three calls proving it.
 * - A **credential classification** that misses a rotation strands the user on
 *   a dead key with working keys configured; one that over-rotates walks every
 *   key on what was a passing 503 and reports them all exhausted.
 *
 * Neither surfaces as an error. Both look like "the model was flaky today".
 */

import { describe, expect, test } from "bun:test";

import {
  classifyCredentialFailure,
  defaultApiKeyEnv,
  readCandidateEnv,
  resolveKeyCandidates,
  shouldRotate,
  type CredentialFailureKind,
  type KeyCandidate,
  type ProviderEntry,
} from "../src/llm/credentials";
import type { LlmError } from "../src/llm/errors";
import { isRefusal, shouldRetryError, shouldRetryRefusal, type RetryDecision } from "../src/llm/retry";

interface EncodedError {
  kind: string;
  status?: number;
  body?: string;
  var?: string;
  message?: string;
}

interface PolicyJson {
  max_retries: number;
  fallback_model: string | null;
}

interface Fixture {
  _header: string[];
  default_api_key_env: { provider_key: string; expect: string }[];
  classify_credential_failure: {
    error: EncodedError;
    kind: CredentialFailureKind;
    should_rotate: boolean;
  }[];
  should_retry_error: {
    error: EncodedError;
    attempt: number;
    policy: PolicyJson;
    expect: RetryDecision;
  }[];
  is_refusal: {
    content: string;
    content_len_bytes: number;
    finish_reason: string;
    expect: boolean;
  }[];
  should_retry_refusal: {
    content: string;
    finish_reason: string;
    attempt: number;
    policy: PolicyJson;
    expect: RetryDecision;
  }[];
  resolve_key_candidates: {
    name: string;
    provider_key: string;
    entry: { enabled: boolean; keys: unknown[] } | null;
    fallback_api_key_env: string | null;
    expect: KeyCandidate[];
  }[];
  read_candidate_env: { env: string; set_to: string | null; expect: string | null }[];
}

const fixture = (await Bun.file(
  new URL("./llm_fixtures/llm_decisions_parity.json", import.meta.url),
).json()) as Fixture;

/** Rebuild the `LlmError` the generator encoded. */
function decodeError(e: EncodedError): LlmError {
  switch (e.kind) {
    case "http_status":
      return { kind: "http_status", status: e.status ?? 0, body: e.body ?? "" };
    case "missing_api_key":
      return { kind: "missing_api_key", var: e.var ?? "" };
    case "incomplete_stream":
      return { kind: "incomplete_stream" };
    case "stream_errored":
      return { kind: "stream_errored", message: e.message ?? "" };
    case "provider":
      return { kind: "provider", message: e.message ?? "" };
    case "refusal":
      return { kind: "refusal" };
    default:
      throw new Error(`fixture carries an error kind the replay cannot rebuild: ${e.kind}`);
  }
}

function policyOf(p: PolicyJson) {
  return {
    max_retries: p.max_retries,
    ...(p.fallback_model !== null ? { fallback_model: p.fallback_model } : {}),
  };
}

function label(e: EncodedError): string {
  return e.kind === "http_status" ? `${e.kind} ${String(e.status)} "${e.body ?? ""}"` : e.kind;
}

describe("the fixture is real", () => {
  test("it was frozen, and says so", () => {
    const header = fixture._header.join(" ");
    expect(header).toContain("9023b46d");
    expect(header).toContain("nothing regenerates this file");
  });

  test("a silently empty fixture must not pass", () => {
    expect(fixture.classify_credential_failure.length).toBeGreaterThanOrEqual(20);
    expect(fixture.should_retry_error.length).toBeGreaterThanOrEqual(300);
    expect(fixture.is_refusal.length).toBeGreaterThanOrEqual(20);
    expect(fixture.should_retry_refusal.length).toBeGreaterThanOrEqual(40);
    expect(fixture.resolve_key_candidates.length).toBeGreaterThanOrEqual(6);
  });

  test("the sweep reaches every decision and every classification", () => {
    const decisions = new Set(fixture.should_retry_error.map((c) => c.expect.decision));
    expect(decisions).toEqual(new Set(["retry", "fallback_model", "fail"]));

    const kinds = new Set(fixture.classify_credential_failure.map((c) => c.kind));
    // `unknown` is unreachable from the current classifier — no branch emits
    // it — so five of the seven, plus not_credential_failure.
    expect(kinds).toEqual(
      new Set([
        "missing_key",
        "invalid_key",
        "quota_exhausted",
        "budget_exhausted",
        "rate_limited_credential",
        "not_credential_failure",
      ]),
    );
  });

  test("the refusal cases straddle the byte limit, not the character limit", () => {
    // The whole point of the byte-vs-UTF-16 distinction: a case must exist
    // whose byte length is over 500 while its `.length` is under.
    const multibyte = fixture.is_refusal.filter(
      (c) => c.content_len_bytes > 500 && c.content.length <= 500,
    );
    expect(multibyte.length, "a multi-byte case past the byte limit").toBeGreaterThan(0);
    // And one exactly on the boundary each way.
    const lengths = new Set(fixture.is_refusal.map((c) => c.content_len_bytes));
    expect(lengths.has(500)).toBe(true);
    expect(lengths.has(501)).toBe(true);
  });
});

describe("defaultApiKeyEnv", () => {
  for (const c of fixture.default_api_key_env) {
    test(`${c.provider_key || "(empty)"} -> ${c.expect}`, () => {
      expect(defaultApiKeyEnv(c.provider_key)).toBe(c.expect);
    });
  }
});

describe("classifyCredentialFailure", () => {
  for (const c of fixture.classify_credential_failure) {
    test(`${label(c.error)} -> ${c.kind}`, () => {
      const kind = classifyCredentialFailure("", decodeError(c.error));
      expect(kind).toBe(c.kind);
      expect(shouldRotate(kind)).toBe(c.should_rotate);
    });
  }
});

describe("shouldRetryError", () => {
  test(`all ${String(fixture.should_retry_error.length)} recorded decisions`, () => {
    // The credential short-circuit warns, and a 400-case sweep would put 400
    // lines through the runner. Captured rather than silenced, so the count is
    // still assertable below.
    const warned: string[] = [];
    const realWarn = console.warn;
    console.warn = (...args: unknown[]) => {
      warned.push(args.map(String).join(" "));
    };
    try {
      for (const c of fixture.should_retry_error) {
        const got = shouldRetryError(decodeError(c.error), c.attempt, policyOf(c.policy));
        expect(
          got,
          `${label(c.error)} attempt=${String(c.attempt)} ` +
            `max=${String(c.policy.max_retries)} fallback=${String(c.policy.fallback_model)}`,
        ).toEqual(c.expect);
      }
    } finally {
      console.warn = realWarn;
    }

    // Every rotating case should have said so — the log is how an operator
    // finds out a key was abandoned, so a silent short-circuit is a defect.
    const rotating = fixture.should_retry_error.filter((c) => {
      const kind = classifyCredentialFailure("", decodeError(c.error));
      return shouldRotate(kind);
    });
    expect(warned.length).toBe(rotating.length);
    expect(rotating.length).toBeGreaterThan(0);
  });
});

describe("isRefusal", () => {
  for (const [i, c] of fixture.is_refusal.entries()) {
    const shown = c.content.length > 40 ? `${c.content.slice(0, 40)}…` : c.content;
    test(`#${String(i)} (${String(c.content_len_bytes)} bytes, ${c.finish_reason}) ${JSON.stringify(shown)}`, () => {
      // Guard the fixture's own claim: if these disagree the generator and the
      // replay are not looking at the same string.
      expect(Buffer.byteLength(c.content, "utf8")).toBe(c.content_len_bytes);
      expect(isRefusal(c.content, c.finish_reason)).toBe(c.expect);
    });
  }
});

describe("shouldRetryRefusal", () => {
  test(`all ${String(fixture.should_retry_refusal.length)} recorded decisions`, () => {
    for (const c of fixture.should_retry_refusal) {
      const got = shouldRetryRefusal(
        { content: c.content, finish_reason: c.finish_reason },
        c.attempt,
        policyOf(c.policy),
      );
      expect(
        got,
        `${JSON.stringify(c.content)} / ${c.finish_reason} attempt=${String(c.attempt)} ` +
          `max=${String(c.policy.max_retries)} fallback=${String(c.policy.fallback_model)}`,
      ).toEqual(c.expect);
    }
  });
});

describe("resolveKeyCandidates", () => {
  for (const c of fixture.resolve_key_candidates) {
    test(c.name, () => {
      const entry = (c.entry ?? undefined) as ProviderEntry | undefined;
      const got = resolveKeyCandidates(
        c.provider_key,
        entry,
        c.fallback_api_key_env ?? undefined,
      );
      expect(got).toEqual(c.expect);
    });
  }
});

describe("readCandidateEnv", () => {
  for (const c of fixture.read_candidate_env) {
    test(`${c.env} set to ${JSON.stringify(c.set_to)}`, () => {
      // Injected rather than mutating process.env, so the cases cannot leak
      // into each other or into anything else in the suite.
      const env: Record<string, string | undefined> =
        c.set_to === null ? {} : { [c.env]: c.set_to };
      const candidate: KeyCandidate = { name: "t", env: c.env, warn_on_fallback: false };
      expect(readCandidateEnv(candidate, env)).toBe(c.expect ?? undefined);
    });
  }
});
