/**
 * Replay of `commands_fixtures/navigation_parity.json` against
 * `src/commands/navigation.ts`.
 *
 * Generated by driving the real Rust at `9023b46d`, where `navigation.rs` is
 * byte-identical to the commit this ports at. Frozen — a diff here is a defect
 * in the port, not a fixture to update.
 *
 * Every case is a file tree plus a call. The fixture records only what the call
 * *answered*, so the trees are declared here and have to match what the
 * generator laid down; the temporary root is masked as `<root>` on both sides,
 * because four of `character_info`'s fields are absolute paths and dropping
 * them would stop pinning which directory each one names.
 */

import { describe, expect, test } from "bun:test";
import { mkdir, mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";

import fixture from "./commands_fixtures/navigation_parity.json" with { type: "json" };

import { CommandError } from "../src/commands/errors.ts";
import {
  characterInfo,
  characterMetadata,
  listCharacters,
  listCharactersStandalone,
  switchCharacter,
} from "../src/commands/navigation.ts";

// ── fixture shapes ──────────────────────────────────────────────────────

interface Row {
  name: string;
  note?: string;
  ok?: unknown;
  err?: { code: string; message: string };
}

const row = (section: keyof typeof fixture, name: string): Row => {
  const found = (fixture[section] as unknown as Row[]).find((r) => r.name === name);
  if (found === undefined) throw new Error(`no fixture row named ${JSON.stringify(name)}`);
  return found;
};

// ── the tree ────────────────────────────────────────────────────────────

/** A path ending in `/` is a directory; anything else is a file. */
type Entry = [path: string, bytes?: string | Uint8Array];

interface World {
  root: string;
  config: string;
  data: string;
}

async function build(entries: Entry[]): Promise<World> {
  const root = await mkdtemp(join(tmpdir(), "shore-navigation-"));
  for (const [path, bytes] of entries) {
    const target = join(root, path);
    if (path.endsWith("/")) {
      await mkdir(target, { recursive: true });
      continue;
    }
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, bytes ?? "");
  }
  // The generator's harness creates the data directory unconditionally, before
  // any case-specific entry.
  await mkdir(join(root, "data"), { recursive: true });
  return { root, config: join(root, "config"), data: join(root, "data") };
}

/** Put the temporary root back to the spelling the fixture recorded. */
function scrub(value: unknown, root: string): unknown {
  if (Array.isArray(value)) return value.map((v) => scrub(v, root));
  if (value === null || typeof value !== "object") {
    return typeof value === "string" ? value.replaceAll(root, "<root>") : value;
  }
  const out: Record<string, unknown> = {};
  for (const [key, v] of Object.entries(value as Record<string, unknown>)) {
    out[key] = scrub(v, root);
  }
  return out;
}

async function check(r: Row, root: string, run: () => unknown | Promise<unknown>): Promise<void> {
  let result: unknown;
  let thrown: unknown;
  try {
    result = await run();
  } catch (e) {
    thrown = e;
  }

  if (r.err !== undefined) {
    expect(thrown, r.name).toBeInstanceOf(CommandError);
    expect((thrown as CommandError).code, r.name).toBe(r.err.code as never);
    expect((thrown as CommandError).message, r.name).toBe(r.err.message);
  } else {
    expect(thrown, r.name).toBeUndefined();
    expect(scrub(result, root), r.name).toEqual(r.ok as never);
  }
}

// ── shared trees ────────────────────────────────────────────────────────

const threeCharacters = (): Entry[] => [
  ["config/characters/alpha/workspace/SOUL.md", "Alpha"],
  ["config/characters/mid/workspace/SOUL.md", "Mid"],
  ["config/characters/zulu/workspace/SOUL.md", "Zulu"],
  ["config/characters/notacharacter/"],
  ["config/characters/empty/workspace/"],
];

const longDefinition = (): string => "a".repeat(10) + "\u{1F600}".repeat(600);

// ── list_characters ─────────────────────────────────────────────────────

describe("listCharacters", () => {
  const cases: [name: string, active: string, entries: Entry[]][] = [
    ["nothing on disk: the active character is still listed", "solo", []],
    ["the active character leads, the rest follow sorted", "mid", threeCharacters()],
    ["an active character that is not on disk", "outsider", threeCharacters()],
    [
      "discovery sorts by code point, not case-insensitively",
      "mid",
      [
        ["config/characters/Zebra/workspace/SOUL.md", "Z"],
        ["config/characters/apple/workspace/SOUL.md", "a"],
        ["config/characters/Apple/workspace/SOUL.md", "A"],
        ["config/characters/mid/workspace/SOUL.md", "m"],
      ],
    ],
    [
      "a legacy character.md counts as a character",
      "mid",
      [
        ["config/characters/legacy/character.md", "Legacy"],
        ["config/characters/mid/workspace/SOUL.md", "m"],
      ],
    ],
  ];

  for (const [name, active, entries] of cases) {
    test(name, async () => {
      const world = await build(entries);
      await check(row("list_characters", name), world.root, () =>
        listCharacters(world.config, active),
      );
    });
  }
});

// ── list_characters_standalone, including every avatar case ─────────────

describe("listCharactersStandalone", () => {
  const PNG_BYTES = new Uint8Array([0xff, 0xfe, 0x00]);

  const cases: [name: string, entries: Entry[]][] = [
    [
      "avatar: png wins over every other extension",
      [
        ["config/characters/pngwins/workspace/SOUL.md", "x"],
        ["config/characters/pngwins/avatar.png", PNG_BYTES],
        ["config/characters/pngwins/avatar.jpg", "jpeg-bytes"],
        ["config/characters/pngwins/avatar.jpeg", "jpeg2-bytes"],
        ["config/characters/pngwins/avatar.webp", "webp-bytes"],
      ],
    ],
    [
      "avatar: jpg beats jpeg and webp",
      [
        ["config/characters/jpgwins/workspace/SOUL.md", "x"],
        ["config/characters/jpgwins/avatar.jpg", "abcd"],
        ["config/characters/jpgwins/avatar.jpeg", "jpeg2-bytes"],
        ["config/characters/jpgwins/avatar.webp", "webp-bytes"],
      ],
    ],
    [
      "avatar: jpeg beats webp",
      [
        ["config/characters/jpegwins/workspace/SOUL.md", "x"],
        ["config/characters/jpegwins/avatar.jpeg", "jpeg2-bytes"],
        ["config/characters/jpegwins/avatar.webp", "webp-bytes"],
      ],
    ],
    [
      "avatar: webp is reached last",
      [
        ["config/characters/webponly/workspace/SOUL.md", "x"],
        ["config/characters/webponly/avatar.webp", "webp-bytes"],
      ],
    ],
    [
      "avatar: a zero-byte file is skipped, not embedded empty",
      [
        ["config/characters/emptypng/workspace/SOUL.md", "x"],
        ["config/characters/emptypng/avatar.png", ""],
        ["config/characters/emptypng/avatar.jpg", "jpeg-bytes"],
      ],
    ],
    [
      "avatar: a directory named avatar.png is not a file",
      [
        ["config/characters/dirpng/workspace/SOUL.md", "x"],
        ["config/characters/dirpng/avatar.png/"],
        ["config/characters/dirpng/avatar.jpg", "jpeg-bytes"],
      ],
    ],
    [
      "avatar: only the four exact names in the character directory",
      [
        ["config/characters/noavatar/workspace/SOUL.md", "x"],
        ["config/characters/noavatar/avatar.PNG", "upper"],
        ["config/characters/noavatar/avatar.gif", "gif"],
        ["config/characters/noavatar/avatar", "bare"],
        ["config/characters/noavatar/workspace/avatar.png", "nested"],
      ],
    ],
    ["standalone does not prepend the active character", threeCharacters()],
    ["standalone with nothing on disk is empty", []],
    ["standalone when characters/ is a file", [["config/characters", "not a directory"]]],
  ];

  for (const [name, entries] of cases) {
    test(name, async () => {
      const world = await build(entries);
      await check(row("list_characters_standalone", name), world.root, () =>
        listCharactersStandalone(world.config),
      );
    });
  }
});

// ── character_info ──────────────────────────────────────────────────────

describe("characterInfo", () => {
  const cases: [name: string, active: string, args: Record<string, unknown>, entries: Entry[]][] = [
    ["the active character, minimally furnished", "mid", {}, threeCharacters()],
    [
      "an empty name argument falls back to the active character",
      "mid",
      { name: "" },
      threeCharacters(),
    ],
    [
      "a non-string name argument falls back to the active character",
      "mid",
      { name: 7 },
      threeCharacters(),
    ],
    ["another character by name", "mid", { name: "alpha" }, threeCharacters()],
    ["a character that does not exist", "mid", { name: "ghost" }, threeCharacters()],
    ["the active character with no directory is not a miss", "outsider", {}, threeCharacters()],
    [
      "a directory that exists but is not a discoverable character",
      "mid",
      { name: "undiscoverable" },
      [["config/characters/undiscoverable/"]],
    ],
    [
      "every bootstrap file present, plus a config override",
      "mid",
      {},
      [
        ["config/characters/mid/workspace/SOUL.md", "You are a test character."],
        ["config/characters/mid/workspace/USER.md", "The user likes tests."],
        ["config/characters/mid/workspace/AGENTS.md", "agents"],
        ["config/characters/mid/workspace/TOOLS.md", "tools"],
        ["config/characters/mid/config.toml", "[defaults]\n"],
        ["data/mid/deferred_edits.jsonl", ""],
      ],
    ],
    [
      "bootstrap files keep declaration order with SOUL absent",
      "mid",
      {},
      [
        ["config/characters/mid/workspace/TOOLS.md", "tools"],
        ["config/characters/mid/workspace/AGENTS.md", "agents"],
      ],
    ],
    [
      "the definition preview is 500 characters, not bytes",
      "mid",
      {},
      [["config/characters/mid/workspace/SOUL.md", longDefinition()]],
    ],
    [
      "a definition shorter than the cap is returned whole",
      "mid",
      {},
      [["config/characters/mid/workspace/SOUL.md", "short"]],
    ],
    [
      "an empty SOUL.md is a definition of the empty string",
      "mid",
      {},
      [["config/characters/mid/workspace/SOUL.md", ""]],
    ],
    [
      "an unreadable definition is present with a null preview",
      "mid",
      {},
      [["config/characters/mid/workspace/SOUL.md/"]],
    ],
    [
      "pending deferred edits are deduplicated and sorted",
      "mid",
      {},
      [
        ["config/characters/mid/workspace/SOUL.md", "x"],
        [
          "data/mid/deferred_edits.jsonl",
          '{"path":"USER.md"}\n' +
            '{"path":"AGENTS.md"}\n' +
            '{"path":"USER.md"}\n' +
            "not json at all\n" +
            '{"path":42}\n' +
            '{"nopath":"USER.md"}\n' +
            '{"path":"notes/scratch.md"}\n' +
            "\n" +
            '{"path":"SOUL.md"}\n',
        ],
      ],
    ],
    [
      "an unreadable deferred-edit queue reports nothing pending",
      "mid",
      {},
      [
        ["config/characters/mid/workspace/SOUL.md", "x"],
        ["data/mid/deferred_edits.jsonl/"],
      ],
    ],
    [
      "the queue read is the named character's, not the active one's",
      "mid",
      { name: "alpha" },
      [
        ["config/characters/alpha/workspace/SOUL.md", "Alpha"],
        ["data/alpha/deferred_edits.jsonl", '{"path":"USER.md"}\n'],
      ],
    ],
  ];

  for (const [name, active, args, entries] of cases) {
    test(name, async () => {
      const world = await build(entries);
      await check(row("character_info", name), world.root, async () =>
        await characterInfo({ configDir: world.config, dataDir: world.data, active }, args),
      );
    });
  }
});

// ── switch_character ────────────────────────────────────────────────────

describe("switchCharacter", () => {
  const cases: [name: string, active: string, args: Record<string, unknown>, entries: Entry[]][] = [
    ["a different character that exists", "mid", { name: "alpha" }, threeCharacters()],
    ["switching to the active character changes nothing", "mid", { name: "mid" }, threeCharacters()],
    [
      "the active character does not have to exist on disk",
      "outsider",
      { name: "outsider" },
      threeCharacters(),
    ],
    ["a character that does not exist", "mid", { name: "ghost" }, threeCharacters()],
    ["no name argument", "mid", {}, threeCharacters()],
    ["a non-string name argument is a missing one", "mid", { name: 7 }, threeCharacters()],
    [
      "an empty name resolves to the characters directory itself",
      "mid",
      { name: "" },
      threeCharacters(),
    ],
    [
      "an existing directory that is not a discoverable character",
      "mid",
      { name: "undiscoverable" },
      [["config/characters/undiscoverable/"]],
    ],
  ];

  for (const [name, active, args, entries] of cases) {
    test(name, async () => {
      const world = await build(entries);
      await check(row("switch_character", name), world.root, () =>
        switchCharacter(world.config, active, args),
      );
    });
  }
});

// ── character_metadata, called directly ─────────────────────────────────

describe("characterMetadata", () => {
  const entries: Entry[] = [["config/characters/direct/avatar.jpeg", "abcd"]];

  test("a character with no directory at all", async () => {
    const world = await build(entries);
    await check(row("character_metadata", "a character with no directory at all"), world.root, () =>
      characterMetadata(world.config, "ghost"),
    );
  });

  test("an avatar under a name discovery would not have returned", async () => {
    const world = await build(entries);
    await check(
      row("character_metadata", "an avatar under a name discovery would not have returned"),
      world.root,
      () => characterMetadata(world.config, "direct"),
    );
  });
});
