/**
 * Cross-language parity for the per-tick trigger decision.
 *
 * The fixture is generated by sweeping the real Rust decision
 * (`tick_decisions_match_shared_fixture` in
 * `crates/daemon/src/autonomy/manager.rs`) over 400 input combinations drawn
 * from threshold-adjacent values. It does not walk, because the decision is
 * stateless: a sweep covers it better than any sequence would.
 *
 * What a failure here means: the two implementations disagree about when a
 * character compacts, archives, or dreams. Every one of those spends an LLM
 * call and rewrites the conversation on disk, so a trigger that fires when the
 * Rust would not is not a cosmetic difference — and one that never fires lets
 * the active conversation grow without bound. Treat a diff as a defect until
 * proven otherwise, not as a fixture that needs regenerating.
 */

import { describe, expect, test } from "bun:test";

import { tickDecision, type CompactionReason, type TickInputs } from "../src/autonomy/tick.ts";

interface FixtureInputs {
  autonomy_enabled: boolean;
  paused: boolean;
  heartbeat_enabled: boolean;
  compaction_enabled: boolean;
  compaction_triggered: boolean;
  deep_archive_done: boolean;
  active_turn_count: number;
  min_turns: number;
  max_turns: number;
  idle_secs: number;
  idle_trigger_secs: number;
  archive_after_secs: number;
  dreaming_enabled: boolean;
  dream_backoff_elapsed: boolean;
  ms_since_user: number | null;
  minimum_inactive_ms: number;
}

interface FixtureDecision {
  heartbeat_may_tick: boolean;
  compaction: CompactionReason | null;
  deep_archive: boolean;
  dream: boolean;
}

interface Fixture {
  cases: { inputs: FixtureInputs; decision: FixtureDecision }[];
}

const fixture = (await Bun.file(
  new URL("../../crates/daemon/tests/fixtures/tick_parity.json", import.meta.url),
).json()) as Fixture;

function inputsOf(f: FixtureInputs): TickInputs {
  return {
    autonomyEnabled: f.autonomy_enabled,
    paused: f.paused,
    heartbeatEnabled: f.heartbeat_enabled,
    compactionEnabled: f.compaction_enabled,
    compactionTriggered: f.compaction_triggered,
    deepArchiveDone: f.deep_archive_done,
    activeTurnCount: f.active_turn_count,
    minTurns: f.min_turns,
    maxTurns: f.max_turns,
    idleSecs: f.idle_secs,
    idleTriggerSecs: f.idle_trigger_secs,
    archiveAfterSecs: f.archive_after_secs,
    dreamingEnabled: f.dreaming_enabled,
    dreamBackoffElapsed: f.dream_backoff_elapsed,
    msSinceUser: f.ms_since_user ?? undefined,
    minimumInactiveMs: f.minimum_inactive_ms,
  };
}

describe("the fixture is real", () => {
  test("a silently unreadable fixture must not pass", () => {
    expect(fixture.cases.length).toBeGreaterThan(300);
    const rows = new Set(fixture.cases.map((c) => JSON.stringify(c.inputs)));
    expect(rows.size, "every case is a distinct combination").toBe(fixture.cases.length);
  });

  test("the sweep reaches every outcome the decision can produce", () => {
    // Four gates, but compaction and the deep archive cannot both fire, so the
    // reachable set is 2 heartbeat × 2 dream × 4 compaction states. A sweep
    // that missed any of them would pass against an implementation that could
    // not produce it at all.
    const seen = new Set(
      fixture.cases.map((c) => {
        const d = c.decision;
        return `${d.heartbeat_may_tick}|${d.compaction}|${d.deep_archive}|${d.dream}`;
      }),
    );
    expect(seen.size).toBe(16);
  });

  test("compaction and the deep archive never both fire", () => {
    // The invariant the whole ordering exists to hold. Asserted over the
    // recorded Rust as well as replayed, so a fixture regenerated from a
    // broken Rust would fail here rather than quietly teaching this side.
    for (const c of fixture.cases) {
      expect(c.decision.compaction !== null && c.decision.deep_archive).toBe(false);
    }
  });
});

describe("the sweep replays identically", () => {
  test("every recorded combination", () => {
    for (const [i, c] of fixture.cases.entries()) {
      const got = tickDecision(inputsOf(c.inputs));
      const want = c.decision;
      const where = `case ${i}: ${JSON.stringify(c.inputs)}`;

      expect(got.heartbeatMayTick, `${where} heartbeat`).toBe(want.heartbeat_may_tick);
      expect(got.compaction ?? null, `${where} compaction`).toBe(want.compaction);
      expect(got.deepArchive, `${where} deep archive`).toBe(want.deep_archive);
      expect(got.dream, `${where} dream`).toBe(want.dream);
    }
  });
});
