/**
 * Cross-language shape parity for every type the sidecar mirrors by hand.
 *
 * Six of them — `WireMessage`, `ContentBlock`, the reasoning carrier fields,
 * `SystemBlock`, `ToolDefinition`, `ProviderOptions` — are TypeScript
 * interfaces written to match Rust structs in `crates/daemon/src/llm/types.rs`.
 * Their doc comments all say "the two must change together" and nothing checked
 * that they did. The drift is asymmetric: this side is pinned by the vendor SDK
 * types each adapter feeds, with a compiler behind it, so it is the Rust half
 * that goes quietly stale.
 *
 * The fixture is generated by serde from the real Rust values
 * (`types.rs::tests::wire_shape_matches_shared_fixture`), so it *is* the bytes
 * this side receives rather than a description of them that can rot.
 *
 * The lock closes in both directions:
 *
 *   - Rust gains or renames a field → the fixture changes → the runtime key
 *     assertions below fail, because the fixture carries a key this side never
 *     declared.
 *   - Someone adds that key to a list here → `tsc` rejects it, because the
 *     lists are typed `Array<keyof T>` and the interface does not have it yet.
 *
 * So neither half can move without the other going red.
 */

import { describe, expect, test } from "bun:test";

import type { ContentBlock } from "../src/engine/types.ts";
import { replayableMessages } from "../src/llm/replay.ts";
import { buildAnthropicParams } from "../src/llm/providers/anthropic.ts";
import {
  decodeActionResult,
  type AutonomyAction,
  type AutonomyRequest,
} from "../src/autonomy/executor.ts";
import type {
  ToolCallError,
  ToolCallRequest,
  ToolCallResponse,
  MessagesRequest,
} from "../src/llm/tool_rpc.ts";
import { ToolRpcUnreachable } from "../src/llm/tool_rpc.ts";
import {
  systemToText,
  toolResultText,
  type CallContext,
  type ProviderOptions,
  type SidecarRequest,
  type StreamEvent,
  type SystemBlock,
  type ToolDefinition,
  type WireMessage,
} from "../src/llm/types.ts";

/** The `call_complete` member of the {@link StreamEvent} union. */
type CallComplete = Extract<StreamEvent, { type: "call_complete" }>;

/**
 * The census, typed as what this side *expects* to receive.
 *
 * Deliberately annotated with the mirror types rather than `unknown`: if the
 * daemon stops sending a `SystemBlock`-shaped `system_block`, the tests below
 * that feed it to real code stop compiling.
 */
interface WireFixture {
  tool_rpc: {
    request_tool: { kind: "tool" } & ToolCallRequest;
    request_messages: { kind: "messages" } & MessagesRequest;
    outcome_ran: ToolCallResponse;
    outcome_failed: ToolCallResponse;
    outcome_unreachable: ToolCallError;
    request_autonomy: { kind: "autonomy" } & AutonomyRequest;
    autonomy_actions: AutonomyAction[];
    autonomy_ran: unknown;
    autonomy_ran_quietly: unknown;
    autonomy_failed: unknown;
    autonomy_unreachable: unknown;
  };
  wire_role: Array<WireMessage["role"]>;
  thinking_replay: Array<SidecarRequest["replay_prior_thinking"]>;
  system_block: SystemBlock;
  tool_definition: ToolDefinition;
  call_complete: CallComplete;
  provider_options: { empty: ProviderOptions; full: ProviderOptions };
  call_context: { minimal: CallContext; full: CallContext };
  reasoning_carrier: Record<string, Record<string, unknown>>;
  wire_block: Record<string, ContentBlock>;
  wire_message: { bare: WireMessage; with_provenance: WireMessage };
}

const fixturePath = new URL(
  "../../crates/daemon/tests/fixtures/wire_parity.json",
  import.meta.url,
);
const wire = (await Bun.file(fixturePath).json()) as WireFixture;

/** A named fixture entry, or a loud failure — never a silent `undefined`. */
function pick<T>(map: Record<string, T>, key: string): T {
  const value = map[key];
  if (value === undefined) throw new Error(`fixture is missing "${key}"`);
  return value;
}

/** Narrow to an image block's source, failing loudly on the wrong variant. */
function imageSource(block: ContentBlock): Extract<ContentBlock, { type: "image" }>["source"] {
  if (block.type !== "image") throw new Error(`expected an image block, got "${block.type}"`);
  return block.source;
}

/** Narrow to a tool result's content, which is text or blocks. */
function toolResultContent(block: ContentBlock): string | ContentBlock[] {
  if (block.type !== "tool_result") {
    throw new Error(`expected a tool_result block, got "${block.type}"`);
  }
  return block.content;
}

/** Keys the daemon actually sent, for one fixture value. */
const keysOf = (value: unknown): string[] => Object.keys(value as object).sort();

/**
 * Assert a fixture value carries exactly the declared keys.
 *
 * `declared` is typed `Array<keyof T>`, so it cannot name a field the mirror
 * has not declared — that is the compile-time half of the lock.
 */
function assertKeys<T>(value: unknown, declared: Array<keyof T & string>, what: string) {
  expect(keysOf(value), what).toEqual([...declared].sort());
}

describe("the fixture is real", () => {
  test("a silently unreadable fixture must not pass", () => {
    expect(Object.keys(wire).length).toBeGreaterThan(5);
    expect(Object.keys(wire.wire_block)).toHaveLength(11);
  });
});

describe("scalar mirrors carry exactly the declared fields", () => {
  test("SystemBlock", () => {
    assertKeys<SystemBlock>(wire.system_block, ["text", "label"], "SystemBlock");
    // `label` is cache-load-bearing: the Anthropic adapter anchors the system
    // breakpoint on the last block that is NOT memory_index.
    expect(systemToText([wire.system_block])).toBe("You are a character.");
  });

  test("ToolDefinition", () => {
    assertKeys<ToolDefinition>(
      wire.tool_definition,
      ["name", "description", "input_schema"],
      "ToolDefinition",
    );
  });

  test("CallContext", () => {
    // These labels decide what a ledger row says and — since budget
    // enforcement moved to this side — whether the call is made at all. A
    // renamed `usage` would not fail a build on either side; it would just
    // stop every budget matching, silently, in the allowing direction.
    assertKeys<CallContext>(
      wire.call_context.minimal,
      ["character", "call_type", "thinking_enabled"],
      "CallContext (minimal)",
    );
    assertKeys<CallContext>(
      wire.call_context.full,
      [
        "ledger",
        "character",
        "call_type",
        "api_key_name",
        "thinking_enabled",
        "cache_ttl",
        "reasoning_effort",
        "keepalive_max_secs",
        "forensics_dir",
        "rid",
        "usage",
      ],
      "CallContext (full)",
    );
    // The budget the gate reads must survive the trip with its filters intact:
    // these are the fields `budgetMatchesCall` compares against.
    const budget = wire.call_context.full.usage?.budgets?.[0];
    expect(budget, "the census carries a budget").toBeDefined();
    expect(budget!.period).toBe("week");
    expect(budget!.limit).toBe("block");
    expect(budget!.reset_day_of_week).toBe("wednesday");
    expect(budget!.pace_action).toBe("pause_background");
    expect(budget!.usage_kind).toEqual(["message_with_tools"]);
  });

  test("call_complete", () => {
    // Emitted per provider call in a loop this side drove, and the point at
    // which the ledger row is written. Recording only at the end could write
    // just their sum, and a summed row misreports the cache: its `cache_read`
    // exceeds anything one call made and becomes a baseline the next ordinary
    // message cannot meet.
    //
    // The daemon's copy is deserialize-only, so the census entry is a literal
    // rather than a serialized value — which is exactly why it needs asserting
    // from both ends. `call_complete_parses` is the Rust half.
    assertKeys<CallComplete>(
      wire.call_complete,
      ["type", "usage", "timing", "finish_reason", "continuation"],
      "call_complete",
    );
    expect(wire.call_complete.type).toBe("call_complete");
    assertKeys<CallComplete["usage"]>(
      wire.call_complete.usage,
      ["input_tokens", "output_tokens", "cache_read_tokens", "cache_creation_tokens"],
      "call_complete.usage",
    );
    assertKeys<CallComplete["timing"]>(
      wire.call_complete.timing,
      ["total_ms", "time_to_first_token_ms"],
      "call_complete.timing",
    );
  });

  test("ProviderOptions declares a reader for every knob the daemon sends", () => {
    // The point of typing this: it was `Record<string, unknown>` on both sides
    // until it had accumulated three keys the daemon wrote and no adapter read.
    assertKeys<ProviderOptions>(
      wire.provider_options.full,
      [
        "reasoning_effort",
        "thinking_enabled",
        "budget_tokens",
        "cache_ttl",
        "openrouter_provider",
        "gemini_generation",
        "zai_clear_thinking",
        "zai_subscription",
      ],
      "ProviderOptions",
    );
  });

  test("an unset knob is omitted, never sent as null", () => {
    // What lets `undefined` mean "not configured" without ambiguity.
    expect(wire.provider_options.empty).toEqual({});
  });
});

describe("the tool-call protocol", () => {
  // Hand-written on both sides — the daemon parses what this side writes and
  // this side parses what the daemon answers, with nothing in between to catch
  // a rename. Same reason the wire types are pinned.
  test("a tool call carries exactly the fields the daemon reads", () => {
    assertKeys<{ kind: string } & ToolCallRequest>(
      wire.tool_rpc.request_tool,
      ["kind", "rid", "tool_id", "name", "input"],
      "ToolCallRequest",
    );
    expect(wire.tool_rpc.request_tool.kind).toBe("tool");
  });

  test("reported messages are a different request, not a tool result", () => {
    // Untagged, a message report and a tool call would be told apart only by
    // field presence — and persisting one as the other would record an
    // assistant turn as tool output.
    assertKeys<{ kind: string } & MessagesRequest>(
      wire.tool_rpc.request_messages,
      ["kind", "rid", "messages"],
      "MessagesRequest",
    );
    expect(wire.tool_rpc.request_messages.kind).toBe("messages");
    // Each message carries its own role: the daemon stores what it is told
    // rather than inferring a turn's role from where it arrived.
    for (const message of wire.tool_rpc.request_messages.messages) {
      assertKeys<MessagesRequest["messages"][number]>(
        message,
        ["role", "content_blocks"],
        "ReportedMessage",
      );
    }
    expect(wire.tool_rpc.request_messages.messages.map((m) => m.role)).toEqual([
      "assistant",
      "user",
    ]);
  });

  test("a tool that ran, whether or not it succeeded", () => {
    assertKeys<ToolCallResponse>(
      wire.tool_rpc.outcome_ran,
      ["output", "is_error"],
      "ToolCallResponse",
    );
    assertKeys<ToolCallResponse>(
      wire.tool_rpc.outcome_failed,
      ["output", "is_error"],
      "ToolCallResponse (failed)",
    );
    expect(wire.tool_rpc.outcome_failed.is_error).toBe(true);
  });

  test("a call that never reached a loop is a different shape entirely", () => {
    // The outcome is untagged, so these two shapes are the only thing telling
    // "your tool failed" from "the daemon could not attempt it" — and this side
    // discriminates on the presence of `error`.
    assertKeys<ToolCallError>(
      wire.tool_rpc.outcome_unreachable,
      ["error"],
      "ToolCallError",
    );
    expect("error" in wire.tool_rpc.outcome_ran).toBe(false);
    expect("output" in wire.tool_rpc.outcome_unreachable).toBe(false);
  });
});

describe("the autonomy protocol", () => {
  // Shares the socket with tool calls and nothing else. A rename here is the
  // quiet kind: an action the daemon does not recognise is a character that
  // stops compacting, with no error anywhere — the same failure mode the
  // keepalive's `keepalive_interval_secs` rename produced.
  test("an action carries exactly the fields the daemon reads", () => {
    assertKeys<{ kind: string } & AutonomyRequest>(
      wire.tool_rpc.request_autonomy,
      ["kind", "character", "action"],
      "AutonomyRequest",
    );
    expect(wire.tool_rpc.request_autonomy.kind).toBe("autonomy");
    // No `rid`: an action belongs to a character, not to a request, which is
    // what puts it in a different registry on the far side.
    expect("rid" in wire.tool_rpc.request_autonomy).toBe(false);
  });

  test("every action this side can ask for is one the daemon knows", () => {
    const sendable: AutonomyAction[] = [
      "heartbeat_tick",
      "compact_max_turns",
      "compact_idle",
      "deep_archive",
    ];
    expect(wire.tool_rpc.autonomy_actions).toEqual(sendable);
  });

  test("an action that ran is read for what it changed", () => {
    expect(decodeActionResult(wire.tool_rpc.autonomy_ran, "nova", "heartbeat_tick")).toEqual({
      turnCount: 4,
      events: [{ kind: "message_sent", detail: "Autonomous message sent: hello" }],
      failed: undefined,
    });
  });

  test("an action that changed nothing sends an empty object, not nulls", () => {
    // Both fields are `skip_serializing_if` on the daemon side, so absence is
    // the normal case and has to read as "nothing to apply". A `turn_count`
    // read as 0 here would blank a count that is merely unknown.
    expect(wire.tool_rpc.autonomy_ran_quietly).toEqual({});
    expect(decodeActionResult(wire.tool_rpc.autonomy_ran_quietly, "nova", "deep_archive")).toEqual({
      turnCount: undefined,
      events: [],
      failed: undefined,
    });
  });

  test("an action that ran and failed is a result; one that never ran is a throw", () => {
    // The outcome is untagged, so the presence of `error` is the only thing
    // telling "your compaction failed" from "that character is not loaded" —
    // and the tick treats those completely differently.
    const failed = decodeActionResult(wire.tool_rpc.autonomy_failed, "nova", "compact_idle");
    expect(failed.failed).toBe("no conversation to compact");
    expect(() =>
      decodeActionResult(wire.tool_rpc.autonomy_unreachable, "nova", "compact_idle"),
    ).toThrow(ToolRpcUnreachable);
  });
});

describe("WireMessage", () => {
  test("declares exactly the fields the daemon sends", () => {
    assertKeys<WireMessage>(
      wire.wire_message.with_provenance,
      ["role", "content", "provider_key", "model"],
      "WireMessage",
    );
  });

  test("provenance is optional and absent for daemon-authored turns", () => {
    assertKeys<WireMessage>(wire.wire_message.bare, ["role", "content"], "WireMessage (bare)");
  });

  test("content is always an array — never the bare string it used to be", () => {
    expect(Array.isArray(wire.wire_message.bare.content)).toBe(true);
  });

  test("every role the daemon can send is one this side accepts", () => {
    const roles: Array<WireMessage["role"]> = ["user", "assistant", "system"];
    expect(wire.wire_role).toEqual(roles);
  });

  test("every replay mode the daemon can send is one this side accepts", () => {
    const modes: Array<SidecarRequest["replay_prior_thinking"]> = ["all", "none"];
    expect(wire.thinking_replay).toEqual(modes);
  });
});

describe("ContentBlock variants", () => {
  const block = (name: string) => pick(wire.wire_block, name);

  test("the tag of every variant is one this side discriminates on", () => {
    const known: Array<ContentBlock["type"]> = [
      "text",
      "image",
      "thinking",
      "redacted_thinking",
      "tool_use",
      "tool_result",
    ];
    const sent = new Set(Object.values(wire.wire_block).map((b) => b.type));
    for (const tag of sent) {
      expect(known, `unknown block tag "${tag}"`).toContain(tag);
    }
  });

  test("text / redacted_thinking / tool_use", () => {
    assertKeys<Extract<ContentBlock, { type: "text" }>>(block("text"), ["type", "text"], "text");
    assertKeys<Extract<ContentBlock, { type: "redacted_thinking" }>>(
      block("redacted_thinking"),
      ["type", "data"],
      "redacted_thinking",
    );
    assertKeys<Extract<ContentBlock, { type: "tool_use" }>>(
      block("tool_use"),
      ["type", "id", "name", "input"],
      "tool_use",
    );
  });

  test("image blocks are synthesized by the daemon and must be accepted here", () => {
    assertKeys<Extract<ContentBlock, { type: "image" }>>(block("image"), ["type", "source"], "image");
    assertKeys<Extract<ContentBlock, { type: "image" }>["source"]>(
      imageSource(block("image")),
      ["type", "media_type", "data"],
      "image.source",
    );
  });

  test("each reasoning carrier rides flattened onto the thinking block", () => {
    // Not nested under a `carrier` key — Rust flattens it, so each carrier is a
    // sibling of `thinking`. One stored signature projects to exactly one of
    // these, named for the provider that reads it, so no adapter sniffs a prefix.
    type Thinking = Extract<ContentBlock, { type: "thinking" }>;
    assertKeys<Thinking>(block("thinking_uncarried"), ["type", "thinking"], "thinking (uncarried)");
    assertKeys<Thinking>(
      block("thinking_signature"),
      ["type", "thinking", "signature"],
      "thinking (anthropic/gemini)",
    );
    assertKeys<Thinking>(
      block("thinking_openrouter"),
      ["type", "thinking", "reasoning_details"],
      "thinking (openrouter)",
    );
    assertKeys<Thinking>(
      block("thinking_zai"),
      ["type", "thinking", "reasoning_content"],
      "thinking (zai)",
    );
  });

  test("tool_result content is text or blocks, and is_error is omitted when false", () => {
    type ToolResult = Extract<ContentBlock, { type: "tool_result" }>;
    assertKeys<ToolResult>(
      block("tool_result_text"),
      ["type", "tool_use_id", "content"],
      "tool_result (text)",
    );
    assertKeys<ToolResult>(
      block("tool_result_blocks"),
      ["type", "tool_use_id", "content"],
      "tool_result (blocks)",
    );
    assertKeys<ToolResult>(
      block("tool_result_error"),
      ["type", "tool_use_id", "content", "is_error"],
      "tool_result (error)",
    );

    // The block-shaped form is the generated-image replay path. This side typed
    // it `string` for as long as it existed, so the flattening below silently
    // produced "[object Object]" instead of the caption.
    const blocks = toolResultContent(block("tool_result_blocks"));
    expect(Array.isArray(blocks)).toBe(true);
    expect(toolResultText(blocks)).toBe("a cat");
  });
});

describe("the census survives the real code paths", () => {
  // Key-set assertions catch a renamed field. They do not catch a field this
  // side declares but drops on the floor, so push the whole census through the
  // paths that actually consume it.
  const everyBlock = Object.values(wire.wire_block) as ContentBlock[];

  const req: SidecarRequest = {
    sdk: "anthropic",
    model: "claude-opus-4-8",
    provider_key: "anthropic",
    api_key: "k",
    system: [wire.system_block],
    tools: [wire.tool_definition],
    messages: [
      { role: "user", content: [{ type: "text", text: "hi" }] },
      {
        role: "assistant",
        provider_key: "anthropic",
        model: "claude-opus-4-8",
        content: everyBlock,
      },
    ],
    max_tokens: 64,
    replay_prior_thinking: "all",
    provider_options: wire.provider_options.full,
  };

  test("replay keeps the blocks minted by the active model", () => {
    const out = replayableMessages(req);
    const kept = out[1]?.content.map((b) => b.type) ?? [];
    // Thinking minted by this exact model replays; the foreign carriers do not.
    expect(kept).toContain("thinking");
    expect(kept).toContain("tool_result");
    expect(kept).toContain("image");
  });

  test("the anthropic adapter accepts every variant without throwing", () => {
    const params = buildAnthropicParams(req);
    expect(params.model).toBe("claude-opus-4-8");
    expect(params.tools).toHaveLength(1);
  });
});
