/**
 * Cross-language shape parity for every type the sidecar mirrors by hand.
 *
 * Six of them — `WireMessage`, `ContentBlock`, the reasoning carrier fields,
 * `SystemBlock`, `ToolDefinition`, `ProviderOptions` — are TypeScript
 * interfaces written to match Rust structs in `crates/daemon/src/llm/types.rs`.
 * Their doc comments all say "the two must change together" and nothing checked
 * that they did. The drift is asymmetric: this side is pinned by the vendor SDK
 * types each adapter feeds, with a compiler behind it, so it is the Rust half
 * that goes quietly stale.
 *
 * The fixture is generated by serde from the real Rust values
 * (`types.rs::tests::wire_shape_matches_shared_fixture`), so it *is* the bytes
 * this side receives rather than a description of them that can rot.
 *
 * The lock closes in both directions:
 *
 *   - Rust gains or renames a field → the fixture changes → the runtime key
 *     assertions below fail, because the fixture carries a key this side never
 *     declared.
 *   - Someone adds that key to a list here → `tsc` rejects it, because the
 *     lists are typed `Array<keyof T>` and the interface does not have it yet.
 *
 * So neither half can move without the other going red.
 */

import { describe, expect, test } from "bun:test";

import type { ContentBlock } from "../src/engine/types.ts";
import { replayableMessages } from "../src/llm/replay.ts";
import { buildAnthropicParams } from "../src/llm/providers/anthropic.ts";
import {
  systemToText,
  toolResultText,
  type ProviderOptions,
  type SidecarRequest,
  type SystemBlock,
  type ToolDefinition,
  type WireMessage,
} from "../src/llm/types.ts";

/**
 * The census, typed as what this side *expects* to receive.
 *
 * Deliberately annotated with the mirror types rather than `unknown`: if the
 * daemon stops sending a `SystemBlock`-shaped `system_block`, the tests below
 * that feed it to real code stop compiling.
 */
interface WireFixture {
  wire_role: Array<WireMessage["role"]>;
  thinking_replay: Array<SidecarRequest["replay_prior_thinking"]>;
  system_block: SystemBlock;
  tool_definition: ToolDefinition;
  provider_options: { empty: ProviderOptions; full: ProviderOptions };
  reasoning_carrier: Record<string, Record<string, unknown>>;
  wire_block: Record<string, ContentBlock>;
  wire_message: { bare: WireMessage; with_provenance: WireMessage };
}

const fixturePath = new URL(
  "../../crates/daemon/tests/fixtures/wire_parity.json",
  import.meta.url,
);
const wire = (await Bun.file(fixturePath).json()) as WireFixture;

/** A named fixture entry, or a loud failure — never a silent `undefined`. */
function pick<T>(map: Record<string, T>, key: string): T {
  const value = map[key];
  if (value === undefined) throw new Error(`fixture is missing "${key}"`);
  return value;
}

/** Narrow to an image block's source, failing loudly on the wrong variant. */
function imageSource(block: ContentBlock): Extract<ContentBlock, { type: "image" }>["source"] {
  if (block.type !== "image") throw new Error(`expected an image block, got "${block.type}"`);
  return block.source;
}

/** Narrow to a tool result's content, which is text or blocks. */
function toolResultContent(block: ContentBlock): string | ContentBlock[] {
  if (block.type !== "tool_result") {
    throw new Error(`expected a tool_result block, got "${block.type}"`);
  }
  return block.content;
}

/** Keys the daemon actually sent, for one fixture value. */
const keysOf = (value: unknown): string[] => Object.keys(value as object).sort();

/**
 * Assert a fixture value carries exactly the declared keys.
 *
 * `declared` is typed `Array<keyof T>`, so it cannot name a field the mirror
 * has not declared — that is the compile-time half of the lock.
 */
function assertKeys<T>(value: unknown, declared: Array<keyof T & string>, what: string) {
  expect(keysOf(value), what).toEqual([...declared].sort());
}

describe("the fixture is real", () => {
  test("a silently unreadable fixture must not pass", () => {
    expect(Object.keys(wire).length).toBeGreaterThan(5);
    expect(Object.keys(wire.wire_block)).toHaveLength(11);
  });
});

describe("scalar mirrors carry exactly the declared fields", () => {
  test("SystemBlock", () => {
    assertKeys<SystemBlock>(wire.system_block, ["text", "label"], "SystemBlock");
    // `label` is cache-load-bearing: the Anthropic adapter anchors the system
    // breakpoint on the last block that is NOT memory_index.
    expect(systemToText([wire.system_block])).toBe("You are a character.");
  });

  test("ToolDefinition", () => {
    assertKeys<ToolDefinition>(
      wire.tool_definition,
      ["name", "description", "input_schema"],
      "ToolDefinition",
    );
  });

  test("ProviderOptions declares a reader for every knob the daemon sends", () => {
    // The point of typing this: it was `Record<string, unknown>` on both sides
    // until it had accumulated three keys the daemon wrote and no adapter read.
    assertKeys<ProviderOptions>(
      wire.provider_options.full,
      [
        "reasoning_effort",
        "thinking_enabled",
        "budget_tokens",
        "cache_ttl",
        "openrouter_provider",
        "gemini_generation",
        "zai_clear_thinking",
        "zai_subscription",
      ],
      "ProviderOptions",
    );
  });

  test("an unset knob is omitted, never sent as null", () => {
    // What lets `undefined` mean "not configured" without ambiguity.
    expect(wire.provider_options.empty).toEqual({});
  });
});

describe("WireMessage", () => {
  test("declares exactly the fields the daemon sends", () => {
    assertKeys<WireMessage>(
      wire.wire_message.with_provenance,
      ["role", "content", "provider_key", "model"],
      "WireMessage",
    );
  });

  test("provenance is optional and absent for daemon-authored turns", () => {
    assertKeys<WireMessage>(wire.wire_message.bare, ["role", "content"], "WireMessage (bare)");
  });

  test("content is always an array — never the bare string it used to be", () => {
    expect(Array.isArray(wire.wire_message.bare.content)).toBe(true);
  });

  test("every role the daemon can send is one this side accepts", () => {
    const roles: Array<WireMessage["role"]> = ["user", "assistant", "system"];
    expect(wire.wire_role).toEqual(roles);
  });

  test("every replay mode the daemon can send is one this side accepts", () => {
    const modes: Array<SidecarRequest["replay_prior_thinking"]> = ["all", "none"];
    expect(wire.thinking_replay).toEqual(modes);
  });
});

describe("ContentBlock variants", () => {
  const block = (name: string) => pick(wire.wire_block, name);

  test("the tag of every variant is one this side discriminates on", () => {
    const known: Array<ContentBlock["type"]> = [
      "text",
      "image",
      "thinking",
      "redacted_thinking",
      "tool_use",
      "tool_result",
    ];
    const sent = new Set(Object.values(wire.wire_block).map((b) => b.type));
    for (const tag of sent) {
      expect(known, `unknown block tag "${tag}"`).toContain(tag);
    }
  });

  test("text / redacted_thinking / tool_use", () => {
    assertKeys<Extract<ContentBlock, { type: "text" }>>(block("text"), ["type", "text"], "text");
    assertKeys<Extract<ContentBlock, { type: "redacted_thinking" }>>(
      block("redacted_thinking"),
      ["type", "data"],
      "redacted_thinking",
    );
    assertKeys<Extract<ContentBlock, { type: "tool_use" }>>(
      block("tool_use"),
      ["type", "id", "name", "input"],
      "tool_use",
    );
  });

  test("image blocks are synthesized by the daemon and must be accepted here", () => {
    assertKeys<Extract<ContentBlock, { type: "image" }>>(block("image"), ["type", "source"], "image");
    assertKeys<Extract<ContentBlock, { type: "image" }>["source"]>(
      imageSource(block("image")),
      ["type", "media_type", "data"],
      "image.source",
    );
  });

  test("each reasoning carrier rides flattened onto the thinking block", () => {
    // Not nested under a `carrier` key — Rust flattens it, so each carrier is a
    // sibling of `thinking`. One stored signature projects to exactly one of
    // these, named for the provider that reads it, so no adapter sniffs a prefix.
    type Thinking = Extract<ContentBlock, { type: "thinking" }>;
    assertKeys<Thinking>(block("thinking_uncarried"), ["type", "thinking"], "thinking (uncarried)");
    assertKeys<Thinking>(
      block("thinking_signature"),
      ["type", "thinking", "signature"],
      "thinking (anthropic/gemini)",
    );
    assertKeys<Thinking>(
      block("thinking_openrouter"),
      ["type", "thinking", "reasoning_details"],
      "thinking (openrouter)",
    );
    assertKeys<Thinking>(
      block("thinking_zai"),
      ["type", "thinking", "reasoning_content"],
      "thinking (zai)",
    );
  });

  test("tool_result content is text or blocks, and is_error is omitted when false", () => {
    type ToolResult = Extract<ContentBlock, { type: "tool_result" }>;
    assertKeys<ToolResult>(
      block("tool_result_text"),
      ["type", "tool_use_id", "content"],
      "tool_result (text)",
    );
    assertKeys<ToolResult>(
      block("tool_result_blocks"),
      ["type", "tool_use_id", "content"],
      "tool_result (blocks)",
    );
    assertKeys<ToolResult>(
      block("tool_result_error"),
      ["type", "tool_use_id", "content", "is_error"],
      "tool_result (error)",
    );

    // The block-shaped form is the generated-image replay path. This side typed
    // it `string` for as long as it existed, so the flattening below silently
    // produced "[object Object]" instead of the caption.
    const blocks = toolResultContent(block("tool_result_blocks"));
    expect(Array.isArray(blocks)).toBe(true);
    expect(toolResultText(blocks)).toBe("a cat");
  });
});

describe("the census survives the real code paths", () => {
  // Key-set assertions catch a renamed field. They do not catch a field this
  // side declares but drops on the floor, so push the whole census through the
  // paths that actually consume it.
  const everyBlock = Object.values(wire.wire_block) as ContentBlock[];

  const req: SidecarRequest = {
    sdk: "anthropic",
    model: "claude-opus-4-8",
    provider_key: "anthropic",
    api_key: "k",
    system: [wire.system_block],
    tools: [wire.tool_definition],
    messages: [
      { role: "user", content: [{ type: "text", text: "hi" }] },
      {
        role: "assistant",
        provider_key: "anthropic",
        model: "claude-opus-4-8",
        content: everyBlock,
      },
    ],
    max_tokens: 64,
    replay_prior_thinking: "all",
    provider_options: wire.provider_options.full,
  };

  test("replay keeps the blocks minted by the active model", () => {
    const out = replayableMessages(req);
    const kept = out[1]?.content.map((b) => b.type) ?? [];
    // Thinking minted by this exact model replays; the foreign carriers do not.
    expect(kept).toContain("thinking");
    expect(kept).toContain("tool_result");
    expect(kept).toContain("image");
  });

  test("the anthropic adapter accepts every variant without throwing", () => {
    const params = buildAnthropicParams(req);
    expect(params.model).toBe("claude-opus-4-8");
    expect(params.tools).toHaveLength(1);
  });
});
